spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

vls.cors.allowed-origins=${VLS_CORS_ALLOWED_ORIGINS:https://dierlo.com,https://www.dierlo.com}
