package com.example.valueinsoftbackend.pricing.dynamic.model;

public enum PriceReasonCode {
    MIN_MARGIN_RECOVERY,
    TARGET_MARGIN_ALIGNMENT,
    COST_INCREASE,
    LOW_STOCK_HIGH_DEMAND,
    OVERSTOCK_SLOW_MOVING,
    DEAD_STOCK_CLEARANCE,
    NO_CHANGE_WITHIN_POLICY,
    POLICY_CAP_APPLIED,
    ROUNDING_APPLIED,
    INSUFFICIENT_DATA,
    ZERO_STOCK,
    BELOW_COST_BLOCKED,
    MAX_INCREASE_BLOCKED,
    MAX_DECREASE_BLOCKED
}
