package com.example.valueinsoftbackend.inventory;

import com.example.valueinsoftbackend.AbstractIntegrationTest;
import com.example.valueinsoftbackend.Service.security.AuthorizationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

import java.util.Locale;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.doNothing;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class InventoryTransactionIntegrationTest extends AbstractIntegrationTest {

    private static final int COMPANY_ID = 1;
    private static final int BRANCH_ID = 1;
    private static final int PRODUCT_ID = 1;
    private static final int SUPPLIER_ID = 1000;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockBean
    private AuthorizationService authorizationService;

    @BeforeEach
    void setup() {
        doNothing().when(authorizationService).assertAuthenticatedCapability(
                anyString(), anyInt(), nullable(Integer.class), anyString()
        );

        ensurePublicFixtures();
        ensureTenantInventoryTables();
        ensureProductAndSupplierFixtures();
    }

    @Test
    @WithMockUser(username = "testuser:Owner", roles = {"USER"})
    void shouldAddInventoryTransaction() throws Exception {
        String jsonPayload = String.format(Locale.ROOT, """
                {
                  "productId": %d,
                  "userName": "testuser",
                  "supplierId": %d,
                  "transactionType": "Add",
                  "numItems": 100,
                  "transTotal": 1000,
                  "payType": "Cash",
                  "time": "2026-06-18T00:00:00Z",
                  "remainingAmount": 0,
                  "branchId": %d,
                  "companyId": %d
                }
                """, PRODUCT_ID, SUPPLIER_ID, BRANCH_ID, COMPANY_ID);

        mockMvc.perform(MockMvcRequestBuilders.post("/invTrans/AddTransaction")
                .contentType(MediaType.APPLICATION_JSON)
                .content(jsonPayload))
                .andExpect(status().isCreated());
    }

    private void ensurePublicFixtures() {
        jdbcTemplate.execute("""
                MERGE INTO public."Company" (
                    id, "companyName", "establishedTime", "ownerId", "planName", "planPrice", "currency", "comImg"
                )
                KEY(id)
                VALUES (1, 'Test Company', CURRENT_TIMESTAMP, 1, 'Test', 0, 'EGP', '')
                """);

        jdbcTemplate.execute("""
                MERGE INTO public."Branch" ("branchId", "branchName", "branchLocation", "companyId", "branchEstTime")
                KEY("branchId")
                VALUES (1, 'Test Branch', 'Test', 1, CURRENT_TIMESTAMP)
                """);
    }

    private void ensureTenantInventoryTables() {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS c_1");

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."InventoryTransactions_1" (
                    "transId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "productId" INTEGER,
                    "userName" VARCHAR(60),
                    "supplierId" INTEGER,
                    "transactionType" VARCHAR(30),
                    "NumItems" INTEGER,
                    "transTotal" INTEGER,
                    "payType" VARCHAR(30),
                    "time" TIMESTAMP,
                    "RemainingAmount" INTEGER
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.inventory_product (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id BIGINT NOT NULL DEFAULT 1,
                    product_name VARCHAR(60) NOT NULL,
                    retail_price INTEGER NOT NULL,
                    lowest_price INTEGER NOT NULL,
                    buying_price INTEGER NOT NULL,
                    company_name VARCHAR(60) NOT NULL,
                    product_type VARCHAR(30) NOT NULL,
                    product_state VARCHAR(30) NOT NULL,
                    supplier_id INTEGER NOT NULL DEFAULT 0,
                    major VARCHAR(60) NOT NULL,
                    tracking_type VARCHAR(20) NOT NULL DEFAULT 'QUANTITY',
                    sku VARCHAR(120),
                    barcode VARCHAR(120),
                    serial VARCHAR(120),
                    business_line_key VARCHAR(60),
                    template_key VARCHAR(80),
                    version BIGINT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.inventory_stock_ledger (
                    stock_ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    branch_id INTEGER NOT NULL,
                    product_id BIGINT NOT NULL,
                    product_unit_id BIGINT,
                    quantity_delta INTEGER NOT NULL,
                    movement_type VARCHAR(40) NOT NULL,
                    reference_type VARCHAR(40),
                    reference_id VARCHAR(64),
                    actor_name VARCHAR(100),
                    note VARCHAR(255),
                    supplier_id INTEGER NOT NULL DEFAULT 0,
                    trans_total INTEGER NOT NULL DEFAULT 0,
                    pay_type VARCHAR(30),
                    remaining_amount INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.supplier_1 (
                    "supplierId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "SupplierName" VARCHAR(60),
                    "supplierPhone" VARCHAR(30),
                    "supplierLocation" VARCHAR(255),
                    suplierMajor VARCHAR(60),
                    "supplierRemainig" INTEGER DEFAULT 0,
                    "supplierTotalSales" INTEGER DEFAULT 0,
                    status VARCHAR(20),
                    archive_note VARCHAR(255),
                    archived_at TIMESTAMP
                )
                """);
    }

    private void ensureProductAndSupplierFixtures() {
        jdbcTemplate.update("""
                MERGE INTO c_1.inventory_product (
                    product_id, company_id, product_name, retail_price, lowest_price, buying_price,
                    company_name, product_type, product_state, supplier_id, major, tracking_type
                )
                KEY(product_id)
                VALUES (?, ?, 'Test Product', 10, 10, 5, 'Test Company', 'Unit', 'New', ?, 'General', 'QUANTITY')
                """, PRODUCT_ID, COMPANY_ID, SUPPLIER_ID);

        jdbcTemplate.update("""
                MERGE INTO c_1.supplier_1 (
                    "supplierId", "SupplierName", "supplierPhone", "supplierLocation", suplierMajor,
                    "supplierRemainig", "supplierTotalSales", status
                )
                KEY("supplierId")
                VALUES (?, 'Test Supplier', '01000000001', 'Test', 'General', 0, 0, 'ACTIVE')
                """, SUPPLIER_ID);
    }
}
