package com.example.valueinsoftbackend.migration;

import com.example.valueinsoftbackend.DatabaseRequests.DbBranch;
import com.example.valueinsoftbackend.DatabaseRequests.DbCompany;
import com.example.valueinsoftbackend.DatabaseRequests.DbArOpenItem;
import com.example.valueinsoftbackend.DatabaseRequests.DbApOpenItem;
import com.example.valueinsoftbackend.Service.openitems.ArOpenItemService;
import com.example.valueinsoftbackend.Model.OpenItems.OpenItemsWriteModels;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Stage 1.6 of docs/ar-ap-credit-open-items/OPEN_ITEMS_IMPLEMENTATION_ROADMAP.md.
 *
 * <p>Locks the AR/AP open-items schema contract (V141–V145) BEFORE any service code exists:
 * every CHECK constraint and guard trigger has a kill-test here, so later service work can
 * refactor freely against a pinned contract.</p>
 *
 * <p>Setup mirrors real provisioning: Flyway builds public + the migrations run their tenant
 * loops (no tenants yet), then a fixture tenant is provisioned the way DbCompany/DbBranch do
 * it (legacy DDL) and the ensure_* functions are invoked directly — which is exactly the
 * Stage 2 bootstrap path. Calling them twice proves idempotency.</p>
 */
@Tag("postgres")
@Testcontainers(disabledWithoutDocker = true)
class OpenItemsMigrationIT {

    private static final int COMPANY_ID = 9001;
    private static final int BRANCH_ID = 9101;
    private static final String SCHEMA = "c_" + COMPANY_ID;
    private static final int JAVA_PROVISIONED_COMPANY_ID = 9002;
    private static final int JAVA_PROVISIONED_BRANCH_ID = 9102;
    private static final String JAVA_PROVISIONED_SCHEMA = "c_" + JAVA_PROVISIONED_COMPANY_ID;
    private static final String CHECK_VIOLATION = "23514";
    private static final AtomicInteger SEQ = new AtomicInteger(1);

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>(
            DockerImageName.parse("pgvector/pgvector:pg16").asCompatibleSubstituteFor("postgres"))
            .withDatabaseName("vls_openitems_test")
            .withUsername("vls")
            .withPassword("vls");

    @BeforeAll
    static void migrateAndProvisionFixtureTenant() throws Exception {
        Flyway flyway = Flyway.configure()
                .dataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .load();
        assertTrue(flyway.migrate().success, "Flyway migration must succeed on a fresh PostgreSQL");

        try (Connection c = connect(); Statement s = c.createStatement()) {
            // -- public fixtures ------------------------------------------------
            s.execute("INSERT INTO public.\"Company\" (id, \"companyName\", currency) "
                    + "VALUES (" + COMPANY_ID + ", 'OpenItemsCo', 'EGP')");
            s.execute("INSERT INTO public.\"Branch\" (\"branchId\", \"branchName\", \"companyId\") "
                    + "VALUES (" + BRANCH_ID + ", 'Main', " + COMPANY_ID + ")");

            // -- tenant schema + legacy tables (faithful to DbCompany/DbBranch DDL) ----
            s.execute("CREATE SCHEMA IF NOT EXISTS " + SCHEMA);
            s.execute("CREATE TABLE " + SCHEMA + ".\"Client\" ("
                    + " c_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,"
                    + " \"clientName\" varchar, \"clientPhone\" varchar, gender varchar,"
                    + " description varchar, \"branchId\" integer,"
                    + " \"registeredTime\" timestamp,"
                    + " CONSTRAINT \"Client_Key\" PRIMARY KEY (c_id))");
            s.execute("CREATE TABLE " + SCHEMA + ".\"ClientReceipts\" ("
                    + " \"crId\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " type varchar(20) NOT NULL, amount money NOT NULL,"
                    + " \"time\" timestamp NOT NULL, \"userName\" varchar(25) NOT NULL,"
                    + " \"clientId\" integer NOT NULL, \"branchId\" integer NOT NULL)");
            s.execute("CREATE TABLE " + SCHEMA + ".\"supplierReciepts\" ("
                    + " \"srId\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " \"transId\" integer NOT NULL, \"amountPaid\" money NOT NULL,"
                    + " \"remainingAmount\" money NOT NULL, \"receiptTime\" timestamp NOT NULL,"
                    + " \"userRecived\" varchar NOT NULL, \"supplierId\" integer NOT NULL,"
                    + " type varchar(15) NOT NULL, \"branchId\" integer NOT NULL)");
            s.execute("CREATE TABLE " + SCHEMA + ".supplier_" + BRANCH_ID + " ("
                    + " \"supplierId\" SERIAL PRIMARY KEY, \"SupplierName\" varchar NOT NULL,"
                    + " \"supplierRemainig\" integer DEFAULT 0, \"supplierTotalSales\" integer DEFAULT 0,"
                    + " \"supplierStatus\" varchar(32) NOT NULL DEFAULT 'active')");

            // -- ensure functions: the exact calls DbCompany bootstrap will make (Stage 2.1).
            // Invoked TWICE to prove idempotency.
            for (int i = 0; i < 2; i++) {
                s.execute("SELECT public.ensure_ar_open_items_foundation_for_tenant('" + SCHEMA + "', " + COMPANY_ID + ")");
                s.execute("SELECT public.ensure_ap_open_items_foundation_for_tenant('" + SCHEMA + "', " + COMPANY_ID + ")");
                s.execute("SELECT public.ensure_receipt_hardening_for_tenant('" + SCHEMA + "', " + COMPANY_ID + ")");
                s.execute("SELECT public.ensure_credit_debit_notes_for_tenant('" + SCHEMA + "', " + COMPANY_ID + ")");
            }
        }
    }

    // =====================================================================
    // Structure
    // =====================================================================

    @Test
    void structuresAndTriggersExist() throws Exception {
        try (Connection c = connect()) {
            for (String table : new String[]{"ar_open_item", "ar_receipt_allocation",
                    "ap_open_item", "ap_payment_allocation", "ar_credit_note", "ap_debit_note"}) {
                assertTrue(tableExists(c, table), "Expected " + SCHEMA + "." + table);
            }
            for (String column : new String[]{"credit_limit", "credit_terms_days", "credit_status", "credit_notes"}) {
                assertTrue(columnExists(c, "Client", column), "Expected Client." + column);
            }
            assertTrue(columnExists(c, "supplier_" + BRANCH_ID, "payment_terms_days"),
                    "Expected supplier_<b>.payment_terms_days");
            for (String column : new String[]{"status", "reversal_of_id", "idempotency_key", "payment_method"}) {
                assertTrue(columnExists(c, "ClientReceipts", column), "Expected ClientReceipts." + column);
            }
            for (String trigger : new String[]{"trg_ar_open_item_guard", "trg_ar_alloc_insert_guard",
                    "trg_ar_alloc_mutation_guard", "trg_ap_open_item_guard", "trg_ap_alloc_insert_guard",
                    "trg_ap_alloc_mutation_guard", "trg_ar_credit_note_guard", "trg_ap_debit_note_guard"}) {
                assertTrue(triggerExists(c, trigger), "Expected trigger " + trigger);
            }
        }
    }

    @Test
    void javaProvisioningMatchesMigratedOpenItemsStructure() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        DbBranch dbBranch = new DbBranch(jdbcTemplate);
        DbCompany dbCompany = new DbCompany(
                jdbcTemplate,
                new NamedParameterJdbcTemplate(jdbcTemplate),
                dbBranch,
                POSTGRES.getUsername(),
                false);

        jdbcTemplate.update("INSERT INTO public.\"Company\" (id, \"companyName\", currency) VALUES (?, ?, ?)",
                JAVA_PROVISIONED_COMPANY_ID, "JavaProvisionedOpenItemsCo", "EGP");
        jdbcTemplate.update("INSERT INTO public.\"Branch\" (\"branchId\", \"branchName\", \"companyId\") VALUES (?, ?, ?)",
                JAVA_PROVISIONED_BRANCH_ID, "Java Main", JAVA_PROVISIONED_COMPANY_ID);

        assertTrue(dbCompany.createCompanySchema(JAVA_PROVISIONED_COMPANY_ID),
                "DbCompany must provision the open-items tenant structures");
        assertTrue(dbBranch.createSupplierTable(JAVA_PROVISIONED_BRANCH_ID, JAVA_PROVISIONED_COMPANY_ID),
                "DbBranch must provision the supplier table with payment terms");

        try (Connection c = connect()) {
            for (String table : new String[]{"ar_open_item", "ar_receipt_allocation",
                    "ap_open_item", "ap_payment_allocation", "ar_credit_note", "ap_debit_note"}) {
                assertEquals(columnSignatures(c, SCHEMA, table, null),
                        columnSignatures(c, JAVA_PROVISIONED_SCHEMA, table, null),
                        "Java-provisioned " + table + " must match the migrated tenant");
            }

            assertEquals(
                    columnSignatures(c, SCHEMA, "Client",
                            List.of("credit_limit", "credit_terms_days", "credit_status", "credit_notes")),
                    columnSignatures(c, JAVA_PROVISIONED_SCHEMA, "Client",
                            List.of("credit_limit", "credit_terms_days", "credit_status", "credit_notes")));
            assertEquals(
                    columnSignatures(c, SCHEMA, "ClientReceipts",
                            List.of("status", "reversal_of_id", "idempotency_key", "payment_method")),
                    columnSignatures(c, JAVA_PROVISIONED_SCHEMA, "ClientReceipts",
                            List.of("status", "reversal_of_id", "idempotency_key", "payment_method")));
            assertEquals(
                    columnSignatures(c, SCHEMA, "supplierReciepts",
                            List.of("status", "reversal_of_id", "idempotency_key")),
                    columnSignatures(c, JAVA_PROVISIONED_SCHEMA, "supplierReciepts",
                            List.of("status", "reversal_of_id", "idempotency_key")));
            assertEquals(
                    columnSignatures(c, SCHEMA, "supplier_" + BRANCH_ID, List.of("payment_terms_days")),
                    columnSignatures(c, JAVA_PROVISIONED_SCHEMA, "supplier_" + JAVA_PROVISIONED_BRANCH_ID,
                            List.of("payment_terms_days")));
        }
    }

    @Test
    void capabilitySeedsUseNewKeysAndLeaveV134Untouched() throws Exception {
        try (Connection c = connect()) {
            assertTrue(capabilityExists(c, "clients.account.statement.view"));
            assertTrue(capabilityExists(c, "clients.openitems.allocate"));
            assertTrue(capabilityExists(c, "suppliers.openitems.view"));
            // B8 regression: the V134 trade-in key keeps its original meaning.
            try (PreparedStatement p = c.prepareStatement(
                    "SELECT description FROM public.platform_capabilities WHERE capability_key = 'clients.statement.view'")) {
                ResultSet rs = p.executeQuery();
                assertTrue(rs.next(), "V134 capability must still exist");
                assertEquals("View a client seller statement (trade-in receipts, payments, balance).",
                        rs.getString(1), "V134 description must not be re-described (review blocker B8)");
            }
        }
    }

    // =====================================================================
    // ar_open_item constraints
    // =====================================================================

    @Test
    void openItemRejectsInconsistentStatusAndAmounts() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            // settled + remaining != total
            expectSqlState(CHECK_VIOLATION, () -> insertArOpenItemRaw(c, clientId, "100", "10", "100", "OPEN"));
            // SETTLED but remaining > 0
            expectSqlState(CHECK_VIOLATION, () -> insertArOpenItemRaw(c, clientId, "100", "50", "50", "SETTLED"));
            // negative remaining
            expectSqlState(CHECK_VIOLATION, () -> insertArOpenItemRaw(c, clientId, "100", "150", "-50", "OPEN"));
            // valid document
            long id = insertArOpenItem(c, clientId, "100");
            assertTrue(id > 0);
        }
    }

    @Test
    void openItemIdentityIsImmutableAndUndeletable() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            long id = insertArOpenItem(c, clientId, "80");
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "UPDATE " + SCHEMA + ".ar_open_item SET total_amount = 90, remaining_amount = 90 WHERE open_item_id = " + id));
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "DELETE FROM " + SCHEMA + ".ar_open_item WHERE open_item_id = " + id));
            // Legitimate settlement update passes.
            exec(c, "UPDATE " + SCHEMA + ".ar_open_item SET settled_amount = 80, remaining_amount = 0, "
                    + "status = 'SETTLED', version = version + 1 WHERE open_item_id = " + id);
        }
    }

    // =====================================================================
    // ar_receipt_allocation guards
    // =====================================================================

    @Test
    void allocationEnforcesCapsAndCoherence() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            int otherClient = insertClient(c);
            int receiptId = insertReceipt(c, clientId, "100");
            long itemA = insertArOpenItem(c, clientId, "60");
            long itemB = insertArOpenItem(c, clientId, "60");
            long foreignItem = insertArOpenItem(c, otherClient, "60");

            // over open-item remaining
            expectSqlState(CHECK_VIOLATION, () -> insertArAllocation(c, clientId, receiptId, itemA, "70", "EGP"));
            // cross-client
            expectSqlState(CHECK_VIOLATION, () -> insertArAllocation(c, clientId, receiptId, foreignItem, "10", "EGP"));
            // currency mismatch
            expectSqlState(CHECK_VIOLATION, () -> insertArAllocation(c, clientId, receiptId, itemA, "10", "USD"));

            // valid: 60 to A, then receipt cap blocks 50 more (60 + 50 > 100)
            insertArAllocation(c, clientId, receiptId, itemA, "60", "EGP");
            settleAr(c, itemA, "60", "60", "0", "SETTLED");
            expectSqlState(CHECK_VIOLATION, () -> insertArAllocation(c, clientId, receiptId, itemB, "50", "EGP"));
            // 40 more is exactly the receipt cap -> allowed
            insertArAllocation(c, clientId, receiptId, itemB, "40", "EGP");
        }
    }

    @Test
    void allocationIsAppendOnlyWithExactReversalMirrors() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            int receiptId = insertReceipt(c, clientId, "50");
            long item = insertArOpenItem(c, clientId, "50");
            long alloc = insertArAllocation(c, clientId, receiptId, item, "50", "EGP");
            settleAr(c, item, "50", "50", "0", "SETTLED");

            // no in-place edits, no deletes
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "UPDATE " + SCHEMA + ".ar_receipt_allocation SET amount = 10 WHERE allocation_id = " + alloc));
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "DELETE FROM " + SCHEMA + ".ar_receipt_allocation WHERE allocation_id = " + alloc));

            // reversal mirror with the wrong amount is rejected
            expectSqlState(CHECK_VIOLATION, () -> insertArReversal(c, clientId, receiptId, item, "40", alloc));
            // exact mirror is accepted, then the original may flip POSTED -> REVERSED
            insertArReversal(c, clientId, receiptId, item, "50", alloc);
            exec(c, "UPDATE " + SCHEMA + ".ar_receipt_allocation SET status = 'REVERSED' WHERE allocation_id = " + alloc);
            // service re-opens the item after reversal
            settleAr(c, item, "50", "0", "50", "OPEN");
            // double reversal is rejected (original no longer POSTED)
            expectSqlState(CHECK_VIOLATION, () -> insertArReversal(c, clientId, receiptId, item, "50", alloc));
        }
    }

    @Test
    void allocationRequiresExactlyOneSource() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            long item = insertArOpenItem(c, clientId, "30");
            // neither receipt nor credit note
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "INSERT INTO " + SCHEMA + ".ar_receipt_allocation "
                            + "(company_id, branch_id, client_id, receipt_id, credit_note_id, open_item_id, amount, currency_code, idempotency_key) "
                            + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", NULL, NULL, " + item + ", 10, 'EGP', '" + key() + "')"));
        }
    }

    @Test
    void creditNoteApplicationIsCappedByNoteTotal() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            long itemA = insertArOpenItem(c, clientId, "30");
            long itemB = insertArOpenItem(c, clientId, "30");
            long note = insertCreditNote(c, clientId, "40");

            exec(c, "INSERT INTO " + SCHEMA + ".ar_receipt_allocation "
                    + "(company_id, branch_id, client_id, credit_note_id, open_item_id, amount, currency_code, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", " + note + ", " + itemA + ", 30, 'EGP', '" + key() + "')");
            settleAr(c, itemA, "30", "30", "0", "SETTLED");
            exec(c, "UPDATE " + SCHEMA + ".ar_credit_note SET applied_amount = 30, unapplied_amount = 10, "
                    + "status = 'PARTIALLY_APPLIED', version = version + 1 WHERE credit_note_id = " + note);

            // 30 applied + 20 > 40 total -> rejected
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "INSERT INTO " + SCHEMA + ".ar_receipt_allocation "
                            + "(company_id, branch_id, client_id, credit_note_id, open_item_id, amount, currency_code, idempotency_key) "
                            + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", " + note + ", " + itemB + ", 20, 'EGP', '" + key() + "')"));
        }
    }

    // =====================================================================
    // AP side (symmetric code — spot checks on the AP-specific rules)
    // =====================================================================

    @Test
    void apAllocationRejectsBranchAndSupplierMismatch() throws Exception {
        try (Connection c = connect()) {
            long item = insertApOpenItem(c, 501, BRANCH_ID, "100");
            int receipt = insertSupplierReceipt(c, 501, BRANCH_ID, "50");
            int foreignReceipt = insertSupplierReceipt(c, 777, BRANCH_ID, "50");

            // receipt belongs to another supplier
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "INSERT INTO " + SCHEMA + ".ap_payment_allocation "
                            + "(company_id, branch_id, supplier_id, receipt_id, open_item_id, amount, currency_code, idempotency_key) "
                            + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", 501, " + foreignReceipt + ", " + item + ", 10, 'EGP', '" + key() + "')"));
            // allocation row claiming a different branch than the open item
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "INSERT INTO " + SCHEMA + ".ap_payment_allocation "
                            + "(company_id, branch_id, supplier_id, receipt_id, open_item_id, amount, currency_code, idempotency_key) "
                            + "VALUES (" + COMPANY_ID + ", " + (BRANCH_ID + 1) + ", 501, " + receipt + ", " + item + ", 10, 'EGP', '" + key() + "')"));
            // valid
            exec(c, "INSERT INTO " + SCHEMA + ".ap_payment_allocation "
                    + "(company_id, branch_id, supplier_id, receipt_id, open_item_id, amount, currency_code, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", 501, " + receipt + ", " + item + ", 50, 'EGP', '" + key() + "')");
        }
    }

    @Test
    void clientReceiptStatusIsConstrained() throws Exception {
        try (Connection c = connect()) {
            int clientId = insertClient(c);
            expectSqlState(CHECK_VIOLATION, () -> exec(c,
                    "INSERT INTO " + SCHEMA + ".\"ClientReceipts\" (type, amount, \"time\", \"userName\", \"clientId\", \"branchId\", status) "
                            + "VALUES ('ReceiveVMoney', 10::numeric::money, NOW(), 'tester', " + clientId + ", " + BRANCH_ID + ", 'DELETED')"));
        }
    }

    @Test
    void arReadRepositoryStatementAndAgingReconcileToOpenItems() throws Exception {
        int clientId;
        long currentItem;
        long overdueItem;
        try (Connection c = connect()) {
            clientId = insertClient(c);
            currentItem = insertArOpenItem(c, clientId, "100");
            overdueItem = insertArOpenItem(c, clientId, "50");
            exec(c, "UPDATE " + SCHEMA + ".ar_open_item SET due_date = CURRENT_DATE + 5 WHERE open_item_id = " + currentItem);
            exec(c, "UPDATE " + SCHEMA + ".ar_open_item SET due_date = CURRENT_DATE - 15 WHERE open_item_id = " + overdueItem);
        }

        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        DbArOpenItem repository = new DbArOpenItem(new NamedParameterJdbcTemplate(dataSource));
        LocalDate today = LocalDate.now();

        var statement = repository.getStatement(
                COMPANY_ID, BRANCH_ID, clientId, today.minusDays(1), today.plusDays(1));
        var aging = repository.getAging(COMPANY_ID, BRANCH_ID, clientId, today);

        assertEquals(0, new java.math.BigDecimal("150.0000").compareTo(statement.closingBalance().get("EGP")));
        assertEquals(1, aging.currencies().size());
        assertEquals(0, new java.math.BigDecimal("150.0000").compareTo(aging.currencies().get(0).total()));
        assertEquals(0, new java.math.BigDecimal("100.0000").compareTo(aging.currencies().get(0).current()));
        assertEquals(0, new java.math.BigDecimal("50.0000").compareTo(aging.currencies().get(0).days1To30()));
    }

    @Test
    void apReadRepositoryStatementAndAgingReconcileToOpenItems() throws Exception {
        long currentItem;
        long overdueItem;
        try (Connection c = connect()) {
            currentItem = insertApOpenItem(c, 501, BRANCH_ID, "80");
            overdueItem = insertApOpenItem(c, 501, BRANCH_ID, "20");
            exec(c, "UPDATE " + SCHEMA + ".ap_open_item SET due_date = CURRENT_DATE + 5 WHERE open_item_id = " + currentItem);
            exec(c, "UPDATE " + SCHEMA + ".ap_open_item SET due_date = CURRENT_DATE - 45 WHERE open_item_id = " + overdueItem);
        }

        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        DbApOpenItem repository = new DbApOpenItem(new NamedParameterJdbcTemplate(dataSource));
        LocalDate today = LocalDate.now();

        var statement = repository.getStatement(
                COMPANY_ID, BRANCH_ID, 501, today.minusDays(1), today.plusDays(1));
        var aging = repository.getAging(COMPANY_ID, BRANCH_ID, 501, today);

        assertEquals(0, new java.math.BigDecimal("100.0000").compareTo(statement.closingBalance().get("EGP")));
        assertEquals(1, aging.currencies().size());
        assertEquals(0, new java.math.BigDecimal("100.0000").compareTo(aging.currencies().get(0).total()));
        assertEquals(0, new java.math.BigDecimal("80.0000").compareTo(aging.currencies().get(0).current()));
        assertEquals(0, new java.math.BigDecimal("20.0000").compareTo(aging.currencies().get(0).days31To60()));
    }

    @Test
    void concurrentAllocationsSerializeWithoutOverSettlement() throws Exception {
        int clientId;
        int receiptId;
        long openItemId;
        try (Connection c = connect()) {
            clientId = insertClient(c);
            receiptId = insertReceipt(c, clientId, "100");
            openItemId = insertArOpenItem(c, clientId, "100");
        }

        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        DbArOpenItem repository = new DbArOpenItem(new NamedParameterJdbcTemplate(dataSource));
        // The concurrency test exercises allocateReceipt only; GL reversal posting is not on
        // this path, so a mock posting service keeps the fixture minimal.
        ArOpenItemService service = new ArOpenItemService(repository,
                org.mockito.Mockito.mock(com.example.valueinsoftbackend.Service.finance.FinanceOperationalPostingService.class));
        TransactionTemplate transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        CyclicBarrier start = new CyclicBarrier(2);
        ExecutorService pool = Executors.newFixedThreadPool(2);
        try {
            java.util.concurrent.Callable<Boolean> allocation = () -> {
                start.await();
                try {
                    transaction.executeWithoutResult(ignored -> service.allocateReceipt(
                            COMPANY_ID, BRANCH_ID, clientId, receiptId,
                            new OpenItemsWriteModels.AllocationCommand("EGP", key(), List.of(
                                    new OpenItemsWriteModels.AllocationTarget(openItemId, new java.math.BigDecimal("70.0000")))),
                            "concurrency-test"));
                    return true;
                } catch (RuntimeException exception) {
                    return false;
                }
            };
            Future<Boolean> first = pool.submit(allocation);
            Future<Boolean> second = pool.submit(allocation);
            int successes = (first.get() ? 1 : 0) + (second.get() ? 1 : 0);
            assertEquals(1, successes, "Exactly one competing 70 allocation may succeed against a 100 item");
        } finally {
            pool.shutdownNow();
        }

        try (Connection c = connect(); PreparedStatement p = c.prepareStatement(
                "SELECT settled_amount, remaining_amount FROM " + SCHEMA + ".ar_open_item WHERE open_item_id=?")) {
            p.setLong(1, openItemId);
            ResultSet rs = p.executeQuery();
            assertTrue(rs.next());
            assertEquals(0, new java.math.BigDecimal("70.0000").compareTo(rs.getBigDecimal(1)));
            assertEquals(0, new java.math.BigDecimal("30.0000").compareTo(rs.getBigDecimal(2)));
        }
    }

    /**
     * Phase 8.3 opt-in soak: 50 independent receipts contend for ten FIFO items.
     * Run with -Dopenitems.soak.enabled=true on a Docker-enabled host.
     */
    @Test
    void fiftyConcurrentAllocationsAcrossTenItemsHaveNoDeadlocks() throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(Boolean.getBoolean("openitems.soak.enabled"));
        int clientId;
        int[] receiptIds = new int[50];
        try (Connection c = connect()) {
            clientId = insertClient(c);
            for (int i = 0; i < 10; i++) insertArOpenItem(c, clientId, "10");
            for (int i = 0; i < receiptIds.length; i++) receiptIds[i] = insertReceipt(c, clientId, "2");
        }

        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        DbArOpenItem repository = new DbArOpenItem(new NamedParameterJdbcTemplate(dataSource));
        ArOpenItemService service = new ArOpenItemService(repository,
                org.mockito.Mockito.mock(com.example.valueinsoftbackend.Service.finance.FinanceOperationalPostingService.class));
        TransactionTemplate transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        long deadlocksBefore = databaseDeadlocks();
        CyclicBarrier start = new CyclicBarrier(receiptIds.length);
        AtomicInteger failures = new AtomicInteger();

        try (ExecutorService pool = Executors.newVirtualThreadPerTaskExecutor()) {
            List<Future<?>> futures = new ArrayList<>();
            for (int receiptId : receiptIds) {
                futures.add(pool.submit(() -> {
                    start.await();
                    try {
                        transaction.executeWithoutResult(ignored -> service.allocateReceipt(
                                COMPANY_ID, BRANCH_ID, clientId, receiptId,
                                new OpenItemsWriteModels.AllocationCommand("EGP", key(), List.of()), "phase8-soak"));
                    } catch (RuntimeException exception) {
                        failures.incrementAndGet();
                    }
                    return null;
                }));
            }
            for (Future<?> future : futures) future.get();
        }

        assertEquals(0, failures.get(), "Every serialized FIFO allocation must succeed");
        assertEquals(deadlocksBefore, databaseDeadlocks(), "The soak must not increase PostgreSQL deadlocks");
        try (Connection c = connect(); Statement s = c.createStatement(); ResultSet rs = s.executeQuery(
                "SELECT SUM(settled_amount), SUM(remaining_amount) FROM " + SCHEMA
                        + ".ar_open_item WHERE client_id=" + clientId)) {
            assertTrue(rs.next());
            assertEquals(0, new java.math.BigDecimal("100.0000").compareTo(rs.getBigDecimal(1)));
            assertEquals(0, java.math.BigDecimal.ZERO.compareTo(rs.getBigDecimal(2)));
        }
    }

    /** Phase 8.3 opt-in throughput soak for 1,000 FIFO receipts. */
    @Test
    void oneThousandReceiptsAllocateFifoWithoutDrift() throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(Boolean.getBoolean("openitems.soak.enabled"));
        int clientId;
        long openItemId;
        int[] receiptIds = new int[1000];
        try (Connection c = connect()) {
            clientId = insertClient(c);
            openItemId = insertArOpenItem(c, clientId, "1000");
            for (int i = 0; i < receiptIds.length; i++) receiptIds[i] = insertReceipt(c, clientId, "1");
        }
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        ArOpenItemService service = new ArOpenItemService(new DbArOpenItem(new NamedParameterJdbcTemplate(dataSource)),
                org.mockito.Mockito.mock(com.example.valueinsoftbackend.Service.finance.FinanceOperationalPostingService.class));
        TransactionTemplate transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));

        for (int receiptId : receiptIds) {
            transaction.executeWithoutResult(ignored -> service.allocateReceipt(
                    COMPANY_ID, BRANCH_ID, clientId, receiptId,
                    new OpenItemsWriteModels.AllocationCommand("EGP", key(), List.of()), "phase8-batch"));
        }

        try (Connection c = connect(); PreparedStatement p = c.prepareStatement(
                "SELECT settled_amount, remaining_amount FROM " + SCHEMA + ".ar_open_item WHERE open_item_id=?")) {
            p.setLong(1, openItemId);
            ResultSet rs = p.executeQuery();
            assertTrue(rs.next());
            assertEquals(0, new java.math.BigDecimal("1000.0000").compareTo(rs.getBigDecimal(1)));
            assertEquals(0, java.math.BigDecimal.ZERO.compareTo(rs.getBigDecimal(2)));
        }
    }

    /** Phase 8.3: concurrent exposure checks serialize on the client row. */
    @Test
    void concurrentExposureChecksCannotOversubscribeClientLimit() throws Exception {
        org.junit.jupiter.api.Assumptions.assumeTrue(Boolean.getBoolean("openitems.soak.enabled"));
        int clientId;
        try (Connection c = connect()) {
            clientId = insertClient(c);
            exec(c, "UPDATE " + SCHEMA + ".\"Client\" SET credit_limit=100 WHERE c_id=" + clientId);
        }
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        DbArOpenItem repository = new DbArOpenItem(new NamedParameterJdbcTemplate(dataSource));
        TransactionTemplate transaction = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        CyclicBarrier start = new CyclicBarrier(20);
        AtomicInteger accepted = new AtomicInteger();

        try (ExecutorService pool = Executors.newVirtualThreadPerTaskExecutor()) {
            List<Future<?>> futures = new ArrayList<>();
            for (int i = 0; i < 20; i++) {
                int sale = i;
                futures.add(pool.submit(() -> {
                    start.await();
                    transaction.executeWithoutResult(ignored -> {
                        repository.lockClientCredit(COMPANY_ID, clientId);
                        java.math.BigDecimal exposure = repository.sumClientOpenExposure(
                                COMPANY_ID, clientId, "EGP");
                        if (exposure.add(java.math.BigDecimal.TEN).compareTo(new java.math.BigDecimal("100")) <= 0) {
                            repository.createOpenItem(COMPANY_ID, BRANCH_ID, clientId, "POS_ORDER",
                                    800000L + sale, "P8-SALE-" + sale, java.time.LocalDateTime.now(),
                                    java.time.LocalDateTime.now(), "EGP", java.math.BigDecimal.TEN,
                                    "phase8-credit-sale-" + clientId + "-" + sale, "phase8-soak");
                            accepted.incrementAndGet();
                        }
                    });
                    return null;
                }));
            }
            for (Future<?> future : futures) future.get();
        }

        assertEquals(10, accepted.get(), "Only ten 10-unit sales may fit a 100-unit limit");
        assertEquals(0, new java.math.BigDecimal("100").compareTo(
                repository.sumClientOpenExposure(COMPANY_ID, clientId, "EGP")));
    }

    // =====================================================================
    // Helpers
    // =====================================================================

    private static Connection connect() throws SQLException {
        return DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
    }

    private static long databaseDeadlocks() throws SQLException {
        try (Connection c = connect(); PreparedStatement p = c.prepareStatement(
                "SELECT deadlocks FROM pg_stat_database WHERE datname=current_database()");
             ResultSet rs = p.executeQuery()) {
            assertTrue(rs.next());
            return rs.getLong(1);
        }
    }

    private static String key() {
        return "it-" + SEQ.getAndIncrement();
    }

    private static void exec(Connection c, String sql) throws SQLException {
        try (Statement s = c.createStatement()) {
            s.execute(sql);
        }
    }

    private interface SqlAction {
        void run() throws Exception;
    }

    private static void expectSqlState(String state, SqlAction action) {
        try {
            action.run();
            fail("Expected SQLSTATE " + state + " but statement succeeded");
        } catch (SQLException e) {
            assertEquals(state, e.getSQLState(),
                    "Expected SQLSTATE " + state + " but got " + e.getSQLState() + ": " + e.getMessage());
        } catch (Exception e) {
            fail("Expected SQLException, got " + e);
        }
    }

    private static int insertClient(Connection c) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".\"Client\" (\"clientName\", \"branchId\", \"registeredTime\") "
                    + "VALUES ('IT Client', " + BRANCH_ID + ", NOW()) RETURNING c_id");
            rs.next();
            return rs.getInt(1);
        }
    }

    private static int insertReceipt(Connection c, int clientId, String amount) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".\"ClientReceipts\" "
                    + "(type, amount, \"time\", \"userName\", \"clientId\", \"branchId\") "
                    + "VALUES ('ReceiveVMoney', " + amount + "::numeric::money, NOW(), 'tester', " + clientId + ", " + BRANCH_ID + ") "
                    + "RETURNING \"crId\"");
            rs.next();
            return rs.getInt(1);
        }
    }

    private static int insertSupplierReceipt(Connection c, int supplierId, int branchId, String amountPaid) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".\"supplierReciepts\" "
                    + "(\"transId\", \"amountPaid\", \"remainingAmount\", \"receiptTime\", \"userRecived\", \"supplierId\", type, \"branchId\") "
                    + "VALUES (1, " + amountPaid + "::numeric::money, 0::numeric::money, NOW(), 'tester', " + supplierId + ", 'cash', " + branchId + ") "
                    + "RETURNING \"srId\"");
            rs.next();
            return rs.getInt(1);
        }
    }

    private static long insertArOpenItem(Connection c, int clientId, String total) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".ar_open_item "
                    + "(company_id, branch_id, client_id, source_type, currency_code, total_amount, settled_amount, remaining_amount, status, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", 'ADJUSTMENT', 'EGP', "
                    + total + ", 0, " + total + ", 'OPEN', '" + key() + "') RETURNING open_item_id");
            rs.next();
            return rs.getLong(1);
        }
    }

    private static void insertArOpenItemRaw(Connection c, int clientId, String total, String settled,
                                            String remaining, String status) throws SQLException {
        exec(c, "INSERT INTO " + SCHEMA + ".ar_open_item "
                + "(company_id, branch_id, client_id, source_type, currency_code, total_amount, settled_amount, remaining_amount, status, idempotency_key) "
                + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", 'ADJUSTMENT', 'EGP', "
                + total + ", " + settled + ", " + remaining + ", '" + status + "', '" + key() + "')");
    }

    private static long insertApOpenItem(Connection c, int supplierId, int branchId, String total) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".ap_open_item "
                    + "(company_id, branch_id, supplier_id, source_type, currency_code, total_amount, settled_amount, remaining_amount, status, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + branchId + ", " + supplierId + ", 'ADJUSTMENT', 'EGP', "
                    + total + ", 0, " + total + ", 'OPEN', '" + key() + "') RETURNING open_item_id");
            rs.next();
            return rs.getLong(1);
        }
    }

    private static long insertCreditNote(Connection c, int clientId, String total) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".ar_credit_note "
                    + "(company_id, branch_id, client_id, reason, currency_code, total_amount, applied_amount, unapplied_amount, status, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", 'IT return', 'EGP', "
                    + total + ", 0, " + total + ", 'OPEN', '" + key() + "') RETURNING credit_note_id");
            rs.next();
            return rs.getLong(1);
        }
    }

    private static long insertArAllocation(Connection c, int clientId, int receiptId, long openItemId,
                                           String amount, String currency) throws SQLException {
        try (Statement s = c.createStatement()) {
            ResultSet rs = s.executeQuery("INSERT INTO " + SCHEMA + ".ar_receipt_allocation "
                    + "(company_id, branch_id, client_id, receipt_id, open_item_id, amount, currency_code, idempotency_key) "
                    + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", " + receiptId + ", "
                    + openItemId + ", " + amount + ", '" + currency + "', '" + key() + "') RETURNING allocation_id");
            rs.next();
            return rs.getLong(1);
        }
    }

    private static void insertArReversal(Connection c, int clientId, int receiptId, long openItemId,
                                         String amount, long originalAllocationId) throws SQLException {
        exec(c, "INSERT INTO " + SCHEMA + ".ar_receipt_allocation "
                + "(company_id, branch_id, client_id, receipt_id, open_item_id, amount, currency_code, idempotency_key, reversal_of_allocation_id) "
                + "VALUES (" + COMPANY_ID + ", " + BRANCH_ID + ", " + clientId + ", " + receiptId + ", "
                + openItemId + ", " + amount + ", 'EGP', '" + key() + "', " + originalAllocationId + ")");
    }

    private static void settleAr(Connection c, long openItemId, String total, String settled,
                                 String remaining, String status) throws SQLException {
        exec(c, "UPDATE " + SCHEMA + ".ar_open_item SET settled_amount = " + settled
                + ", remaining_amount = " + remaining + ", status = '" + status
                + "', version = version + 1 WHERE open_item_id = " + openItemId);
    }

    private static boolean tableExists(Connection c, String table) throws SQLException {
        try (PreparedStatement p = c.prepareStatement(
                "SELECT 1 FROM information_schema.tables WHERE table_schema = ? AND table_name = ?")) {
            p.setString(1, SCHEMA);
            p.setString(2, table);
            try (ResultSet rs = p.executeQuery()) {
                return rs.next();
            }
        }
    }

    private static boolean columnExists(Connection c, String table, String column) throws SQLException {
        try (PreparedStatement p = c.prepareStatement(
                "SELECT 1 FROM information_schema.columns WHERE table_schema = ? AND table_name = ? AND column_name = ?")) {
            p.setString(1, SCHEMA);
            p.setString(2, table);
            p.setString(3, column);
            try (ResultSet rs = p.executeQuery()) {
                return rs.next();
            }
        }
    }

    private static List<String> columnSignatures(Connection c, String schema, String table,
                                                  List<String> includedColumns) throws SQLException {
        String sql = "SELECT column_name, data_type, udt_name, is_nullable, "
                + "COALESCE(numeric_precision::text, ''), COALESCE(numeric_scale::text, '') "
                + "FROM information_schema.columns WHERE table_schema = ? AND table_name = ? "
                + "ORDER BY ordinal_position";
        List<String> signatures = new ArrayList<>();
        try (PreparedStatement p = c.prepareStatement(sql)) {
            p.setString(1, schema);
            p.setString(2, table);
            try (ResultSet rs = p.executeQuery()) {
                while (rs.next()) {
                    String column = rs.getString(1);
                    if (includedColumns == null || includedColumns.contains(column)) {
                        signatures.add(column + "|" + rs.getString(2) + "|" + rs.getString(3) + "|"
                                + rs.getString(4) + "|" + rs.getString(5) + "|" + rs.getString(6));
                    }
                }
            }
        }
        return signatures;
    }

    private static boolean triggerExists(Connection c, String trigger) throws SQLException {
        try (PreparedStatement p = c.prepareStatement("SELECT 1 FROM pg_trigger WHERE tgname = ?")) {
            p.setString(1, trigger);
            try (ResultSet rs = p.executeQuery()) {
                return rs.next();
            }
        }
    }

    private static boolean capabilityExists(Connection c, String keyName) throws SQLException {
        try (PreparedStatement p = c.prepareStatement(
                "SELECT 1 FROM public.platform_capabilities WHERE capability_key = ?")) {
            p.setString(1, keyName);
            try (ResultSet rs = p.executeQuery()) {
                boolean found = rs.next();
                assertNotNull(rs);
                return found;
            }
        }
    }
}
