package com.example.valueinsoftbackend.client;

import com.example.valueinsoftbackend.AbstractIntegrationTest;
import com.example.valueinsoftbackend.Service.security.AuthorizationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

import java.util.Locale;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.doNothing;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class ClientIntegrationTest extends AbstractIntegrationTest {

    private static final int COMPANY_ID = 1;
    private static final int BRANCH_ID = 1;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean
    private AuthorizationService authorizationService;

    @BeforeEach
    void setup() {
        doNothing().when(authorizationService).assertAuthenticatedCapability(
                anyString(), anyInt(), nullable(Integer.class), anyString()
        );

        ensurePublicFixtures();
        ensureTenantClientTable();
    }

    @Test
    @WithMockUser(username = "testuser:Owner", roles = {"USER"})
    void shouldCreateClient() throws Exception {
        String jsonPayload = String.format(Locale.ROOT, """
                {
                  "clientId": 0,
                  "clientName": "Integration Test Client",
                  "clientPhone": "01000000000",
                  "gender": "unknown",
                  "desc": "123 Test St",
                  "branchId": %d
                }
                """, BRANCH_ID);

        mockMvc.perform(MockMvcRequestBuilders.post("/Client/{companyId}/AddClient", COMPANY_ID)
                .contentType(MediaType.APPLICATION_JSON)
                .content(jsonPayload))
                .andExpect(status().isAccepted());
    }

    private void ensurePublicFixtures() {
        jdbcTemplate.execute("""
                MERGE INTO public."Company" (
                    id, "companyName", "establishedTime", "ownerId", "planName", "planPrice", "currency", "comImg"
                )
                KEY(id)
                VALUES (1, 'Test Company', CURRENT_TIMESTAMP, 1, 'Test', 0, 'EGP', '')
                """);

        jdbcTemplate.execute("""
                MERGE INTO public."Branch" ("branchId", "branchName", "branchLocation", "companyId", "branchEstTime")
                KEY("branchId")
                VALUES (1, 'Test Branch', 'Test', 1, CURRENT_TIMESTAMP)
                """);
    }

    private void ensureTenantClientTable() {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS c_1");
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."Client" (
                    c_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 11) PRIMARY KEY,
                    "clientName" VARCHAR,
                    "clientPhone" VARCHAR,
                    gender VARCHAR,
                    description VARCHAR,
                    "branchId" INTEGER,
                    "registeredTime" TIMESTAMP
                )
                """);
    }
}
