CREATE TABLE IF NOT EXISTS public."Company" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "companyName" VARCHAR(100),
    "establishedTime" TIMESTAMP,
    "ownerId" INTEGER,
    "planName" VARCHAR(100),
    "planPrice" INTEGER,
    "currency" VARCHAR(20),
    "comImg" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS public."Branch" (
    "branchId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "branchName" VARCHAR(100),
    "branchLocation" VARCHAR(255),
    "companyId" INTEGER,
    "branchEstTime" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userName" VARCHAR(60),
    "userPassword" VARCHAR(100),
    "userEmail" VARCHAR(120),
    "userRole" VARCHAR(60),
    "userPhone" VARCHAR(30),
    "branchId" INTEGER,
    "firstName" VARCHAR(60),
    "lastName" VARCHAR(60),
    gender INTEGER,
    "creationTime" TIMESTAMP,
    "imgFile" VARCHAR(255),
    password_reset_required BOOLEAN NOT NULL DEFAULT FALSE
);
