package com.example.valueinsoftbackend.pos;

import com.example.valueinsoftbackend.AbstractIntegrationTest;
import com.example.valueinsoftbackend.Service.security.AuthorizationService;
import com.example.valueinsoftbackend.Service.security.TenantScopeGuard;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

import java.util.Locale;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class PosOrderIntegrationTest extends AbstractIntegrationTest {

    private static final int COMPANY_ID = 1;
    private static final int BRANCH_ID = 1;
    private static final int PRODUCT_ID = 1;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean
    private AuthorizationService authorizationService;

    @MockitoBean
    private TenantScopeGuard tenantScopeGuard;

    @BeforeEach
    void setup() {
        doNothing().when(authorizationService).assertAuthenticatedCapability(
                anyString(), anyInt(), nullable(Integer.class), anyString()
        );
        when(tenantScopeGuard.requireScope(anyString(), nullable(Integer.class), nullable(Integer.class)))
                .thenReturn(new TenantScopeGuard.ResolvedTenantScope(COMPANY_ID, BRANCH_ID));

        ensurePublicFixtures();
        ensureTenantSchema();
        ensureBranchPosTables();
        ensureProductStock();
    }

    @Test
    @WithMockUser(username = "testuser:Owner", roles = {"USER"})
    void shouldCreatePosOrder() throws Exception {
        String jsonPayload = String.format(Locale.ROOT, """
                {
                  "orderId": 0,
                  "orderTime": "2026-06-18T00:00:00Z",
                  "clientName": "",
                  "orderType": "Dirict",
                  "orderDiscount": 0,
                  "orderTotal": 10,
                  "salesUser": "testuser",
                  "branchId": %d,
                  "clientId": 0,
                  "orderIncome": 5,
                  "orderDetails": [
                    {
                      "itemId": %d,
                      "itemName": "Test Product",
                      "quantity": 1,
                      "price": 10,
                      "total": 10,
                      "productId": %d
                    }
                  ]
                }
                """, BRANCH_ID, PRODUCT_ID, PRODUCT_ID);

        mockMvc.perform(MockMvcRequestBuilders.post("/Order/1/saveOrder")
                .contentType(MediaType.APPLICATION_JSON)
                .content(jsonPayload))
                .andExpect(status().isCreated());
    }

    private void ensurePublicFixtures() {
        jdbcTemplate.execute("""
                MERGE INTO public."Company" (
                    id, "companyName", "establishedTime", "ownerId", "planName", "planPrice", "currency", "comImg"
                )
                KEY(id)
                VALUES (1, 'Test Company', CURRENT_TIMESTAMP, 1, 'Test', 0, 'EGP', '')
                """);

        jdbcTemplate.execute("""
                MERGE INTO public."Branch" ("branchId", "branchName", "branchLocation", "companyId", "branchEstTime")
                KEY("branchId")
                VALUES (1, 'Test Branch', 'Test', 1, CURRENT_TIMESTAMP)
                """);
    }

    private void ensureTenantSchema() {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS c_1");
    }

    private void ensureBranchPosTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."PosShiftPeriod" (
                    "PosSOID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ShiftStartTime" TIMESTAMP,
                    "ShiftEndTime" TIMESTAMP,
                    "branchId" INTEGER,
                    opened_by_user_id INTEGER,
                    assigned_cashier_id INTEGER,
                    closed_by_user_id INTEGER,
                    register_code VARCHAR(60),
                    status VARCHAR(20),
                    opening_float NUMERIC(12,2) DEFAULT 0,
                    expected_cash NUMERIC(12,2) DEFAULT 0,
                    counted_cash NUMERIC(12,2) DEFAULT 0,
                    variance_amount NUMERIC(12,2) DEFAULT 0,
                    variance_reason VARCHAR(255),
                    close_note VARCHAR(255),
                    order_count INTEGER DEFAULT 0,
                    gross_sales NUMERIC(12,2) DEFAULT 0,
                    net_sales NUMERIC(12,2) DEFAULT 0,
                    discount_total NUMERIC(12,2) DEFAULT 0,
                    refund_total NUMERIC(12,2) DEFAULT 0,
                    version BIGINT DEFAULT 0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.pos_receipt_sequences (
                    branch_id BIGINT NOT NULL,
                    period_yymm CHAR(4) NOT NULL,
                    last_sequence_no INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (branch_id, period_yymm),
                    CHECK (last_sequence_no BETWEEN 0 AND 999999)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."PosOrder_1" (
                    "orderId" SERIAL PRIMARY KEY,
                    "orderTime" TIMESTAMP NOT NULL,
                    "clientName" VARCHAR,
                    "orderType" VARCHAR(10),
                    "orderDiscount" INTEGER,
                    "orderTotal" INTEGER,
                    "salesUser" VARCHAR,
                    "clientId" INTEGER,
                    "orderIncome" INTEGER,
                    "orderBouncedBack" INTEGER,
                    "shift_id" INTEGER,
                    receipt_number VARCHAR(14),
                    idempotency_key VARCHAR(255)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."PosOrderDetail_1" (
                    "orderDetailsId" SERIAL PRIMARY KEY,
                    "itemId" INTEGER,
                    "itemName" VARCHAR,
                    quantity INTEGER,
                    price INTEGER,
                    total INTEGER,
                    "orderId" INTEGER REFERENCES c_1."PosOrder_1" ("orderId") ON DELETE CASCADE ON UPDATE CASCADE,
                    "productId" INTEGER,
                    "bouncedBack" INTEGER
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1."InventoryTransactions_1" (
                    "transId" SERIAL PRIMARY KEY,
                    "productId" INTEGER,
                    "userName" VARCHAR(15),
                    "supplierId" INTEGER,
                    "transactionType" VARCHAR(15),
                    "NumItems" INTEGER,
                    "transTotal" INTEGER,
                    "payType" VARCHAR,
                    "time" TIMESTAMP,
                    "RemainingAmount" INTEGER
                )
                """);
    }

    private void ensureProductStock() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.inventory_product (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id BIGINT NOT NULL DEFAULT 1,
                    product_name VARCHAR(30) NOT NULL,
                    retail_price INTEGER NOT NULL,
                    lowest_price INTEGER NOT NULL,
                    buying_price INTEGER NOT NULL,
                    company_name VARCHAR(30) NOT NULL,
                    product_type VARCHAR(15) NOT NULL,
                    product_state VARCHAR(10) NOT NULL,
                    supplier_id INTEGER NOT NULL DEFAULT 0,
                    major VARCHAR(30) NOT NULL,
                    tracking_type VARCHAR(20) NOT NULL DEFAULT 'QUANTITY',
                    sku VARCHAR(120),
                    barcode VARCHAR(120),
                    version BIGINT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.inventory_branch_stock_balance (
                    branch_id INTEGER NOT NULL,
                    product_id BIGINT NOT NULL,
                    quantity INTEGER NOT NULL DEFAULT 0,
                    reserved_qty INTEGER NOT NULL DEFAULT 0,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (branch_id, product_id)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS c_1.inventory_stock_ledger (
                    stock_ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    branch_id INTEGER NOT NULL,
                    product_id BIGINT NOT NULL,
                    quantity_delta INTEGER NOT NULL,
                    movement_type VARCHAR(40) NOT NULL,
                    reference_type VARCHAR(40),
                    reference_id VARCHAR(64),
                    actor_name VARCHAR(100),
                    note VARCHAR(255),
                    supplier_id INTEGER NOT NULL DEFAULT 0,
                    trans_total INTEGER NOT NULL DEFAULT 0,
                    pay_type VARCHAR(30),
                    remaining_amount INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        jdbcTemplate.update("""
                MERGE INTO c_1.inventory_product (
                    product_id, company_id, product_name, retail_price, lowest_price, buying_price,
                    company_name, product_type, product_state, supplier_id, major, tracking_type
                )
                KEY(product_id)
                VALUES (?, ?, 'Test Product', 10, 10, 5, 'Test Company', 'Unit', 'New', 0, 'General', 'QUANTITY')
                """, PRODUCT_ID, COMPANY_ID);

        jdbcTemplate.update("""
                MERGE INTO c_1.inventory_branch_stock_balance (branch_id, product_id, quantity, reserved_qty)
                KEY(branch_id, product_id)
                VALUES (?, ?, 10, 0)
                """, BRANCH_ID, PRODUCT_ID);
    }
}
