package com.example.valueinsoftbackend.pos;

import com.example.valueinsoftbackend.AbstractIntegrationTest;
import com.example.valueinsoftbackend.Model.Request.CreateOrderRequest;
import com.example.valueinsoftbackend.Model.Request.OrderItemRequest;
import com.example.valueinsoftbackend.Model.Response.CreateOrderResult;
import com.example.valueinsoftbackend.Service.OrderService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.Collections;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

public class PosReceiptNumberingIntegrationTest extends AbstractIntegrationTest {

    @Autowired
    private OrderService orderService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void testFirstReceiptGeneration() {
        // Setup schema
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS c_9999");
        jdbcTemplate.execute("CREATE TABLE c_9999.\"Client\" (c_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"clientName\" VARCHAR, \"clientPhone\" VARCHAR, gender VARCHAR, description VARCHAR, \"branchId\" INTEGER, \"registeredTime\" TIMESTAMP)");
        jdbcTemplate.execute("CREATE TABLE c_9999.pos_receipt_sequences (branch_id BIGINT NOT NULL, period_yymm CHAR(4) NOT NULL, last_sequence_no INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), PRIMARY KEY (branch_id, period_yymm), CHECK (last_sequence_no BETWEEN 0 AND 999999))");
        jdbcTemplate.execute("CREATE TABLE c_9999.\"PosOrder_1082\" (\"orderId\" SERIAL PRIMARY KEY, \"orderTime\" TIMESTAMP, \"clientName\" VARCHAR, \"orderType\" VARCHAR, \"orderDiscount\" INTEGER, \"orderTotal\" INTEGER, \"salesUser\" VARCHAR, \"clientId\" INTEGER, \"orderIncome\" INTEGER, \"orderBouncedBack\" INTEGER, \"shift_id\" INTEGER, receipt_number VARCHAR(14), idempotency_key VARCHAR(255))");
        jdbcTemplate.execute("CREATE TABLE c_9999.\"PosShiftPeriod\" (\"PosSOID\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"ShiftStartTime\" TIMESTAMP, \"ShiftEndTime\" TIMESTAMP, \"branchId\" INTEGER, opened_by_user_id INTEGER, assigned_cashier_id INTEGER, closed_by_user_id INTEGER, register_code VARCHAR(60), status VARCHAR(20), opening_float NUMERIC(12,2) DEFAULT 0, expected_cash NUMERIC(12,2) DEFAULT 0, counted_cash NUMERIC(12,2) DEFAULT 0, variance_amount NUMERIC(12,2) DEFAULT 0, variance_reason VARCHAR(255), close_note VARCHAR(255), order_count INTEGER DEFAULT 0, gross_sales NUMERIC(12,2) DEFAULT 0, net_sales NUMERIC(12,2) DEFAULT 0, discount_total NUMERIC(12,2) DEFAULT 0, refund_total NUMERIC(12,2) DEFAULT 0, version BIGINT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbcTemplate.execute("CREATE TABLE c_9999.\"PosOrderDetail_1082\" (\"orderDetailsId\" SERIAL PRIMARY KEY, \"itemId\" INTEGER, \"itemName\" VARCHAR, quantity INTEGER, price INTEGER, total INTEGER, \"orderId\" INTEGER REFERENCES c_9999.\"PosOrder_1082\" (\"orderId\") ON DELETE CASCADE ON UPDATE CASCADE, \"productId\" INTEGER, \"bouncedBack\" INTEGER)");

        OrderItemRequest item = new OrderItemRequest(1, "Product 1", 1, 100, 100, 0, Collections.emptyList(), Collections.emptyList(), null);
        CreateOrderRequest request = new CreateOrderRequest(0, null, "Test", "Direct", 0, 100, "user", 1082, 1, 100, List.of(item), null, null, null, null, null, null, null, null, UUID.randomUUID().toString());
        
        CreateOrderResult result = orderService.createOrder(request, 9999);
        assertNotNull(result);
        assertFalse(result.idempotencyHit());
        assertNotNull(result.receiptNumber());
        assertTrue(result.receiptNumber().contains("1082000001"));
    }
}
