-- =====================================================================
-- P1-8: Flyway baseline for the LEGACY public tables (pre-Flyway schema).
--
-- WHY THIS EXISTS
-- Migrations V1+ assume these legacy tables already exist; NO migration creates them —
-- historically they came from a manual bootstrap dump, so a fresh PostgreSQL could not be
-- built by Flyway alone. This migration creates the complete legacy `public` base so Flyway
-- is authoritative:
--   * FRESH databases (Testcontainers / CI / new environments) run V0 -> V1 -> ... in order
--     and end up with a complete schema — no missing tables.
--   * EXISTING databases are baselined ABOVE this version (see the P1-8 runbook in
--     docs/SAAS_P0_P1_REMEDIATION_PLAN.md), so V0 is never re-applied there.
--
-- SCOPE: exactly the legacy tables that Flyway never creates. By the project's naming
-- convention these are the quoted mixed-case tables (+ lowercase `users`). All modern
-- snake_case tables (ai_*, billing_*, finance_*, inventory_*, platform_*, tenant_*, pos_*
-- offline, etc.) are created by later migrations and are intentionally NOT included here.
--
-- SOURCE: schema-only dump of the live PostgreSQL 18 DB (VLSBackV2 2026-7-7.sql). Deliberate
-- deviations from the raw dump, for a clean replayable baseline:
--   * IDENTITY declared BY DEFAULT (not ALWAYS) so seed/app inserts may set explicit ids.
--   * CREATE TABLE IF NOT EXISTS everywhere (safe if a table already exists).
--   * Custom sequence START/INCREMENT values are dropped (default identity is fine on a
--     fresh DB); the id column is made PRIMARY KEY.
--   * public.users.password_reset_required is added later by V99 (kept out of V0).
--
-- NOTE (follow-up, not blocking): DbCompany reads a "tenantStatus" value for a company, but
-- public."Company" has no such column in the dump (likely derived from public.tenants.status
-- by the query, or added out-of-band). Reconcile during the P1-9 smoke test; kept identical
-- to the production dump here.
-- =====================================================================

-- =========================  Base identity tables  =========================

CREATE TABLE IF NOT EXISTS public."Company" (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "companyName"     CHARACTER VARYING(30),
    "establishedTime" TIMESTAMP WITH TIME ZONE,
    "ownerId"         INTEGER,
    "planName"        CHARACTER VARYING,
    "planPrice"       INTEGER,
    "comImg"          TEXT,
    currency          CHARACTER VARYING(5)
);

CREATE TABLE IF NOT EXISTS public."Branch" (
    "branchId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "branchName"     CHARACTER VARYING(25) NOT NULL,
    "branchLocation" CHARACTER VARYING(30),
    "companyId"      INTEGER NOT NULL,
    "branchEstTime"  TIMESTAMP(3) WITHOUT TIME ZONE,
    "branchMajor"    CHARACTER VARYING(30)
);

CREATE TABLE IF NOT EXISTS public.users (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userName"     CHARACTER VARYING(30) NOT NULL,
    "userPassword" CHARACTER VARYING(100) NOT NULL,
    "userEmail"    CHARACTER VARYING(60),
    "userRole"     CHARACTER VARYING(15),
    "userPhone"    CHARACTER VARYING,
    "branchId"     INTEGER,
    "firstName"    CHARACTER VARYING,
    "lastName"     CHARACTER VARYING,
    gender         SMALLINT,
    "creationTime" TIMESTAMP WITHOUT TIME ZONE,
    "imgFile"      TEXT
);

-- Transient: indexed by V2/V4, dropped by V119. Recreated so those migrations succeed.
CREATE TABLE IF NOT EXISTS public."CompanySubscription" (
    "sId"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "startTime"    TIMESTAMP WITHOUT TIME ZONE,
    "endTime"      TIMESTAMP WITHOUT TIME ZONE,
    "branchId"     INTEGER,
    "amountToPay"  INTEGER,
    "amountPaid"   INTEGER,
    order_id       CHARACTER VARYING(100),
    status         CHARACTER VARYING(40)
);

-- =========================  Legacy operational tables  =========================

CREATE TABLE IF NOT EXISTS public."Client" (
    c_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientName"     CHARACTER VARYING,
    "clientPhone"    CHARACTER VARYING,
    gender           CHARACTER VARYING,
    description      CHARACTER VARYING,
    "branchId"       INTEGER,
    "registeredTime" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS public."ClientReceipts" (
    "crId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        CHARACTER VARYING(20) NOT NULL,
    amount      MONEY NOT NULL,
    "time"      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "userName"  CHARACTER VARYING(25) NOT NULL,
    "clientId"  INTEGER NOT NULL,
    "branchId"  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public."CompanyAnalysis" (
    "cAID"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales             INTEGER DEFAULT 0,
    "Income"          INTEGER DEFAULT 0,
    "clientsIn"       INTEGER DEFAULT 0,
    "invShortage"     INTEGER DEFAULT 0,
    "discountByUsers" INTEGER DEFAULT 0,
    "damagedProducts" INTEGER DEFAULT 0,
    "returnPurchases" INTEGER DEFAULT 0,
    "shiftEndsEarly"  INTEGER DEFAULT 0,
    date              DATE,
    "branchId"        INTEGER
);

CREATE TABLE IF NOT EXISTS public."DamagedList" (
    "DId"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProductId"    INTEGER NOT NULL,
    "ProductName"  CHARACTER VARYING NOT NULL,
    "Time"         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "Reason"       CHARACTER VARYING(15),
    "Damaged by"   CHARACTER VARYING,
    "Cashier user" CHARACTER VARYING,
    "AmountTP"     INTEGER,
    "Paid"         BOOLEAN,
    "branchId"     INTEGER,
    quantity       INTEGER
);

CREATE TABLE IF NOT EXISTS public."InventoryTransactions" (
    "transId"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "productId"       INTEGER,
    "userId"          INTEGER,
    "supplierId"      INTEGER,
    "transactionType" CHARACTER VARYING(15),
    "NumItems"        INTEGER,
    "transTotal"      INTEGER,
    "payType"         CHARACTER VARYING,
    "time"            TIMESTAMP WITHOUT TIME ZONE,
    "RemainingAmount" INTEGER
);

CREATE TABLE IF NOT EXISTS public."MainMajor" (
    "MId"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CateName"   CHARACTER VARYING(20) NOT NULL,
    "AppType"    CHARACTER VARYING(10),
    "CateNameEG" CHARACTER VARYING(20)
);

CREATE TABLE IF NOT EXISTS public."PosCateJson" (
    "CategoryJID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryData" JSON,
    "BranchId"     INTEGER
);

CREATE TABLE IF NOT EXISTS public."PosOrder" (
    "orderId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orderTime"     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "clientName"    CHARACTER VARYING,
    "orderType"     CHARACTER VARYING(10),
    "orderDiscount" INTEGER,
    "orderTotal"    INTEGER,
    "salesUser"     CHARACTER VARYING
);

CREATE TABLE IF NOT EXISTS public."PosOrderDetail" (
    "orderDetailsId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "itemId"         INTEGER,
    "itemName"       CHARACTER VARYING,
    quantity         INTEGER,
    price            INTEGER,
    total            INTEGER,
    "orderId"        INTEGER
);

CREATE TABLE IF NOT EXISTS public."PosProduct" (
    "productId"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "productName"      CHARACTER VARYING(30),
    "buyingDay"        TIMESTAMP WITHOUT TIME ZONE,
    "activationPeriod" INTEGER,
    "rPrice"           INTEGER,
    "lPrice"           INTEGER,
    "bPrice"           INTEGER,
    "companyName"      CHARACTER VARYING(30),
    type               CHARACTER VARYING(15),
    "ownerName"        CHARACTER VARYING(20),
    serial             CHARACTER VARYING(35),
    "desc"             CHARACTER VARYING(60),
    "batteryLife"      INTEGER,
    "ownerPhone"       CHARACTER VARYING(14),
    "ownerNI"          CHARACTER VARYING(18),
    quantity           INTEGER,
    "pState"           CHARACTER VARYING(10),
    "branchId"         INTEGER
);

CREATE TABLE IF NOT EXISTS public."PosShiftPeriod" (
    "PosSOID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ShiftStartTime" TIMESTAMP WITHOUT TIME ZONE,
    "ShiftEndTime"   TIMESTAMP WITHOUT TIME ZONE,
    "branchId"       INTEGER
);

CREATE TABLE IF NOT EXISTS public."SupplierBProduct" (
    "sBPId"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "productId"  INTEGER NOT NULL,
    quantity     INTEGER NOT NULL,
    cost         INTEGER NOT NULL,
    "userName"   CHARACTER VARYING(25),
    "sPaid"      INTEGER,
    "time"       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "desc"       CHARACTER VARYING(40),
    "supplierId" INTEGER NOT NULL,
    "branchId"   INTEGER NOT NULL
);

-- NOTE: this legacy table name has a trailing space and must be quoted exactly: "supplier "
CREATE TABLE IF NOT EXISTS public."supplier " (
    "supplierId"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SupplierName"     CHARACTER VARYING NOT NULL,
    "supplierPhone1"   CHARACTER VARYING(14),
    "supplierPhone2"   CHARACTER VARYING(14),
    "SupplierLocation" CHARACTER VARYING
);
