-- ==========================================================
-- V101 - Inventory Dynamic Pricing Foundation
-- ==========================================================
-- Phase 1 only: tenant-schema tables, provisioning helper,
-- capabilities, and default grants for the smart dynamic
-- pricing engine. This migration does not calculate or apply
-- product prices.
-- ==========================================================

CREATE OR REPLACE FUNCTION public.create_inventory_pricing_engine_tables_for_tenant(schema_name text)
RETURNS void AS $$
BEGIN
    IF schema_name IS NULL OR schema_name NOT LIKE 'c\_%' ESCAPE '\' THEN
        RAISE EXCEPTION 'Inventory pricing engine tenant schema must start with c_: %', schema_name;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schemata.schema_name = $1
    ) THEN
        RAISE EXCEPTION 'Inventory pricing engine tenant schema does not exist: %', schema_name;
    END IF;

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_dynamic_pricing_policy (
            policy_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT,
            scope_type              VARCHAR(40)  NOT NULL,
            scope_value             VARCHAR(120),
            display_name            VARCHAR(150) NOT NULL,
            target_margin_pct       NUMERIC(9,4) NOT NULL,
            min_margin_pct          NUMERIC(9,4) NOT NULL,
            max_increase_pct        NUMERIC(9,4) NOT NULL,
            max_decrease_pct        NUMERIC(9,4) NOT NULL,
            max_increase_amount     NUMERIC(19,4),
            max_decrease_amount     NUMERIC(19,4),
            min_final_price         NUMERIC(19,4),
            max_final_price         NUMERIC(19,4),
            allow_below_cost        BOOLEAN      NOT NULL DEFAULT FALSE,
            approval_required       BOOLEAN      NOT NULL DEFAULT TRUE,
            maker_checker_required  BOOLEAN      NOT NULL DEFAULT TRUE,
            auto_apply_allowed      BOOLEAN      NOT NULL DEFAULT FALSE,
            max_auto_apply_pct      NUMERIC(9,4),
            max_products_per_batch  INTEGER      NOT NULL DEFAULT 500,
            rounding_mode           VARCHAR(40)  NOT NULL DEFAULT ''NEAREST_1'',
            low_stock_days_cover    NUMERIC(12,4) NOT NULL DEFAULT 7,
            overstock_days_cover    NUMERIC(12,4) NOT NULL DEFAULT 60,
            slow_moving_days        INTEGER      NOT NULL DEFAULT 45,
            dead_stock_days         INTEGER      NOT NULL DEFAULT 120,
            config_json             JSONB        NOT NULL DEFAULT ''{}''::jsonb,
            is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
            created_by              VARCHAR(150) NOT NULL,
            updated_by              VARCHAR(150),
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_inventory_dynamic_pricing_policy_scope CHECK (
                scope_type IN (''COMPANY'', ''BRANCH'', ''CATEGORY'', ''PRODUCT'', ''BUSINESS_LINE'', ''PRICING_POLICY'')
            ),
            CONSTRAINT chk_inventory_dynamic_pricing_policy_rounding CHECK (
                rounding_mode IN (''NEAREST_1'', ''NEAREST_5'', ''NEAREST_10'', ''CEILING_1'')
            ),
            CONSTRAINT chk_inventory_dynamic_pricing_policy_margins CHECK (
                target_margin_pct >= 0
                AND target_margin_pct < 1
                AND min_margin_pct >= 0
                AND min_margin_pct < 1
                AND target_margin_pct >= min_margin_pct
            ),
            CONSTRAINT chk_inventory_dynamic_pricing_policy_caps CHECK (
                max_increase_pct >= 0
                AND max_decrease_pct >= 0
                AND (max_auto_apply_pct IS NULL OR max_auto_apply_pct >= 0)
                AND max_products_per_batch > 0
                AND slow_moving_days > 0
                AND dead_stock_days >= slow_moving_days
                AND low_stock_days_cover >= 0
                AND overstock_days_cover >= low_stock_days_cover
            ),
            CONSTRAINT chk_inventory_dynamic_pricing_policy_amounts CHECK (
                (max_increase_amount IS NULL OR max_increase_amount >= 0)
                AND (max_decrease_amount IS NULL OR max_decrease_amount >= 0)
                AND (min_final_price IS NULL OR min_final_price >= 0)
                AND (max_final_price IS NULL OR max_final_price >= 0)
                AND (
                    min_final_price IS NULL
                    OR max_final_price IS NULL
                    OR max_final_price >= min_final_price
                )
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_product_price_history (
            history_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT,
            product_id              BIGINT       NOT NULL,
            old_retail_price        NUMERIC(19,4) NOT NULL,
            new_retail_price        NUMERIC(19,4) NOT NULL,
            old_lowest_price        NUMERIC(19,4) NOT NULL,
            new_lowest_price        NUMERIC(19,4) NOT NULL,
            buying_price_snapshot   NUMERIC(19,4) NOT NULL,
            change_source           VARCHAR(60)  NOT NULL,
            batch_id                BIGINT,
            recommendation_run_id   BIGINT,
            reason                  TEXT,
            actor_name              VARCHAR(150) NOT NULL,
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_inventory_product_price_history_source CHECK (
                change_source IN (
                    ''MANUAL_PRODUCT_EDIT'',
                    ''BULK_ADJUSTMENT'',
                    ''RECOMMENDATION_APPLY'',
                    ''AUTO_POLICY_APPLY''
                )
            ),
            CONSTRAINT chk_inventory_product_price_history_prices CHECK (
                old_retail_price >= 0
                AND new_retail_price >= 0
                AND old_lowest_price >= 0
                AND new_lowest_price >= 0
                AND buying_price_snapshot >= 0
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_product_pricing_metrics_daily (
            metric_date             DATE         NOT NULL,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT       NOT NULL,
            product_id              BIGINT       NOT NULL,
            sold_qty                NUMERIC(19,4) NOT NULL DEFAULT 0,
            gross_sales             NUMERIC(19,4) NOT NULL DEFAULT 0,
            net_sales               NUMERIC(19,4) NOT NULL DEFAULT 0,
            estimated_cogs          NUMERIC(19,4) NOT NULL DEFAULT 0,
            gross_profit            NUMERIC(19,4) NOT NULL DEFAULT 0,
            discount_amount         NUMERIC(19,4) NOT NULL DEFAULT 0,
            return_qty              NUMERIC(19,4) NOT NULL DEFAULT 0,
            stock_qty_snapshot      NUMERIC(19,4),
            retail_price_snapshot   NUMERIC(19,4),
            buying_price_snapshot   NUMERIC(19,4),
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY (metric_date, company_id, branch_id, product_id),
            CONSTRAINT chk_inventory_pricing_metrics_daily_nonnegative CHECK (
                gross_sales >= 0
                AND net_sales >= 0
                AND estimated_cogs >= 0
                AND discount_amount >= 0
                AND return_qty >= 0
                AND (stock_qty_snapshot IS NULL OR stock_qty_snapshot >= 0)
                AND (retail_price_snapshot IS NULL OR retail_price_snapshot >= 0)
                AND (buying_price_snapshot IS NULL OR buying_price_snapshot >= 0)
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_price_recommendation_run (
            run_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT       NOT NULL,
            status                  VARCHAR(40)  NOT NULL,
            scope_json              JSONB        NOT NULL,
            policy_snapshot_json    JSONB        NOT NULL,
            metrics_window_days     INTEGER      NOT NULL,
            total_products          INTEGER      NOT NULL DEFAULT 0,
            recommended_products    INTEGER      NOT NULL DEFAULT 0,
            warning_products        INTEGER      NOT NULL DEFAULT 0,
            skipped_products        INTEGER      NOT NULL DEFAULT 0,
            created_by              VARCHAR(150) NOT NULL,
            started_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            completed_at            TIMESTAMPTZ,
            failure_reason          TEXT,
            CONSTRAINT chk_inventory_price_recommendation_run_status CHECK (
                status IN (''RUNNING'', ''COMPLETED'', ''COMPLETED_WITH_WARNINGS'', ''FAILED'', ''CANCELLED'')
            ),
            CONSTRAINT chk_inventory_price_recommendation_run_counts CHECK (
                metrics_window_days > 0
                AND total_products >= 0
                AND recommended_products >= 0
                AND warning_products >= 0
                AND skipped_products >= 0
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_price_recommendation_item (
            item_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id                  BIGINT       NOT NULL,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT       NOT NULL,
            product_id              BIGINT       NOT NULL,
            product_name            VARCHAR(200) NOT NULL,
            category                VARCHAR(120),
            pricing_policy_code     VARCHAR(40),
            old_retail_price        NUMERIC(19,4) NOT NULL,
            old_lowest_price        NUMERIC(19,4) NOT NULL,
            buying_price            NUMERIC(19,4) NOT NULL,
            suggested_retail_price  NUMERIC(19,4),
            suggested_lowest_price  NUMERIC(19,4),
            delta_amount            NUMERIC(19,4),
            delta_pct               NUMERIC(9,4),
            current_margin_pct      NUMERIC(9,4),
            suggested_margin_pct    NUMERIC(9,4),
            stock_qty               NUMERIC(19,4),
            sales_velocity_7d       NUMERIC(19,4),
            sales_velocity_30d      NUMERIC(19,4),
            sales_velocity_90d      NUMERIC(19,4),
            days_cover              NUMERIC(19,4),
            movement_class          VARCHAR(40)  NOT NULL,
            demand_score            NUMERIC(9,4),
            cost_change_pct         NUMERIC(9,4),
            recommendation_status   VARCHAR(40)  NOT NULL,
            approval_required       BOOLEAN      NOT NULL DEFAULT TRUE,
            reason_codes            JSONB        NOT NULL DEFAULT ''[]''::jsonb,
            explanation_json        JSONB        NOT NULL DEFAULT ''{}''::jsonb,
            warning_codes           JSONB        NOT NULL DEFAULT ''[]''::jsonb,
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_inventory_price_recommendation_item_run
                FOREIGN KEY (run_id) REFERENCES %I.inventory_price_recommendation_run (run_id) ON DELETE CASCADE,
            CONSTRAINT chk_inventory_price_recommendation_item_movement CHECK (
                movement_class IN (''FAST'', ''STABLE'', ''SLOW'', ''DEAD'', ''NEW'', ''UNKNOWN'')
            ),
            CONSTRAINT chk_inventory_price_recommendation_item_status CHECK (
                recommendation_status IN (''RECOMMENDED'', ''NO_CHANGE'', ''SKIPPED'', ''WARNING'')
            ),
            CONSTRAINT chk_inventory_price_recommendation_item_prices CHECK (
                old_retail_price >= 0
                AND old_lowest_price >= 0
                AND buying_price >= 0
                AND (suggested_retail_price IS NULL OR suggested_retail_price >= 0)
                AND (suggested_lowest_price IS NULL OR suggested_lowest_price >= 0)
            )
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_price_adjustment_batch (
            batch_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT       NOT NULL,
            source_type             VARCHAR(40)  NOT NULL,
            source_run_id           BIGINT,
            status                  VARCHAR(40)  NOT NULL,
            adjustment_mode         VARCHAR(40),
            direction               VARCHAR(20),
            adjustment_value        NUMERIC(19,4),
            price_targets           JSONB        NOT NULL,
            scope_json              JSONB        NOT NULL,
            policy_snapshot_json    JSONB        NOT NULL,
            total_items             INTEGER      NOT NULL DEFAULT 0,
            valid_items             INTEGER      NOT NULL DEFAULT 0,
            warning_items           INTEGER      NOT NULL DEFAULT 0,
            blocked_items           INTEGER      NOT NULL DEFAULT 0,
            applied_items           INTEGER      NOT NULL DEFAULT 0,
            failed_items            INTEGER      NOT NULL DEFAULT 0,
            reason                  TEXT         NOT NULL,
            created_by              VARCHAR(150) NOT NULL,
            submitted_by            VARCHAR(150),
            approved_by             VARCHAR(150),
            rejected_by             VARCHAR(150),
            applied_by              VARCHAR(150),
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            submitted_at            TIMESTAMPTZ,
            approved_at             TIMESTAMPTZ,
            rejected_at             TIMESTAMPTZ,
            applied_at              TIMESTAMPTZ,
            updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_inventory_price_adjustment_batch_source CHECK (
                source_type IN (''BULK_MANUAL'', ''RECOMMENDATION'', ''AUTO_POLICY'')
            ),
            CONSTRAINT chk_inventory_price_adjustment_batch_status CHECK (
                status IN (
                    ''DRAFT'',
                    ''PREVIEWED'',
                    ''PENDING_APPROVAL'',
                    ''APPROVED'',
                    ''REJECTED'',
                    ''APPLYING'',
                    ''APPLIED'',
                    ''PARTIALLY_APPLIED'',
                    ''FAILED'',
                    ''CANCELLED''
                )
            ),
            CONSTRAINT chk_inventory_price_adjustment_batch_mode CHECK (
                adjustment_mode IS NULL OR adjustment_mode IN (''PERCENTAGE'', ''FIXED_AMOUNT'', ''RECOMMENDED_PRICE'')
            ),
            CONSTRAINT chk_inventory_price_adjustment_batch_direction CHECK (
                direction IS NULL OR direction IN (''INCREASE'', ''DECREASE'')
            ),
            CONSTRAINT chk_inventory_price_adjustment_batch_counts CHECK (
                total_items >= 0
                AND valid_items >= 0
                AND warning_items >= 0
                AND blocked_items >= 0
                AND applied_items >= 0
                AND failed_items >= 0
            ),
            CONSTRAINT chk_inventory_price_adjustment_batch_value CHECK (
                adjustment_value IS NULL OR adjustment_value >= 0
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_price_adjustment_item (
            item_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id                BIGINT       NOT NULL,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT       NOT NULL,
            product_id              BIGINT       NOT NULL,
            recommendation_item_id  BIGINT,
            product_name            VARCHAR(200) NOT NULL,
            old_retail_price        NUMERIC(19,4) NOT NULL,
            new_retail_price        NUMERIC(19,4) NOT NULL,
            old_lowest_price        NUMERIC(19,4) NOT NULL,
            new_lowest_price        NUMERIC(19,4) NOT NULL,
            buying_price_snapshot   NUMERIC(19,4) NOT NULL,
            delta_amount            NUMERIC(19,4) NOT NULL,
            delta_pct               NUMERIC(9,4) NOT NULL,
            expected_margin_pct     NUMERIC(9,4),
            status                  VARCHAR(40)  NOT NULL,
            reason_codes            JSONB        NOT NULL DEFAULT ''[]''::jsonb,
            warning_codes           JSONB        NOT NULL DEFAULT ''[]''::jsonb,
            blocked_codes           JSONB        NOT NULL DEFAULT ''[]''::jsonb,
            apply_error             TEXT,
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            applied_at              TIMESTAMPTZ,
            CONSTRAINT fk_inventory_price_adjustment_item_batch
                FOREIGN KEY (batch_id) REFERENCES %I.inventory_price_adjustment_batch (batch_id) ON DELETE CASCADE,
            CONSTRAINT chk_inventory_price_adjustment_item_status CHECK (
                status IN (''VALID'', ''WARNING'', ''BLOCKED'', ''APPLIED'', ''FAILED'', ''SKIPPED'')
            ),
            CONSTRAINT chk_inventory_price_adjustment_item_prices CHECK (
                old_retail_price >= 0
                AND new_retail_price >= 0
                AND old_lowest_price >= 0
                AND new_lowest_price >= 0
                AND buying_price_snapshot >= 0
            )
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_pricing_audit_log (
            audit_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id              BIGINT       NOT NULL,
            branch_id               BIGINT,
            event_type              VARCHAR(80)  NOT NULL,
            entity_type             VARCHAR(60)  NOT NULL,
            entity_id               VARCHAR(80),
            actor_name              VARCHAR(150),
            event_message           TEXT         NOT NULL,
            payload_json            JSONB        NOT NULL DEFAULT ''{}''::jsonb,
            created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_inventory_pricing_audit_entity_type CHECK (
                entity_type IN (''POLICY'', ''RUN'', ''BATCH'', ''ITEM'', ''PRODUCT_PRICE'')
            )
        )', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_dynamic_pricing_policy (company_id, branch_id, is_active)',
        'idx_inventory_dynamic_pricing_policy_scope', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_dynamic_pricing_policy (company_id, scope_type, scope_value, is_active)',
        'idx_inventory_dynamic_pricing_policy_precedence', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_product_price_history (company_id, product_id, created_at DESC)',
        'idx_inventory_product_price_history_product', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_product_price_history (company_id, branch_id, created_at DESC)',
        'idx_inventory_product_price_history_branch', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_product_price_history (company_id, batch_id)',
        'idx_inventory_product_price_history_batch', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_product_pricing_metrics_daily (company_id, branch_id, product_id, metric_date DESC)',
        'idx_inventory_pricing_metrics_product_date', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_product_pricing_metrics_daily (company_id, branch_id, metric_date DESC)',
        'idx_inventory_pricing_metrics_branch_date', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_run (company_id, branch_id, started_at DESC)',
        'idx_inventory_price_recommendation_run_started', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_run (company_id, branch_id, status)',
        'idx_inventory_price_recommendation_run_status', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_item (company_id, branch_id, run_id)',
        'idx_inventory_price_recommendation_item_run', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_item (company_id, branch_id, product_id)',
        'idx_inventory_price_recommendation_item_product', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_item (run_id, recommendation_status)',
        'idx_inventory_price_recommendation_item_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_recommendation_item (run_id, movement_class)',
        'idx_inventory_price_recommendation_item_movement', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_batch (company_id, branch_id, created_at DESC)',
        'idx_inventory_price_adjustment_batch_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_batch (company_id, branch_id, status)',
        'idx_inventory_price_adjustment_batch_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_batch (company_id, branch_id, source_run_id)',
        'idx_inventory_price_adjustment_batch_source_run', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_item (company_id, branch_id, batch_id, status)',
        'idx_inventory_price_adjustment_item_batch_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_item (company_id, branch_id, product_id)',
        'idx_inventory_price_adjustment_item_product', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_price_adjustment_item (batch_id, product_id)',
        'idx_inventory_price_adjustment_item_batch_product', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_pricing_audit_log (company_id, branch_id, created_at DESC)',
        'idx_inventory_pricing_audit_scope_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_pricing_audit_log (company_id, event_type, created_at DESC)',
        'idx_inventory_pricing_audit_event_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_pricing_audit_log (company_id, entity_type, entity_id)',
        'idx_inventory_pricing_audit_entity', schema_name);
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    schema_rec RECORD;
BEGIN
    FOR schema_rec IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name LIKE 'c\_%' ESCAPE '\'
        ORDER BY schema_name
    LOOP
        PERFORM public.create_inventory_pricing_engine_tables_for_tenant(schema_rec.schema_name);
    END LOOP;
END $$;

INSERT INTO public.platform_capabilities (
    capability_key,
    module_id,
    resource,
    action,
    scope_type,
    status,
    description
) VALUES
    ('inventory.pricing.view', 'inventory', 'pricing', 'view', 'branch', 'active', 'View smart pricing recommendations, batches, and policy summaries.'),
    ('inventory.pricing.cost.read', 'inventory', 'pricing_cost', 'read', 'branch', 'active', 'View buying cost and gross margin details in smart pricing.'),
    ('inventory.pricing.recommendation.run', 'inventory', 'pricing_recommendation', 'run', 'branch', 'active', 'Create deterministic smart pricing recommendation runs.'),
    ('inventory.pricing.adjustment.preview', 'inventory', 'pricing_adjustment', 'preview', 'branch', 'active', 'Preview bulk price adjustments before approval or application.'),
    ('inventory.pricing.adjustment.create', 'inventory', 'pricing_adjustment', 'create', 'branch', 'active', 'Create controlled price adjustment batches.'),
    ('inventory.pricing.adjustment.submit', 'inventory', 'pricing_adjustment', 'submit', 'branch', 'active', 'Submit price adjustment batches for approval.'),
    ('inventory.pricing.adjustment.approve', 'inventory', 'pricing_adjustment', 'approve', 'branch', 'active', 'Approve or reject controlled price adjustment batches.'),
    ('inventory.pricing.adjustment.apply', 'inventory', 'pricing_adjustment', 'apply', 'branch', 'active', 'Apply approved price adjustment batches to inventory products.'),
    ('inventory.pricing.adjustment.auto_apply', 'inventory', 'pricing_adjustment', 'auto_apply', 'branch', 'active', 'Permit restricted policy-based automatic price adjustment application.'),
    ('inventory.pricing.policy.manage', 'inventory', 'pricing_policy', 'manage', 'company', 'active', 'Manage smart pricing guardrail policies.'),
    ('inventory.pricing.audit.read', 'inventory', 'pricing_audit', 'read', 'branch', 'active', 'Read smart pricing audit and price-change history.')
ON CONFLICT (capability_key) DO UPDATE
SET
    module_id = EXCLUDED.module_id,
    resource = EXCLUDED.resource,
    action = EXCLUDED.action,
    scope_type = EXCLUDED.scope_type,
    status = EXCLUDED.status,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO public.role_grants (
    role_id,
    capability_key,
    scope_type,
    grant_mode,
    grant_version
) VALUES
    ('Owner', 'inventory.pricing.view', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.cost.read', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.recommendation.run', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.preview', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.create', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.submit', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.approve', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.apply', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.adjustment.auto_apply', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.policy.manage', 'company', 'allow', 'v1'),
    ('Owner', 'inventory.pricing.audit.read', 'company', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.view', 'branch', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.recommendation.run', 'branch', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.adjustment.preview', 'branch', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.adjustment.create', 'branch', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.adjustment.submit', 'branch', 'allow', 'v1'),
    ('BranchManager', 'inventory.pricing.audit.read', 'branch', 'allow', 'v1'),
    ('InventoryClerk', 'inventory.pricing.view', 'branch', 'allow', 'v1'),
    ('InventoryClerk', 'inventory.pricing.recommendation.run', 'branch', 'allow', 'v1'),
    ('InventoryClerk', 'inventory.pricing.adjustment.preview', 'branch', 'allow', 'v1'),
    ('InventoryClerk', 'inventory.pricing.adjustment.create', 'branch', 'allow', 'v1'),
    ('InventoryClerk', 'inventory.pricing.adjustment.submit', 'branch', 'allow', 'v1'),
    ('Accountant', 'inventory.pricing.view', 'company', 'allow', 'v1'),
    ('Accountant', 'inventory.pricing.cost.read', 'company', 'allow', 'v1'),
    ('Accountant', 'inventory.pricing.audit.read', 'company', 'allow', 'v1')
ON CONFLICT (role_id, capability_key, scope_type) DO UPDATE
SET
    grant_mode = EXCLUDED.grant_mode,
    grant_version = EXCLUDED.grant_version;

