-- ==========================================================
-- V162 - Product Import: RECEIVE action for serialized rows
-- ==========================================================
-- Bulk product import now routes serialized (IMEI / SERIAL)
-- rows through the product receipt pipeline. Rows whose barcode
-- matches an existing product are received into that product
-- (action = RECEIVE) instead of being skipped or re-inserted.
-- This migration extends the allowed row actions and refreshes
-- the tenant-table creator function so new tenants get the
-- updated constraint.
-- ==========================================================

-- 1) Relax the action constraint on existing tenant tables.
DO $$
DECLARE
    schema_rec RECORD;
BEGIN
    FOR schema_rec IN
        SELECT table_schema
        FROM information_schema.tables
        WHERE table_name = 'inventory_import_row'
          AND table_schema LIKE 'c\_%' ESCAPE '\'
        ORDER BY table_schema
    LOOP
        EXECUTE format('ALTER TABLE %I.inventory_import_row DROP CONSTRAINT IF EXISTS chk_inventory_import_row_action',
            schema_rec.table_schema);
        EXECUTE format('ALTER TABLE %I.inventory_import_row ADD CONSTRAINT chk_inventory_import_row_action CHECK (
                action IS NULL OR action IN (''INSERT'', ''UPDATE'', ''SKIP'', ''RECEIVE'')
            )', schema_rec.table_schema);
    END LOOP;
END $$;

-- 2) Refresh the creator function so future tenant schemas are
--    created with the extended constraint. Body is identical to
--    V89 except for the RECEIVE action.
CREATE OR REPLACE FUNCTION public.create_inventory_product_import_tables_for_tenant(schema_name text)
RETURNS void AS $$
BEGIN
    IF schema_name IS NULL OR schema_name NOT LIKE 'c\_%' ESCAPE '\' THEN
        RAISE EXCEPTION 'Inventory product import tenant schema must start with c_: %', schema_name;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schemata.schema_name = $1
    ) THEN
        RAISE EXCEPTION 'Inventory product import tenant schema does not exist: %', schema_name;
    END IF;

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_import_batch (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id          BIGINT       NOT NULL,
            branch_id           BIGINT       NOT NULL,
            import_type         VARCHAR(40)  NOT NULL DEFAULT ''PRODUCT'',
            mode                VARCHAR(30)  NOT NULL,
            status              VARCHAR(40)  NOT NULL,
            original_file_name  VARCHAR(255),
            file_sha256         VARCHAR(128),
            total_rows          INTEGER      NOT NULL DEFAULT 0,
            valid_rows          INTEGER      NOT NULL DEFAULT 0,
            warning_rows        INTEGER      NOT NULL DEFAULT 0,
            invalid_rows        INTEGER      NOT NULL DEFAULT 0,
            duplicate_rows      INTEGER      NOT NULL DEFAULT 0,
            inserted_rows       INTEGER      NOT NULL DEFAULT 0,
            updated_rows        INTEGER      NOT NULL DEFAULT 0,
            skipped_rows        INTEGER      NOT NULL DEFAULT 0,
            failed_rows         INTEGER      NOT NULL DEFAULT 0,
            settings_json       JSONB        NOT NULL DEFAULT ''{}''::jsonb,
            created_by          VARCHAR(150) NOT NULL,
            confirmed_by        VARCHAR(150),
            created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            validated_at        TIMESTAMPTZ,
            confirmed_at        TIMESTAMPTZ,
            completed_at        TIMESTAMPTZ,
            updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT chk_inventory_import_batch_type CHECK (import_type IN (''PRODUCT'')),
            CONSTRAINT chk_inventory_import_batch_mode CHECK (mode IN (''ADD_ONLY'', ''UPDATE_ONLY'', ''UPSERT'')),
            CONSTRAINT chk_inventory_import_batch_status CHECK (status IN (
                ''UPLOADED'',
                ''VALIDATING'',
                ''VALIDATED'',
                ''VALIDATED_WITH_ERRORS'',
                ''IMPORTING'',
                ''IMPORTED'',
                ''IMPORTED_WITH_ERRORS'',
                ''FAILED'',
                ''CANCELLED''
            )),
            CONSTRAINT chk_inventory_import_batch_counts CHECK (
                total_rows >= 0
                AND valid_rows >= 0
                AND warning_rows >= 0
                AND invalid_rows >= 0
                AND duplicate_rows >= 0
                AND inserted_rows >= 0
                AND updated_rows >= 0
                AND skipped_rows >= 0
                AND failed_rows >= 0
            )
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_import_row (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id            BIGINT       NOT NULL,
            company_id          BIGINT       NOT NULL,
            branch_id           BIGINT       NOT NULL,
            row_number          INTEGER      NOT NULL,
            row_hash            VARCHAR(128) NOT NULL,
            raw_data            JSONB        NOT NULL,
            normalized_data     JSONB        NOT NULL DEFAULT ''{}''::jsonb,
            status              VARCHAR(40)  NOT NULL,
            existing_product_id BIGINT,
            created_product_id  BIGINT,
            action              VARCHAR(30),
            sku                 VARCHAR(100),
            barcode             VARCHAR(100),
            product_name        VARCHAR(200),
            category            VARCHAR(100),
            supplier_name       VARCHAR(200),
            created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_inventory_import_row_batch
                FOREIGN KEY (batch_id) REFERENCES %I.inventory_import_batch (id) ON DELETE CASCADE,
            CONSTRAINT chk_inventory_import_row_number CHECK (row_number > 0),
            CONSTRAINT chk_inventory_import_row_status CHECK (status IN (
                ''VALID'',
                ''WARNING'',
                ''INVALID'',
                ''DUPLICATE'',
                ''IMPORTED'',
                ''UPDATED'',
                ''SKIPPED'',
                ''IMPORT_FAILED''
            )),
            CONSTRAINT chk_inventory_import_row_action CHECK (
                action IS NULL OR action IN (''INSERT'', ''UPDATE'', ''SKIP'', ''RECEIVE'')
            )
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.inventory_import_error (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id      BIGINT       NOT NULL,
            row_id        BIGINT,
            company_id    BIGINT       NOT NULL,
            branch_id     BIGINT       NOT NULL,
            row_number    INTEGER,
            field_name    VARCHAR(100),
            error_code    VARCHAR(100) NOT NULL,
            error_message TEXT         NOT NULL,
            severity      VARCHAR(30)  NOT NULL,
            raw_value     TEXT,
            created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_inventory_import_error_batch
                FOREIGN KEY (batch_id) REFERENCES %I.inventory_import_batch (id) ON DELETE CASCADE,
            CONSTRAINT fk_inventory_import_error_row
                FOREIGN KEY (row_id) REFERENCES %I.inventory_import_row (id) ON DELETE CASCADE,
            CONSTRAINT chk_inventory_import_error_severity CHECK (severity IN (
                ''ERROR'',
                ''WARNING'',
                ''INFO''
            ))
        )', schema_name, schema_name, schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_batch (company_id, branch_id, created_at DESC)',
        'idx_' || schema_name || '_inventory_import_batch_scope_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_batch (company_id, branch_id, status)',
        'idx_' || schema_name || '_inventory_import_batch_scope_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_batch (file_sha256)',
        'idx_' || schema_name || '_inventory_import_batch_file_hash', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_row (company_id, branch_id, batch_id, status)',
        'idx_' || schema_name || '_inventory_import_row_scope_batch_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_row (batch_id, row_number)',
        'idx_' || schema_name || '_inventory_import_row_batch_row_number', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_row (company_id, branch_id, sku)',
        'idx_' || schema_name || '_inventory_import_row_scope_sku', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_row (company_id, branch_id, barcode)',
        'idx_' || schema_name || '_inventory_import_row_scope_barcode', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_row (batch_id, row_hash)',
        'idx_' || schema_name || '_inventory_import_row_batch_hash', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_error (company_id, branch_id, batch_id)',
        'idx_' || schema_name || '_inventory_import_error_scope_batch', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_error (batch_id, severity)',
        'idx_' || schema_name || '_inventory_import_error_batch_severity', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.inventory_import_error (row_id)',
        'idx_' || schema_name || '_inventory_import_error_row', schema_name);
END;
$$ LANGUAGE plpgsql;
