-- ==========================================================
-- V164 - ValueInSoft application RAG knowledge pack
-- ==========================================================
-- Seeds verified, application-owned help knowledge into both:
--   1. ai_document / ai_document_chunk (grounded keyword RAG)
--   2. ai_knowledge_document / ai_knowledge_chunk (semantic corpus)
--
-- Chunks intentionally have no synthetic embedding. They are immediately
-- available to keyword RAG and can later be reingested with a configured
-- real embedding provider.
-- ==========================================================

CREATE TEMP TABLE vls_ai_application_seed_chunk (
    document_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    module VARCHAR(100) NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (document_id, chunk_index)
);

INSERT INTO vls_ai_application_seed_chunk
    (document_id, title, module, chunk_index, heading, content)
VALUES
    ('40000000-0000-0000-0000-000000000001', 'Application navigation and branch context', 'dashboard', 0,
     'Finding screens',
     $$The ValueInSoft main application is organized into Dashboard, Point of sale, Inventory, Clients, Finance, Reports, HR and Payroll, Attendance, and Settings. Sidebar items appear only when the signed-in user has the required capability. A missing menu item usually means the user lacks permission, the company or branch context is incomplete, or the subscribed package does not enable that module.$$),
    ('40000000-0000-0000-0000-000000000001', 'Application navigation and branch context', 'dashboard', 1,
     'Company and branch scope',
     $$Company-level pages combine information across permitted branches. Branch-level pages use the currently selected branch, so confirm the branch name before entering sales, inventory, attendance, or finance data. Changing branch context can change available records, balances, settings, and actions.$$),
    ('40000000-0000-0000-0000-000000000001', 'Application navigation and branch context', 'dashboard', 2,
     'Safe navigation troubleshooting',
     $$If a page is empty or unavailable, confirm that the user is signed in, a company exists, the intended branch is selected, and the account has the required capability. Refresh once after correcting context. Do not bypass access controls; ask an owner or authorized administrator to review assignments when access is still missing.$$),

    ('40000000-0000-0000-0000-000000000002', 'Dashboard and company dashboard', 'dashboard', 0,
     'Dashboard pages',
     $$DashboardUser and AdminDashboardPage show branch-oriented operational summaries. CompanyDashboardPage is a company-wide view for permitted owners and administrators. Dashboard cards can summarize sales, orders, clients, alerts, inventory health, finance, and recent activity, subject to the selected date and available data.$$),
    ('40000000-0000-0000-0000-000000000002', 'Dashboard and company dashboard', 'dashboard', 1,
     'Using dashboard filters',
     $$Check the page scope and date before interpreting dashboard values. Company dashboard figures may aggregate all permitted branches, while a branch dashboard represents the selected branch. Use available date or period controls, refresh after transactions are posted, and open the related module when detailed evidence is required.$$),
    ('40000000-0000-0000-0000-000000000002', 'Dashboard and company dashboard', 'dashboard', 2,
     'Reading dashboard results safely',
     $$Dashboard values are summaries rather than accounting evidence. Investigate unexpected numbers through Sales, Inventory history, Finance journals, or the appropriate report. Empty cards can mean there are no records for the period, a branch failed to load, or the user cannot read the underlying module.$$),

    ('40000000-0000-0000-0000-000000000003', 'Point of sale checkout', 'pos', 0,
     'Starting a POS sale',
     $$Open Point of sale or POS categories, confirm the active branch and open shift when shift tracking is required, then find products by category, name, barcode, serial number, or IMEI. Add the intended items to the cart and verify quantity, unit price, discounts, tax behavior, and customer before payment.$$),
    ('40000000-0000-0000-0000-000000000003', 'Point of sale checkout', 'pos', 1,
     'Cart and product validation',
     $$Serialized products require selection or scanning of the exact available serial or IMEI unit. Stock, reservation, pricing, and permission rules can block checkout. Resolve validation messages before completing the order and never substitute a different identifier just to pass validation.$$),
    ('40000000-0000-0000-0000-000000000003', 'Point of sale checkout', 'pos', 2,
     'Completing the order',
     $$Select the correct payment method and enter any required amounts or references. Review change, credit terms, and customer assignment before confirming. Treat the saved order or invoice confirmation as the completion signal; avoid submitting the same sale repeatedly after a slow response.$$),

    ('40000000-0000-0000-0000-000000000004', 'POS payments receipts returns and held orders', 'pos', 0,
     'Payments and customer credit',
     $$POS may support cash, card, wallet, mixed payment, or credit depending on configuration and permissions. Credit sales require an eligible customer and can be restricted by the configured credit-control mode or customer limit. Verify the payment allocation and customer before finalizing.$$),
    ('40000000-0000-0000-0000-000000000004', 'POS payments receipts returns and held orders', 'pos', 1,
     'Receipts and printers',
     $$After a sale is saved, open the receipt or order details and choose the configured print or sharing action. If printing fails, verify browser print permission, printer connection, paper size, receipt format, and the branch default printer. Reprinting must not create a second sale.$$),
    ('40000000-0000-0000-0000-000000000004', 'POS payments receipts returns and held orders', 'pos', 2,
     'Held orders and returns',
     $$Use the hold or suspend workflow only when it is available and preserve the correct customer and cart context. Resume the saved order before payment instead of rebuilding it. For returns or refunds, open the original transaction, verify eligible quantities and payment consequences, and follow the authorized return action so stock and finance remain linked.$$),

    ('40000000-0000-0000-0000-000000000005', 'POS shifts and offline synchronization', 'shift', 0,
     'Opening and closing a POS shift',
     $$Open a shift before selling when the branch requires shift tracking. Record the opening cash and permitted cash movements accurately. At close, review expected cash, enter counted cash, explain any required variance, and submit only after active work and pending orders are resolved.$$),
    ('40000000-0000-0000-0000-000000000005', 'POS shifts and offline synchronization', 'shift', 1,
     'Offline POS behavior',
     $$Offline POS can queue supported operations when connectivity is interrupted. Keep the same device and branch context, avoid duplicating a transaction in another tab, and allow queued batches to synchronize when the connection returns. A locally queued state is not the same as a server-posted completion.$$),
    ('40000000-0000-0000-0000-000000000005', 'POS shifts and offline synchronization', 'shift', 2,
     'Offline sync administration',
     $$OfflineSyncAdmin shows synchronization batches and processing results for authorized administrators. Review failed or quarantined items, their validation details, and idempotency references before retrying. Do not repeatedly resubmit a batch without understanding whether it was already posted.$$),

    ('40000000-0000-0000-0000-000000000006', 'Inventory catalog and product management', 'inventory', 0,
     'Browsing inventory',
     $$InventoryCatalogPage and viewInventory provide branch product search, stock visibility, filters, and permitted inventory actions. Search can use product name, barcode, serial, IMEI, category, or other supported attributes. Quantities reflect the selected branch and can distinguish available, reserved, and serialized units.$$),
    ('40000000-0000-0000-0000-000000000006', 'Inventory catalog and product management', 'inventory', 1,
     'Adding or editing a product',
     $$Open Add item, choose the appropriate product template or type, and enter the required name, category, unit of measure, tracking type, barcode, pricing, cost, quantity, supplier, and attributes. Serialized or IMEI tracking requires exact unit identifiers. Review validation and save, then confirm the product appears in inventory and POS when sellable.$$),
    ('40000000-0000-0000-0000-000000000006', 'Inventory catalog and product management', 'inventory', 2,
     'Product changes and permissions',
     $$Product editing and cost visibility depend on capabilities. Avoid changing tracking type, base unit, or identity fields after transactions exist unless the application explicitly permits it. Use inventory history to verify the effect of quantity-changing operations rather than editing balances indirectly.$$),

    ('40000000-0000-0000-0000-000000000007', 'Inventory categories templates and units', 'inventory', 0,
     'Categories',
     $$Edit categories organizes products for inventory browsing and POS category selection. Create clear category names, keep the hierarchy understandable, and check whether products reference a category before changing or removing it. Category access requires the relevant inventory capability.$$),
    ('40000000-0000-0000-0000-000000000007', 'Inventory categories templates and units', 'inventory', 1,
     'Product templates and attributes',
     $$Inventory templates define reusable product fields and validation behavior for different business categories. Choose the template that matches the product type, then complete its required dynamic attributes. Platform-managed templates can be inspected or configured only by authorized administrators.$$),
    ('40000000-0000-0000-0000-000000000007', 'Inventory categories templates and units', 'inventory', 2,
     'Units of measure and tracking types',
     $$Use the base unit of measure that matches how stock is controlled. Quantity-tracked items use aggregate quantities, serial-tracked items use one unique serial per unit, and IMEI-tracked items use exact IMEI identifiers. Incorrect tracking configuration causes receiving, adjustment, sale, and return validation problems.$$),

    ('40000000-0000-0000-0000-000000000008', 'Serialized inventory and IMEI workflows', 'inventory', 0,
     'Receiving serialized units',
     $$For SERIAL or IMEI products, receive each physical unit with a unique identifier. The number of identifiers must match the received quantity, and duplicate identifiers are rejected. Record acquisition cost when required so serialized inventory and margin reporting remain accurate.$$),
    ('40000000-0000-0000-0000-000000000008', 'Serialized inventory and IMEI workflows', 'inventory', 1,
     'Selling and locating serialized units',
     $$At POS, scan or select the exact available serial or IMEI unit. Inventory browse and history can show identifiers and their state. A unit that is sold, reserved, damaged, returned, or otherwise unavailable cannot be selected as normal stock.$$),
    ('40000000-0000-0000-0000-000000000008', 'Serialized inventory and IMEI workflows', 'inventory', 2,
     'Serialized corrections and returns',
     $$Serialized adjustments, damage, and supplier return workflows must target exact units when supported; aggregate quantity changes are unsafe for serialized products. Use inventory history to trace the identifier. If the requested exact-unit workflow is unavailable, stop and use an authorized correction process rather than changing aggregate stock.$$),

    ('40000000-0000-0000-0000-000000000009', 'Inventory adjustments damages and supplier returns', 'inventory', 0,
     'Inventory adjustments',
     $$Use an inventory adjustment to record a justified correction to stock. Enter the direction or resulting quantity as presented, a clear reason, and any required version or reference. The system can reject a change that would reduce stock below reserved quantity or conflict with a newer update; reload before retrying a version conflict.$$),
    ('40000000-0000-0000-0000-000000000009', 'Inventory adjustments damages and supplier returns', 'inventory', 1,
     'Damage records and reversal',
     $$Record damaged stock through the damage workflow with product, quantity or exact serialized unit, reason, responsible party when relevant, and liability amount when applicable. Damage affects inventory through an auditable document. Use the dedicated reversal action for an incorrect damage record rather than hiding it with an unrelated adjustment.$$),
    ('40000000-0000-0000-0000-000000000009', 'Inventory adjustments damages and supplier returns', 'inventory', 2,
     'Supplier returns',
     $$A supplier return removes eligible stock and can record supplier credit according to the workflow. Confirm supplier, product, quantity, cost, and reason. Serialized products require exact-unit return support; do not submit an aggregate serialized return when the interface rejects it.$$),

    ('40000000-0000-0000-0000-000000000010', 'Inventory history audit and traceability', 'inventory', 0,
     'Inventory transactions',
     $$InventoryHistory transactions show stock movements for the selected branch. Filter by date, movement type, business line, template, product, serial or IMEI, and supplier when available. Open related product or supplier details to investigate the source of a movement.$$),
    ('40000000-0000-0000-0000-000000000010', 'Inventory history audit and traceability', 'inventory', 1,
     'Inventory audit view',
     $$The audit sub-page shows operational changes and traceability evidence. Search and filter events, inspect grouped details, and export evidence only when permitted. Audit records explain who or what changed inventory but should be interpreted together with the originating transaction.$$),
    ('40000000-0000-0000-0000-000000000010', 'Inventory history audit and traceability', 'inventory', 2,
     'Investigating discrepancies',
     $$For an unexpected balance, verify branch, date range, reservations, serialized unit states, receipts, sales, returns, damages, adjustments, and reversals. Do not correct the balance until the source is understood. Record a specific reason and retain supporting references for any authorized adjustment.$$),

    ('40000000-0000-0000-0000-000000000011', 'Bulk product import', 'inventory', 0,
     'Preparing an import',
     $$BulkProductImport imports many products into the selected branch from a spreadsheet. Download or use the current template, keep required headers unchanged, and fill product names, categories, units, prices, quantities, barcodes, tracking details, and template attributes consistently.$$),
    ('40000000-0000-0000-0000-000000000011', 'Bulk product import', 'inventory', 1,
     'Validating the file',
     $$Upload the completed file and review validation before applying it. Correct missing required values, invalid categories or units, duplicate barcodes, duplicate serials or IMEIs, invalid prices, and unsupported tracking combinations. Do not apply a batch while important rows remain invalid.$$),
    ('40000000-0000-0000-0000-000000000011', 'Bulk product import', 'inventory', 2,
     'Import execution and history',
     $$Apply the import once after the preview is correct. The import uses audit and idempotency protections, so avoid uploading the same batch repeatedly after a slow response. Use import history and error reports to confirm accepted and rejected rows and to investigate previous batches.$$),

    ('40000000-0000-0000-0000-000000000012', 'Inventory pricing dynamic pricing and USD cost', 'inventory', 0,
     'Pricing visibility and permissions',
     $$Pricing pages require inventory pricing capabilities, and cost fields can require separate cost-read permission. Confirm branch scope and currency context before comparing prices. Direct product editing and controlled bulk pricing are different workflows.$$),
    ('40000000-0000-0000-0000-000000000012', 'Inventory pricing dynamic pricing and USD cost', 'inventory', 1,
     'Dynamic pricing workflow',
     $$DynamicPricingEngine can preview metrics, run recommendations, round proposed prices, and create an adjustment batch. A recommendation does not change product prices by itself. Where enabled, the batch moves through create, submit, approve, apply, reject, or cancel steps with permission checks and audit notes.$$),
    ('40000000-0000-0000-0000-000000000012', 'Inventory pricing dynamic pricing and USD cost', 'inventory', 2,
     'Inflation and USD pricing',
     $$Inflation tools preview scoped cost and retail changes before application. PricingWithUsd uses a current exchange-rate context and product USD cost settings where configured. Review scope, exchange rate, rounding, margins, and the preview before applying any bulk change.$$),

    ('40000000-0000-0000-0000-000000000013', 'Suppliers purchases and supplier balances', 'suppliers', 0,
     'Supplier records',
     $$Suppliers provides supplier search, profiles, contact details, balances, statements, receipts, returns, and audit history according to permission. Confirm the supplier identity before recording purchases, payments, credits, or returns.$$),
    ('40000000-0000-0000-0000-000000000013', 'Suppliers purchases and supplier balances', 'suppliers', 1,
     'Purchases and supplier invoices',
     $$Record incoming purchase or receipt information against the correct supplier and branch. Verify invoice reference, products, quantities, costs, tax, due terms, and serialized identifiers when applicable. A posted purchase can affect inventory, supplier balance, and finance, so use its intended correction or return workflow when wrong.$$),
    ('40000000-0000-0000-0000-000000000013', 'Suppliers purchases and supplier balances', 'suppliers', 2,
     'Supplier payments and open items',
     $$Use the supplier payment or finance workflow to settle eligible payable items. Match the payment to the correct supplier, currency, date, reference, and open invoices. Review the remaining payable or supplier credit after posting rather than assuming the account is fully settled.$$),

    ('40000000-0000-0000-0000-000000000014', 'Clients loyalty analytics and vouchers', 'customers', 0,
     'Client records',
     $$Add client creates a customer profile; View clients searches and manages existing profiles. Verify name, phone, contact information, credit settings, and duplicate records before saving. Access to create, read, or edit clients depends on capability.$$),
    ('40000000-0000-0000-0000-000000000014', 'Clients loyalty analytics and vouchers', 'customers', 1,
     'Credit loyalty and vouchers',
     $$Customer credit sales can be limited by configuration and customer credit status. Loyalty settings define available loyalty behavior, while client vouchers record authorized finance entries or receipts. Always link money to the correct client and source transaction and verify the remaining balance after posting.$$),
    ('40000000-0000-0000-0000-000000000014', 'Clients loyalty analytics and vouchers', 'customers', 2,
     'Purchase behavior analytics',
     $$CustomerBehaviorAnalyticsPage summarizes purchase patterns for users with customer behavior access. Interpret results within the selected company, branches, and date range. Use client and sales history for transaction-level confirmation and avoid treating an aggregate trend as an individual customer fact.$$),

    ('40000000-0000-0000-0000-000000000015', 'Finance home setup and mappings', 'finance', 0,
     'Finance workspace',
     $$FinanceHome and FinanceDashboard provide finance navigation and summaries. Finance data is company or branch scoped according to the page and permission. Use journals, source documents, reports, and reconciliation for evidence behind summary values.$$),
    ('40000000-0000-0000-0000-000000000015', 'Finance home setup and mappings', 'finance', 1,
     'Finance setup',
     $$FinanceSetup configures accounting foundations and mappings used by operational posting. Complete required accounts, source mappings, currencies, and related settings before relying on automatic posting. Changes require finance permission and should be reviewed carefully because later transactions depend on them.$$),
    ('40000000-0000-0000-0000-000000000015', 'Finance home setup and mappings', 'finance', 2,
     'Accounting safety',
     $$Posted accounting evidence should not be edited as ordinary draft data. Use supported reversal, correction, credit note, debit note, or follow-up journal workflows. Confirm period status and account mapping before posting, and never infer a final balance from a single dashboard card.$$),

    ('40000000-0000-0000-0000-000000000016', 'Finance posting requests and journals', 'finance', 0,
     'Posting requests',
     $$FinancePostingRequests shows operational events waiting for or undergoing accounting posting. Review source type, source reference, company or branch scope, amounts, status, and validation details. Resolve missing mappings or invalid source data before retrying a failed request.$$),
    ('40000000-0000-0000-0000-000000000016', 'Finance posting requests and journals', 'finance', 1,
     'Journals',
     $$FinanceJournals lists journal entries and their balanced debit and credit lines. Open a journal to verify posting date, period, source, accounts, dimensions, currency, amounts, and status. Posted journals are protected from direct mutation; use an authorized corrective workflow.$$),
    ('40000000-0000-0000-0000-000000000016', 'Finance posting requests and journals', 'finance', 2,
     'Troubleshooting posting',
     $$For a missing journal, first locate the source transaction and its posting request. Check finance setup, account mappings, fiscal period status, currency data, and the reported error. Avoid manually duplicating an entry while an automatic request might still complete.$$),

    ('40000000-0000-0000-0000-000000000017', 'Finance reconciliation periods and reports', 'finance', 0,
     'Reconciliation',
     $$FinanceReconciliation compares source items with finance records and helps resolve unmatched differences. Filter to the correct branch, account, source, currency, and period. Match only records that represent the same business event and document the reason for any manual resolution.$$),
    ('40000000-0000-0000-0000-000000000017', 'Finance reconciliation periods and reports', 'finance', 1,
     'Fiscal periods',
     $$FinancePeriods controls accounting date ranges and their operational status. Review outstanding work before closing a period. Transactions cannot always post into a closed period; reopening or changing a period requires appropriate authorization and audit justification.$$),
    ('40000000-0000-0000-0000-000000000017', 'Finance reconciliation periods and reports', 'finance', 2,
     'Finance reports',
     $$FinanceReports can include trial balance and other accounting views depending on configuration. Set the date, company or branch scope, currency, and report options before running. Trace unexpected totals to journals and source documents and export only data the user is authorized to access.$$),

    ('40000000-0000-0000-0000-000000000018', 'Sales expenses payables and receivables', 'sales', 0,
     'Sales reporting',
     $$SalesScreen provides sales history and reporting for authorized users. Filter by date, branch, cashier, customer, payment method, or status where available. Open the original order or invoice for detail, and use the supported return workflow rather than changing reported totals.$$),
    ('40000000-0000-0000-0000-000000000018', 'Sales expenses payables and receivables', 'sales', 1,
     'Expenses',
     $$Expenses records authorized business expenses with date, category or account, amount, branch, payee, payment details, description, and evidence as required. Verify finance mapping and avoid duplicate entry after a slow response. Correct posted expenses through the supported workflow.$$),
    ('40000000-0000-0000-0000-000000000018', 'Sales expenses payables and receivables', 'sales', 2,
     'Obligations and open items',
     $$Payables and Receivables reports show open customer, supplier, and other obligations according to the selected scope and date. Review due dates, original documents, allocations, credits, and remaining balances. Record settlements through the correct receipt or payment workflow so open items and finance stay consistent.$$),

    ('40000000-0000-0000-0000-000000000019', 'Attendance dashboard sessions and monthly calendar', 'attendance', 0,
     'Attendance dashboard',
     $$HRDashboard summarizes employee presence and attendance for the selected company or branch and date. Review present, absent, late, active-session, and exception indicators according to configured schedules. Open employee or attendance detail before taking action on a summary.$$),
    ('40000000-0000-0000-0000-000000000019', 'Attendance dashboard sessions and monthly calendar', 'attendance', 1,
     'Clock-in and clock-out sessions',
     $$Attendance supports employee work sessions and can allow multiple daily sessions according to policy. A clock-in opens a session and a clock-out closes it. Resolve an existing open session or identity mismatch before recording another event, and keep corrections auditable.$$),
    ('40000000-0000-0000-0000-000000000019', 'Attendance dashboard sessions and monthly calendar', 'attendance', 2,
     'Monthly attendance map',
     $$HRMonthlyAttendance displays attendance across a selected month. Use employee, branch, status, or schedule context where available and inspect a day before interpreting absence or lateness. Holidays, approved leave, shift assignment, and incomplete sessions can affect the displayed status.$$),

    ('40000000-0000-0000-0000-000000000020', 'Employees attendance shifts and assignments', 'attendance', 0,
     'Employees',
     $$HREmployees manages employee records used by attendance and payroll. Link the correct application user identity when required and maintain employment, branch, schedule, and status information. Duplicate or missing identity links can prevent attendance and payroll from resolving the employee.$$),
    ('40000000-0000-0000-0000-000000000020', 'Employees attendance shifts and assignments', 'attendance', 1,
     'Attendance shifts',
     $$HRShifts defines work schedules such as start time, end time, breaks, and applicable rules. Editing a shift requires the shift-edit capability. Review how a change affects existing assignments and reporting dates before saving.$$),
    ('40000000-0000-0000-0000-000000000020', 'Employees attendance shifts and assignments', 'attendance', 2,
     'Shift assignments',
     $$HRAssignments connects employees to attendance shifts for effective dates. Choose the employee, shift, branch, and date range carefully and avoid overlapping assignments unless the application explicitly supports them. Historical attendance should be interpreted with the assignment effective on that day.$$),

    ('40000000-0000-0000-0000-000000000021', 'Payroll salary profiles and current salaries', 'payroll', 0,
     'Salary profiles',
     $$PayrollSalaryProfiles defines employee compensation inputs used by payroll, such as base salary and configured components. Confirm employee identity, currency, effective dates, and active status. Changes should become effective through the supported dated workflow rather than rewriting historical payroll.$$),
    ('40000000-0000-0000-0000-000000000021', 'Payroll salary profiles and current salaries', 'payroll', 1,
     'Current salaries',
     $$PayrollCurrentSalaries shows current employee salary information for authorized users. Values depend on active salary profiles and effective dates. Use payroll runs and audit records for historical paid amounts rather than assuming the current profile applied in the past.$$),
    ('40000000-0000-0000-0000-000000000021', 'Payroll salary profiles and current salaries', 'payroll', 2,
     'Attendance inputs',
     $$Payroll can use attendance snapshots and approved calendar information according to configuration. Review incomplete sessions, absences, leave, holidays, and assignments before finalizing a run. Correct source attendance through its authorized workflow so the payroll evidence remains traceable.$$),

    ('40000000-0000-0000-0000-000000000022', 'Payroll adjustments runs and payments', 'payroll', 0,
     'Payroll adjustments',
     $$PayrollAdjustments records authorized additions or deductions with employee, type, amount, effective period, reason, and status. Avoid duplicate adjustments and verify whether an item is recurring or applies to one run. Preserve approvals and supporting references.$$),
    ('40000000-0000-0000-0000-000000000022', 'Payroll adjustments runs and payments', 'payroll', 1,
     'Payroll runs',
     $$PayrollRuns calculates payroll for a defined company, branch, and period using eligible profiles, adjustments, and attendance inputs. Review warnings and employee results before approval or finalization. Do not rerun or pay a period without checking the status of an existing run.$$),
    ('40000000-0000-0000-0000-000000000022', 'Payroll adjustments runs and payments', 'payroll', 2,
     'Payroll payments',
     $$PayrollPayments records settlement of approved payroll liabilities according to permission and finance setup. Verify employee, run, amount, date, method, reference, and remaining payable. Payment posting should not exceed the eligible unpaid amount.$$),

    ('40000000-0000-0000-0000-000000000023', 'Payroll settings and audit', 'payroll', 0,
     'Payroll settings',
     $$PayrollSettings contains payroll behavior and finance mappings available to authorized users. Configure accounts, calendars, calculation rules, and payment settings before production runs. Review downstream impact before changing settings that affect calculations.$$),
    ('40000000-0000-0000-0000-000000000023', 'Payroll settings and audit', 'payroll', 1,
     'Payroll audit',
     $$PayrollAudit shows traceability for profile, adjustment, run, and payment activity. Filter to the relevant employee, period, action, or reference and inspect the originating record. Audit data is evidence and should not be altered to hide a correction.$$),
    ('40000000-0000-0000-0000-000000000023', 'Payroll settings and audit', 'payroll', 2,
     'Payroll troubleshooting',
     $$If payroll is missing or unexpected, check employee identity, active salary profile, effective dates, attendance snapshot, approved leave or holidays, adjustments, run status, finance mappings, and permissions. Correct the source record and use the supported recalculation path rather than editing finalized results directly.$$),

    ('40000000-0000-0000-0000-000000000024', 'Company branch loyalty and printer settings', 'settings', 0,
     'Company settings',
     $$MainCompanySettings manages company-level configuration for authorized owners and administrators. Review company identity, operational defaults, billing-related state, and enabled settings carefully. Company changes can affect every branch and should be made only with the required capability.$$),
    ('40000000-0000-0000-0000-000000000024', 'Company branch loyalty and printer settings', 'settings', 1,
     'Branch settings',
     $$MainBranchSettings controls branch-specific behavior such as operational options, inventory thresholds, POS behavior, and printer configuration where available. Confirm the target branch before saving. Branch settings override or specialize company behavior only where the application supports it.$$),
    ('40000000-0000-0000-0000-000000000024', 'Company branch loyalty and printer settings', 'settings', 2,
     'Loyalty and receipt setup',
     $$LoyaltySettings configures available customer loyalty behavior. Receipt printer settings select supported paper kind, format, and default printer behavior for the branch. Test a non-destructive preview or reprint after configuration and do not create a sale merely to test printing.$$),

    ('40000000-0000-0000-0000-000000000025', 'Users permissions and account access', 'settings', 0,
     'Creating and editing users',
     $$Add user creates an account for a company according to permission. Enter correct identity and contact data, assign an appropriate role or access configuration, and communicate credentials securely. Edit users manages existing account status and permitted changes.$$),
    ('40000000-0000-0000-0000-000000000025', 'Users permissions and account access', 'settings', 1,
     'Capabilities and roles',
     $$ValueInSoft authorizes actions through capabilities, scope, and legacy role rules. Read, create, edit, approve, apply, export, cost visibility, and administrative actions can require different capabilities. Grant the least access needed and never work around a denied action through another screen.$$),
    ('40000000-0000-0000-0000-000000000025', 'Users permissions and account access', 'settings', 2,
     'Account and password safety',
     $$Users can manage permitted profile information from the account page. A password reset or reset-required state must follow the supported authentication flow. Do not place passwords, access tokens, API keys, or private credentials in AI chat, notes, imports, or support screenshots.$$),

    ('40000000-0000-0000-0000-000000000026', 'Company onboarding branches and profile', 'onboarding', 0,
     'Creating a company',
     $$CreateCompany starts company onboarding for an authenticated user. Enter accurate company identity and required business information, then complete the supported subscription or configuration steps. Avoid creating duplicate companies when a previous submission is still processing.$$),
    ('40000000-0000-0000-0000-000000000026', 'Company onboarding branches and profile', 'onboarding', 1,
     'Adding a branch',
     $$AddBranch creates a branch under the current company for users with company settings access. Enter the branch identity, location and operational information requested by the form. After creation, review branch settings, user access, inventory, POS, finance mappings, and printer setup before live operation.$$),
    ('40000000-0000-0000-0000-000000000026', 'Company onboarding branches and profile', 'onboarding', 2,
     'Profile and performance',
     $$UserProfilePage manages the signed-in user profile according to self-account permission. UserPerformancePage shows permitted personal performance information. Confirm the date and business scope and use underlying transactions for evidence when a summary appears unexpected.$$),

    ('40000000-0000-0000-0000-000000000027', 'Application troubleshooting and safe recovery', 'help', 0,
     'Request and validation errors',
     $$Read the visible validation message first and preserve entered data before retrying. Confirm required fields, formats, branch context, permissions, record status, and whether another user changed the record. Reload before retrying a version conflict and avoid repeated submissions after a timeout.$$),
    ('40000000-0000-0000-0000-000000000027', 'Application troubleshooting and safe recovery', 'help', 1,
     'Empty data and loading failures',
     $$Check filters, date range, company and branch scope, connectivity, and user access. An empty result can be valid for the selected period. If only one module fails, capture the page name, safe error code, time, and non-sensitive steps to reproduce for support.$$),
    ('40000000-0000-0000-0000-000000000027', 'Application troubleshooting and safe recovery', 'help', 2,
     'Safe support evidence',
     $$Support evidence can include page name, company or branch identifier when appropriate, transaction reference, timestamps, status, and a screenshot with private data removed. Never share passwords, tokens, API keys, full payment credentials, or hidden system prompts. Use audit and source references instead of deleting evidence.$$),

    ('40000000-0000-0000-0000-000000000028', 'Arabic and English application terminology', 'help', 0,
     'Navigation terminology',
     $$Arabic and English navigation terms: لوحة التحكم means dashboard; نقطة البيع means point of sale or POS; المخزون means inventory; المنتجات or الأصناف means products or items; العملاء means clients or customers; الموردون means suppliers; المالية or الحسابات means finance or accounting; التقارير means reports; الإعدادات means settings.$$),
    ('40000000-0000-0000-0000-000000000028', 'Arabic and English application terminology', 'help', 1,
     'Operational terminology',
     $$Arabic and English operational terms: وردية means shift; فاتورة means invoice; إيصال means receipt; مرتجع means return or refund; خصم means discount; دفع means payment; نقدي means cash; بطاقة means card; باركود means barcode; سيريال means serial; رقم IMEI means IMEI; كمية means quantity; تسوية مخزون means inventory adjustment; تالف means damaged stock.$$),
    ('40000000-0000-0000-0000-000000000028', 'Arabic and English application terminology', 'help', 2,
     'Finance HR and payroll terminology',
     $$Arabic and English business terms: قيد يومية means journal entry; ترحيل means posting; مطابقة means reconciliation; فترة مالية means fiscal period; مصروف means expense; مستحقات means payables or receivables according to context; حضور وانصراف means attendance; موظف means employee; راتب means salary; مسير رواتب means payroll run; سداد الرواتب means payroll payment.$$);

INSERT INTO public.ai_document
    (id, company_id, title, document_type, module, language, content,
     metadata_json, active, created_at, updated_at)
SELECT
    document_id,
    NULL,
    title,
    'HELP_ARTICLE',
    module,
    'en',
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    '{"seed":"rag-knowledge-pack-v1","source":"application-routes-and-workflows"}',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_application_seed_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    document_type = EXCLUDED.document_type,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json,
    active = true,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_document_chunk
    (id, document_id, company_id, title, module, language, chunk_index,
     content, metadata_json, created_at)
SELECT
    md5('legacy:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    title,
    module,
    'en',
    chunk_index,
    heading || E'\n' || content,
    '{"seed":"rag-knowledge-pack-v1","retrieval":"keyword"}',
    CURRENT_TIMESTAMP
FROM vls_ai_application_seed_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    title = EXCLUDED.title,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json;

INSERT INTO public.ai_knowledge_document
    (id, company_id, branch_id, module, language, document_type, title,
     source_type, source_uri, content_hash, raw_content, normalized_content,
     status, metadata_json, created_at, updated_at)
SELECT
    document_id,
    NULL,
    NULL,
    module,
    'en',
    'HELP_ARTICLE',
    title,
    'APPLICATION',
    'valueinsoft://help/' || replace(lower(title), ' ', '-'),
    md5(string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index)),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    'ACTIVE',
    '{"seed":"rag-knowledge-pack-v1","source":"application-routes-and-workflows"}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_application_seed_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    document_type = EXCLUDED.document_type,
    title = EXCLUDED.title,
    source_type = EXCLUDED.source_type,
    source_uri = EXCLUDED.source_uri,
    content_hash = EXCLUDED.content_hash,
    raw_content = EXCLUDED.raw_content,
    normalized_content = EXCLUDED.normalized_content,
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_knowledge_chunk
    (id, document_id, company_id, branch_id, module, language, chunk_index,
     heading, content, token_count, embedding, embedding_model, status,
     metadata_json, created_at)
SELECT
    md5('knowledge:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    NULL,
    module,
    'en',
    chunk_index,
    heading,
    content,
    cardinality(regexp_split_to_array(btrim(content), E'\\s+')),
    NULL,
    'keyword-fallback',
    'ACTIVE',
    '{"seed":"rag-knowledge-pack-v1","embeddingStatus":"pending-real-provider"}'::jsonb,
    CURRENT_TIMESTAMP
FROM vls_ai_application_seed_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    branch_id = EXCLUDED.branch_id,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    heading = EXCLUDED.heading,
    content = EXCLUDED.content,
    token_count = EXCLUDED.token_count,
    embedding = NULL,
    embedding_model = 'keyword-fallback',
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json;

DROP TABLE vls_ai_application_seed_chunk;
