-- ==========================================================
-- V165 - Detailed POS and Inventory RAG knowledge
-- ==========================================================
-- Source-of-truth help content derived from the implemented frontend,
-- backend services, validation rules, capabilities, and lifecycle states.
-- The migration deliberately writes the same corpus to both RAG stores.
-- Embeddings remain pending for a configured real embedding provider;
-- keyword retrieval is immediately available and model answers stay grounded.
-- ==========================================================

CREATE TEMP TABLE vls_ai_pos_inventory_detail_chunk (
    document_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    module VARCHAR(100) NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (document_id, chunk_index)
);

INSERT INTO vls_ai_pos_inventory_detail_chunk
    (document_id, title, module, chunk_index, heading, content)
VALUES
    ('41000000-0000-0000-0000-000000000001', 'POS entry modes and business context', 'pos', 0,
     'Opening Point of Sale',
     $$Open Point of Sale from the application navigation. The branch setting pos.mainScreenMode chooses the Classic or Modern main POS experience; both use the same server-backed catalog and posting rules. The user needs pos.sale.create to create sales and pos.sale.read to inspect sales. Missing actions can mean the capability, company, branch, or authenticated session is missing.$$),
    ('41000000-0000-0000-0000-000000000001', 'POS entry modes and business context', 'pos', 1,
     'Company branch and cart scope',
     $$The active cart is scoped to the current company and branch. If either context changes, the previous cart is not valid for the new scope and the POS clears or rejects it. Confirm the current branch before scanning products, selecting a customer, opening a shift, or paying; catalog stock, prices, settings, devices, and shifts are branch-specific.$$),
    ('41000000-0000-0000-0000-000000000001', 'POS entry modes and business context', 'pos', 2,
     'Classic and Modern views',
     $$Classic POS emphasizes the established category and product layout. Modern POS adds the newer catalog, filter, and barcode interaction. Switching presentation does not bypass stock, serialized-unit, customer-credit, payment, shift, permission, idempotency, or finance rules. Use the mode configured for the branch and report the visible mode when requesting support.$$),

    ('41000000-0000-0000-0000-000000000002', 'POS catalog search filters and barcode scanning', 'pos', 0,
     'Finding products',
     $$Find a product by category, product name, barcode, serial number, or IMEI when the relevant identifier is indexed. Modern POS supports category selection and filters for stock state, returned or bounced-back state, used items, sellable items, price range, and major. Clear restrictive filters when a known product is not displayed.$$),
    ('41000000-0000-0000-0000-000000000002', 'POS catalog search filters and barcode scanning', 'pos', 1,
     'Barcode outcomes',
     $$A barcode scan can add one unambiguous available product, report no match, or show multiple candidates or variants that require selection. An out-of-stock match is not added as normal sellable stock. For a serial or IMEI scan, select the exact available unit rather than treating the identifier as an aggregate product barcode.$$),
    ('41000000-0000-0000-0000-000000000002', 'POS catalog search filters and barcode scanning', 'pos', 2,
     'Catalog recovery',
     $$If search returns nothing, verify spelling or scan quality, remove filters, check category, confirm branch, and compare Inventory availability. When offline mode is active, the catalog comes from the downloaded branch cache and can be stale until bootstrap data is refreshed online. Do not create a duplicate product merely because one filtered or offline search failed.$$),

    ('41000000-0000-0000-0000-000000000003', 'POS cart quantity stock and removal rules', 'pos', 0,
     'Adding cart lines',
     $$The cart normalizes product data and groups only lines with the same cart-line identity. A product that is out of stock is blocked unless the implemented product rule explicitly allows it. Serialized units remain distinct because their exact unit identity matters. Review product name, identifier, unit price, and quantity after each scan.$$),
    ('41000000-0000-0000-0000-000000000003', 'POS cart quantity stock and removal rules', 'pos', 1,
     'Changing quantity',
     $$Increasing a quantity-tracked line cannot exceed its available quantity. Decreasing a line at quantity one removes it from the cart. Serialized or IMEI units should be added or removed as exact units, not increased as a generic quantity. Stock can change concurrently, so checkout performs authoritative validation even when the cart initially accepted a line.$$),
    ('41000000-0000-0000-0000-000000000003', 'POS cart quantity stock and removal rules', 'pos', 2,
     'Reading totals safely',
     $$The cart summary includes line count, base amount, offer discounts, manual discount, loyalty discount, and final total as applicable. Inspect every applied adjustment before payment. If a displayed total changes after validation, re-check prices, stock, offers, customer, and tax context; do not repeatedly submit an outdated cart.$$),

    ('41000000-0000-0000-0000-000000000004', 'POS serialized and IMEI sales', 'pos', 0,
     'Selecting an exact unit',
     $$Products tracked as IMEI or SERIAL require an exact available product unit. Scan or select the unit identifier and confirm it belongs to the intended product and branch. A generic product row without a productUnitId or valid serial or IMEI cannot safely represent a serialized sale line.$$),
    ('41000000-0000-0000-0000-000000000004', 'POS serialized and IMEI sales', 'pos', 1,
     'Unavailable identifiers',
     $$A serialized unit may be AVAILABLE, sold, reserved, returned, damaged, under repair, or otherwise unavailable. Only an eligible available unit can be sold normally. If the identifier exists but is unavailable, inspect Inventory unit history instead of changing the identifier or selecting a different physical unit to bypass validation.$$),
    ('41000000-0000-0000-0000-000000000004', 'POS serialized and IMEI sales', 'pos', 2,
     'Online-only serialized checkout',
     $$Serialized and IMEI sale lines must be posted online. The Save Offline action is disabled when serialized items are present because the server must atomically verify and transition exact unit state. Restore backend connectivity and retry once with the same intended unit; do not replace the line with a quantity-tracked placeholder.$$),

    ('41000000-0000-0000-0000-000000000005', 'POS checkout posting and duplicate protection', 'pos', 0,
     'Before confirming checkout',
     $$Confirm company, branch, active shift when required, cart lines, exact serialized units, customer or supplier, payment option, paid amount, discounts, loyalty reservation, and receipt language. The server revalidates ownership, stock, totals, credit rules, and request structure inside the posting transaction.$$),
    ('41000000-0000-0000-0000-000000000005', 'POS checkout posting and duplicate protection', 'pos', 1,
     'Idempotent submission',
     $$POS posting uses an idempotency key so a replay of the same completed request returns the existing result and skips duplicate downstream posting. After a slow response, check the order result or sales history before clicking again. Reusing one idempotency key with different payload data is a conflict, not a way to edit a sale.$$),
    ('41000000-0000-0000-0000-000000000005', 'POS checkout posting and duplicate protection', 'pos', 2,
     'Finance posting after sale',
     $$A saved POS order enqueues its finance posting request after the sale transaction commits. If the enqueue step later fails, the sale can remain saved and operations should inspect the posting request or retry workflow rather than create another order. The configured mappings include POS sales account 4100 and sales returns account 4300.$$),

    ('41000000-0000-0000-0000-000000000006', 'POS payment credit and counterparty rules', 'pos', 0,
     'Paid amount validation',
     $$paidNow must be between zero and the final order total. A non-credit sale cannot be partially paid; the server returns POS_PARTIAL_PAYMENT_REQUIRES_CREDIT. Use the supported credit workflow for a remaining receivable, or collect the full required amount. A paid amount greater than the total is invalid even if the interface can calculate change.$$),
    ('41000000-0000-0000-0000-000000000006', 'POS payment credit and counterparty rules', 'pos', 1,
     'Customer credit',
     $$A customer credit sale requires a selected client. The credit-control service locks and checks that client in the same transaction; a denial rolls back the order, while configured warning behavior can permit posting with a warning. A receivable sale must leave a positive outstanding balance. Paid-now amounts can create a linked client receipt and the remainder becomes an open receivable item.$$),
    ('41000000-0000-0000-0000-000000000006', 'POS payment credit and counterparty rules', 'pos', 2,
     'Supplier receivable sale',
     $$The POS can sell eligible stock to a supplier as the counterparty when that workflow is selected. It requires a supplier, uses supplier-specific displayed sale amounts, and records the amount the supplier owes the business. Confirm that this is a sale to the supplier, not an inventory purchase from the supplier, before posting.$$),

    ('41000000-0000-0000-0000-000000000007', 'POS discounts offers and loyalty', 'pos', 0,
     'Offers and automatic discounts',
     $$Configured POS offers can be applied to eligible lines or the order. The payment view lists each applied offer and calculated discount and allows removal before posting. Eligibility, offer type, percentage or fixed value, active dates, and branch context determine the result. Removing an offer recalculates the order total.$$),
    ('41000000-0000-0000-0000-000000000007', 'POS discounts offers and loyalty', 'pos', 1,
     'Manual discount boundary',
     $$A manual discount must not reduce the payable amount below permitted price and discount boundaries. The interface displays the remaining maximum after automatic and loyalty discounts. If the discount is rejected, reduce it or obtain the required authority; do not alter item cost or tracking data to simulate a discount.$$),
    ('41000000-0000-0000-0000-000000000007', 'POS discounts offers and loyalty', 'pos', 2,
     'Loyalty redemption and earning',
     $$Select a customer to load points, eligible rewards, projected earning, and maximum rounded redemption. Applying a reward reserves a redemption and reduces the checkout amount; it can be removed before posting. The server confirms redemption during the sale and awards eligible earned points. Insufficient points or no configured reward prevents redemption.$$),

    ('41000000-0000-0000-0000-000000000008', 'POS repair tickets receipts and printing', 'pos', 0,
     'Repair ticket sale context',
     $$POS can load supported repair work by repair ticket identifier or customer IMEI through the repair slot and ticket workflow. Validate the returned customer, device, repair details, and payable amount. A missing ticket or already-paid ticket is not a new sale; inspect the ticket history instead of rebuilding it as an unrelated cart.$$),
    ('41000000-0000-0000-0000-000000000008', 'POS repair tickets receipts and printing', 'pos', 1,
     'Receipt preview and language',
     $$Before printing, the payment screen can preview the receipt with customer or supplier name, serialized identifiers, item prices, offer discount, manual discount, loyalty discount, total, and payment state. Invoice language can be Arabic or English. Check the preview after any payment or discount change.$$),
    ('41000000-0000-0000-0000-000000000008', 'POS repair tickets receipts and printing', 'pos', 2,
     'Browser and direct printing',
     $$The checkout supports browser printing and direct printing through the configured printer integration. Receipt printer settings include printer selection and paper profiles such as 80 mm and 58 mm receipt paper. A print failure does not mean the order failed; verify sales history first, then reprint the saved order without reposting it.$$),

    ('41000000-0000-0000-0000-000000000009', 'POS shift opening active state and cash movements', 'shift', 0,
     'Opening a shift',
     $$Open a shift for the selected branch with the opening float and cashier assignment. Capability pos.shift.create is required. Opening is idempotent at the business level: when an active branch shift already exists, use that shift rather than opening another. The active-shift lookup requires pos.shift.read and can return no content when none is open.$$),
    ('41000000-0000-0000-0000-000000000009', 'POS shift opening active state and cash movements', 'shift', 1,
     'Cash movements',
     $$Use the cash-movement action for auditable cash added to or removed from an active shift and provide its supported reason or note. It requires pos.shift.edit. Cash received in a posted cash sale is also recorded against the active shift by the sale posting flow; do not enter that same receipt again as a manual cash movement.$$),
    ('41000000-0000-0000-0000-000000000009', 'POS shift opening active state and cash movements', 'shift', 2,
     'Shift details and history',
     $$Users with pos.shift.read can open enriched shift details, orders, totals, reconciliation data, branch shift history, and the shift event log. Use the events and source orders to explain differences. Reading sales in legacy shift detail can additionally require pos.sale.read.$$),

    ('41000000-0000-0000-0000-000000000010', 'POS shift reconciliation close and force close', 'shift', 0,
     'Server reconciliation',
     $$Before closing, load the shift reconciliation calculated by the server. Review opening cash, expected cash, recorded cash movements, sales by payment behavior, and other displayed totals. Enter counted cash accurately; the variance is the difference between counted and expected cash, not an amount to hide with a new sale.$$),
    ('41000000-0000-0000-0000-000000000010', 'POS shift reconciliation close and force close', 'shift', 1,
     'Closing and variance approval',
     $$Normal closing requires pos.shift.close and submits the close request through server-side reconciliation. A branch policy can require explanation or approval for a variance; pos.shift.approve_variance is the dedicated approval capability where applicable. Resolve pending work and document the reason before closing.$$),
    ('41000000-0000-0000-0000-000000000010', 'POS shift reconciliation close and force close', 'shift', 2,
     'Force close',
     $$Force close is a manager action protected by pos.shift.force_close and records a reason and audit event. Use it only when the normal close path cannot be completed after investigation. It does not erase discrepancies, queued offline orders, or posting evidence; those remain subjects for reconciliation.$$),

    ('41000000-0000-0000-0000-000000000011', 'Offline POS readiness device and bootstrap', 'pos', 0,
     'Readiness prerequisites',
     $$Offline sales require offline mode enabled by company configuration, a registered active device, the correct company and branch, and downloaded POS data. Readiness checks products, prices, payment methods, permissions, tax data, discounts, POS settings, and whether offline sales are allowed. A blocked or inactive device cannot synchronize normally.$$),
    ('41000000-0000-0000-0000-000000000011', 'Offline POS readiness device and bootstrap', 'pos', 1,
     'Downloading bootstrap data',
     $$While the backend is reachable, download or refresh the full offline bootstrap or an available section such as suppliers. The local IndexedDB cache is scoped to company and branch and stores operational snapshots including products, serialized units, clients, and suppliers. Bootstrap cannot be refreshed while disconnected or without company, branch, and login token.$$),
    ('41000000-0000-0000-0000-000000000011', 'Offline POS readiness device and bootstrap', 'pos', 2,
     'Limits of offline operation',
     $$Offline data is a snapshot and may not reflect another device's recent stock, customer, price, or permission changes. Serialized sales are online-only. A locally saved offline sale is queued, not yet an official server order. Keep the same branch and device context and do not recreate the queued sale online unless its server status is known.$$),

    ('41000000-0000-0000-0000-000000000012', 'Offline POS queue sync states and recovery', 'pos', 0,
     'Order and batch lifecycle',
     $$Offline order imports can move through PENDING, PENDING_RETRY, PROCESSING, READY_FOR_VALIDATION, VALIDATING, VALIDATED, POSTING, and SYNCED. Failure outcomes include VALIDATION_FAILED, POSTING_FAILED, FAILED, DUPLICATE, and NEEDS_REVIEW. Batch states include RECEIVED, IN_PROGRESS or PROCESSING, COMPLETED, COMPLETED_WITH_ERRORS, PARTIALLY_SYNCED, SYNCED, and FAILED.$$),
    ('41000000-0000-0000-0000-000000000012', 'Offline POS queue sync states and recovery', 'pos', 1,
     'Normal synchronization',
     $$When connectivity returns, sync queued clients as needed, sync pending orders, and poll server statuses. Auto-sync on reconnect can be enabled in offline settings. The queue displays server identifiers, backend error codes, messages, and last sync errors. Archive synchronized orders and clean archived local data only after server completion is confirmed.$$),
    ('41000000-0000-0000-0000-000000000012', 'Offline POS queue sync states and recovery', 'pos', 2,
     'Failed duplicate and review states',
     $$A DUPLICATE normally means idempotency protection found an existing request; inspect the linked server result. NEEDS_REVIEW means automatic processing cannot safely decide, especially around uncertain posting. Administrators with pos.offline.status, pos.offline.errors, pos.offline.retry, or pos.offline.sync can inspect and retry permitted work. Never force repeated processing without checking the order, inventory, and finance effects.$$),

    ('41000000-0000-0000-0000-000000000013', 'POS permissions and troubleshooting', 'pos', 0,
     'POS capabilities',
     $$Primary sale capabilities are pos.sale.create, pos.sale.read, and pos.sale.edit where supported. Shift capabilities are pos.shift.read, pos.shift.create, pos.shift.edit, pos.shift.close, pos.shift.force_close, and pos.shift.approve_variance. Offline administration separates pos.offline.sync, pos.offline.status, pos.offline.errors, and pos.offline.retry. A hidden or disabled action usually reflects one of these checks.$$),
    ('41000000-0000-0000-0000-000000000013', 'POS permissions and troubleshooting', 'pos', 1,
     'Checkout failure checklist',
     $$For a rejected checkout, preserve the cart and read the error code. Check active branch and shift, product availability, exact serialized unit, price and discount bounds, paid amount, credit flag, selected customer or supplier, loyalty reservation, session, and capability. Reload authoritative data before retrying a stock or concurrency conflict.$$),
    ('41000000-0000-0000-0000-000000000013', 'POS permissions and troubleshooting', 'pos', 2,
     'Do not duplicate uncertain sales',
     $$After a timeout or print error, first search sales history, current shift orders, offline queue status, and finance posting status. Retrying with a new idempotency key can create a second legitimate sale. Use the original reference when possible and escalate NEEDS_REVIEW or inconsistent stock and finance results with timestamps and non-sensitive evidence.$$),

    ('41000000-0000-0000-0000-000000000014', 'Inventory workspace modes and exact search', 'inventory', 0,
     'Inventory workspace modes',
     $$The Inventory workspace provides Dashboard, Browse, Quick Find, and Analysis modes. Dashboard loads its own summary data. Browse searches the product catalog. Quick Find resolves an exact-like barcode, SKU, serial, or IMEI query. Analysis searches inventory movements for a period. All results use the active company and branch.$$),
    ('41000000-0000-0000-0000-000000000014', 'Inventory workspace modes and exact search', 'inventory', 1,
     'Quick Find behavior',
     $$Quick Find waits for an exact-like query: a mostly numeric identifier or an alphanumeric serial-like value of at least five characters. exactType defaults to auto so the server can identify the lookup type. Use the full barcode, serial, or IMEI for best results; partial product names belong in Browse.$$),
    ('41000000-0000-0000-0000-000000000014', 'Inventory workspace modes and exact search', 'inventory', 2,
     'Serialized search results',
     $$Inventory can expand serialized products into individual unit rows when inventory.showSerializedUnitRows is enabled. Unit rows expose identifier, unit status, and cost only when permitted. If several identifiers belong to one product, expand the product or open its drawer and filter units by identifier or status.$$),

    ('41000000-0000-0000-0000-000000000015', 'Inventory browsing filters presets sorting and export', 'inventory', 0,
     'Browse filters and quick chips',
     $$Browse supports stock and item state, business line, template, supplier, major, quantity range, buying and selling price ranges, barcode presence, supplier presence, created-date range, and last-movement range. Quick chips include in-stock, low-stock, out-of-stock, and used views where available. Applied filters are combined, so reset them when results look unexpectedly empty.$$),
    ('41000000-0000-0000-0000-000000000015', 'Inventory browsing filters presets sorting and export', 'inventory', 1,
     'Sorting paging and presets',
     $$Default browse page size is 25 and is constrained between 10 and 200 by settings. Default sort is updatedAt descending; configured alternatives can include stock and name ordering. Personal presets save a query state. Publishing a branch or global preset requires the corresponding preset permission; applying a preset restores its mode, search, filters, sort, and page size.$$),
    ('41000000-0000-0000-0000-000000000015', 'Inventory browsing filters presets sorting and export', 'inventory', 2,
     'Excel and PDF export',
     $$Inventory catalog export is available only with the required item-read, export, and cost-read access enforced by the screen. Export uses the current branch and active filters. Excel export is limited to the first 50,000 items. Treat exported cost and serial data as sensitive and do not assume an export contains rows beyond its documented limit.$$),

    ('41000000-0000-0000-0000-000000000016', 'Inventory product creation templates categories and attributes', 'inventory', 0,
     'Creating a product',
     $$Open Add Inventory Item with inventory.item.create, choose the product template, and enter the required product name, category, business line, unit, tracking type, barcode or SKU, prices, supplier, condition, and dynamic attributes. The create-and-receive flow can create the product and its opening receipt atomically.$$),
    ('41000000-0000-0000-0000-000000000016', 'Inventory product creation templates categories and attributes', 'inventory', 1,
     'Template validation',
     $$The selected inventory template must exist and be active. Only attributes defined by the template are accepted; required attributes must be present and NUMBER, BOOLEAN, and DATE fields must have the correct type, with dates formatted yyyy-MM-dd. Templates explicitly control whether SERIAL or IMEI and BATCH tracking are supported.$$),
    ('41000000-0000-0000-0000-000000000016', 'Inventory product creation templates categories and attributes', 'inventory', 2,
     'Categories and identity fields',
     $$Categories organize Inventory and POS discovery. Use an existing category and avoid duplicate names with slightly different spelling. Product identity, template, base unit, and tracking type have downstream transaction meaning. After movements exist, change these only through supported editing rules and verify the product and unit history afterward.$$),

    ('41000000-0000-0000-0000-000000000017', 'Inventory product pricing tracking and condition', 'inventory', 0,
     'Price order rule',
     $$For create-and-receive product data, retailPrice must be greater than or equal to lowestPrice, and lowestPrice must be greater than or equal to buyingPrice. The server rejects an invalid order with PRODUCT_PRICE_ORDER_INVALID. Cost visibility can require inventory.pricing.cost.read separately from ordinary item read.$$),
    ('41000000-0000-0000-0000-000000000017', 'Inventory product pricing tracking and condition', 'inventory', 1,
     'Tracking types',
     $$QUANTITY tracks an aggregate balance. SERIAL and IMEI track one exact identifier per physical unit. IMEI must be a valid 15-digit number. BATCH is only allowed by templates that support it. A template that does not support the requested SERIAL, IMEI, or BATCH type returns TRACKING_TYPE_TEMPLATE_UNSUPPORTED.$$),
    ('41000000-0000-0000-0000-000000000017', 'Inventory product pricing tracking and condition', 'inventory', 2,
     'New and used condition',
     $$Inventory receipts accept conditionCode NEW or USED. Condition is part of the operational identity and affects filters and display. Use the dedicated serialized condition-correction workflow for an incorrect exact-unit condition; do not silently edit history or receive the same physical unit again.$$),

    ('41000000-0000-0000-0000-000000000018', 'Inventory supplier and client trade-in receipts', 'inventory', 0,
     'Receipt operation modes',
     $$Inventory product receipt supports creating and receiving a new product or receiving an existing product. RECEIVE_EXISTING_PRODUCT requires existingProductId. Creating a new product requires a product payload. Every request needs company, branch, receipt data, operation mode, and an idempotency key.$$),
    ('41000000-0000-0000-0000-000000000018', 'Inventory supplier and client trade-in receipts', 'inventory', 1,
     'Supplier receipt',
     $$A supplier receipt uses a supplier in the selected branch and must not include a client. Confirm quantity, unit cost, total, payment option, payment method when paying now, reference, and serialized units. The receipt produces stock movement and can produce supplier and finance effects.$$),
    ('41000000-0000-0000-0000-000000000018', 'Inventory supplier and client trade-in receipts', 'inventory', 2,
     'Client trade-in receipt',
     $$A client trade-in receipt requires an active client and must omit supplierId. It records that inventory was acquired from the client rather than a supplier. Archived clients cannot sell products to the shop. Verify the client, product identity, condition, acquisition price, and payment treatment before confirming.$$),

    ('41000000-0000-0000-0000-000000000019', 'Inventory receipt payment finance and idempotency', 'inventory', 0,
     'Payment options',
     $$Receipt paymentOption is FULL, PARTIAL, or LATER. FULL requires paidAmount equal to total cost. PARTIAL requires paidAmount greater than zero and lower than total. LATER requires paidAmount zero. Amounts cannot be negative or exceed total, and paymentMethod is required when money is paid now.$$),
    ('41000000-0000-0000-0000-000000000019', 'Inventory receipt payment finance and idempotency', 'inventory', 1,
     'Inventory and finance results',
     $$A successful receipt updates stock and records a purchase receipt movement. Depending on counterparty and payment, it can create payable or other linked finance work. Inventory asset maps to account 1200 in the configured defaults. Review the response ledger and finance summaries; a finance status can be skipped when no finance request is applicable.$$),
    ('41000000-0000-0000-0000-000000000019', 'Inventory receipt payment finance and idempotency', 'inventory', 2,
     'Receipt duplicate protection',
     $$The idempotency key and payload hash protect product receipts. Replaying the same completed request returns its saved response, while using the same key with changed data returns IDEMPOTENCY_KEY_PAYLOAD_CONFLICT. After an uncertain response, inspect product quantity, serialized units, purchase history, and finance result before creating another receipt.$$),

    ('41000000-0000-0000-0000-000000000020', 'Receiving serialized and IMEI inventory', 'inventory', 0,
     'Serialized unit count',
     $$serializedUnits are accepted only for SERIAL or IMEI products, and their count must equal receipt.quantity; otherwise the server returns SERIALIZED_UNIT_COUNT_MISMATCH. Each SERIAL unit needs serialNumber; each IMEI unit needs a valid 15-digit imei. Duplicate identifiers inside one request return SERIALIZED_UNIT_DUPLICATE_IN_REQUEST.$$),
    ('41000000-0000-0000-0000-000000000020', 'Receiving serialized and IMEI inventory', 'inventory', 1,
     'Existing identifiers and restock',
     $$An identifier already active in inventory cannot be received as a new physical unit. The server distinguishes duplicate, product mismatch, active duplicate, and permitted restock state checks. Sold, returned, damaged, or under-repair history must be resolved through the intended lifecycle; do not change spelling or add spaces to evade uniqueness.$$),
    ('41000000-0000-0000-0000-000000000020', 'Receiving serialized and IMEI inventory', 'inventory', 2,
     'Acquisition traceability',
     $$Each serialized unit records product, branch, identifier, condition, acquisition cost, source party type and identifier, receipt reference, and AVAILABLE state when newly received. A STOCK_IN movement links the unit to the product receipt. Use this evidence to investigate margin, supplier, client trade-in, and later sale history.$$),

    ('41000000-0000-0000-0000-000000000021', 'Serialized inventory lookup transfer and correction', 'inventory', 0,
     'Lookup and availability',
     $$Use Serialized Scan with company, branch, and scan code to locate an exact unit. Serialized Units lists a product's units and can filter by unit status. Serialized Availability summarizes available units. Stock Movements traces the product, while Serialized Unit Movements traces one productUnitId.$$),
    ('41000000-0000-0000-0000-000000000021', 'Serialized inventory lookup transfer and correction', 'inventory', 1,
     'Transfers',
     $$Transfer Serialized Units moves explicitly selected units through the supported branch transfer workflow. Confirm source branch, destination branch, product, productUnitIds, current statuses, and permissions. A transfer is not an aggregate quantity adjustment and should preserve the identifier and movement history.$$),
    ('41000000-0000-0000-0000-000000000021', 'Serialized inventory lookup transfer and correction', 'inventory', 2,
     'Identifier and condition correction',
     $$Use the identifier update endpoint for an authorized correction to the serial or IMEI and the condition-correction endpoint for NEW or USED corrections. These are audit-sensitive actions. Verify the physical identifier, avoid collisions with existing units, include the supported reason, and confirm the unit movement or audit record after saving.$$),

    ('41000000-0000-0000-0000-000000000022', 'Inventory quantity adjustments', 'inventory', 0,
     'Allowed adjustment reasons',
     $$Inventory adjustment is for quantity-tracked products. quantityDelta must be a non-zero integer. Supported reasons include the configured adjustment reason set such as FOUND_STOCK and SHRINKAGE. FOUND_STOCK must increase stock and SHRINKAGE must decrease it; a direction mismatch is rejected.$$),
    ('41000000-0000-0000-0000-000000000022', 'Inventory quantity adjustments', 'inventory', 1,
     'Reserved quantity protection',
     $$An adjustment cannot make quantity on hand lower than reserved quantity. The interface returns RESERVED_QUANTITY_CONFLICT when the proposed result violates reservations. Reload current stock and reservations, investigate the source, and choose the correct delta; do not clear legitimate reservations to force a correction.$$),
    ('41000000-0000-0000-0000-000000000022', 'Inventory quantity adjustments', 'inventory', 2,
     'Idempotency and serialized restriction',
     $$Every adjustment uses a unique idempotency key and records company, branch, product, delta, reason, and note. Serialized products require a unit-specific workflow and are blocked from aggregate adjustment. Use exact-unit status, transfer, identifier, condition, damage, return, or supported correction tools instead.$$),

    ('41000000-0000-0000-0000-000000000023', 'Inventory damage and reversal', 'inventory', 0,
     'Recording damage',
     $$Damage entry for the current workspace supports quantity-tracked inventory. Quantity must be a positive integer and cannot exceed available quantity. Enter the product, quantity, reason, damagedBy when relevant, liability amount when supported, branch, and idempotency key. SERIAL or IMEI products are blocked from this aggregate damage path.$$),
    ('41000000-0000-0000-0000-000000000023', 'Inventory damage and reversal', 'inventory', 1,
     'Accounting and inventory effect',
     $$A posted damage document reduces eligible stock through an auditable transaction and can create finance posting based on configured mappings. Default accounts include inventory damage expense 6500 and write-off expense 6510. Verify the resulting stock movement and posting status instead of editing the product quantity directly.$$),
    ('41000000-0000-0000-0000-000000000023', 'Inventory damage and reversal', 'inventory', 2,
     'Reversing an incorrect damage',
     $$Use the dedicated damage reversal endpoint with its own idempotency key and reason. A reversal preserves the original damage evidence and creates the compensating result. Do not hard-delete or hide a posted damage record; the legacy hard-delete writer is gated and can return INVENTORY_LEGACY_WRITER_DISABLED.$$),

    ('41000000-0000-0000-0000-000000000024', 'Inventory supplier returns', 'inventory', 0,
     'Return prerequisites',
     $$The workspace supplier return is enabled only when inventory.allowSupplierReturns is true and the user has the required inventory action permission. The product needs a supplier, return quantity must be a positive integer, and the remaining on-hand quantity cannot fall below reserved quantity.$$),
    ('41000000-0000-0000-0000-000000000024', 'Inventory supplier returns', 'inventory', 1,
     'Serialized restriction',
     $$The aggregate supplier-return action supports QUANTITY tracking. SERIAL and IMEI returns must identify exact units, and the current aggregate drawer explicitly blocks them with serialized-unit guidance. Do not convert tracking type or submit a generic quantity return for serialized stock.$$),
    ('41000000-0000-0000-0000-000000000024', 'Inventory supplier returns', 'inventory', 2,
     'Posting and replay safety',
     $$Confirm supplier, product, quantity, acquisition cost context, reason or note, branch, and idempotency key. The return removes eligible inventory and can create supplier credit and finance effects. A same-payload replay returns the existing response; after uncertainty, inspect inventory movement and supplier statement before retrying.$$),

    ('41000000-0000-0000-0000-000000000025', 'Inventory history analysis audit and investigation', 'inventory', 0,
     'Analysis filters',
     $$Inventory Analysis defaults to the current month and movement types ADD, SOLD, BOUNCE_BACK, and ADJUSTMENT, sorted by movement time descending with page size 50. It can filter date, movement types, business line, template, supplier, product, and stock impact. Select a longer date range when tracing older receipts or sales.$$),
    ('41000000-0000-0000-0000-000000000025', 'Inventory history analysis audit and investigation', 'inventory', 1,
     'Product and unit history',
     $$Use Stock Movements for product-level quantity changes, Serialized Unit Movements for one unit, and Purchase History for acquisition evidence. Correlate movement type, reference type and identifier, actor, timestamp, quantity before and after, supplier or client source, and related order or receipt.$$),
    ('41000000-0000-0000-0000-000000000025', 'Inventory history analysis audit and investigation', 'inventory', 2,
     'Audit search export and AI analysis',
     $$Inventory Audit provides filtered search, Excel and PDF export, and an AI analysis endpoint for authorized users. The analysis operates on the same filtered evidence and can flag issues such as sampled negative closing quantities that need reconciliation. AI observations guide investigation; source movements and documents remain authoritative.$$),

    ('41000000-0000-0000-0000-000000000026', 'Inventory low stock and branch settings', 'inventory', 0,
     'Low-stock calculation',
     $$inventory.lowStockThreshold defaults to 5. A quantity-tracked item is low stock when its available quantity is at or below that threshold. inventory.includeOutOfStockInLowStock defaults true, so zero quantity can be included. inventory.excludeSerializedFromLowStock defaults true, preventing aggregate low-stock treatment of serialized products.$$),
    ('41000000-0000-0000-0000-000000000026', 'Inventory low stock and branch settings', 'inventory', 1,
     'Other inventory defaults',
     $$inventory.lowStockCriticalCount defaults to 10, inventory.defaultBrowsePageSize to 25, inventory.defaultBrowseSort to updatedAt:desc, inventory.showSerializedUnitRows to true, inventory.allowSupplierReturns to true, and inventory.auditDefaultLowStockOnly to false. These settings are resolved for the active branch.$$),
    ('41000000-0000-0000-0000-000000000026', 'Inventory low stock and branch settings', 'inventory', 2,
     'Troubleshooting low stock',
     $$If low-stock totals look wrong, confirm the branch, threshold, out-of-stock inclusion, serialized exclusion, unit states, and reservations. Serialized availability is counted from AVAILABLE unit records when present. Changing branch settings affects presentation and classification, not historical movement evidence.$$),

    ('41000000-0000-0000-0000-000000000027', 'Bulk product import preparation and modes', 'inventory', 0,
     'Template and file preparation',
     $$Download the current product import template and keep its headers. Prepare a CSV with product identity, category, unit, pricing, quantity, supplier, tracking and identifier fields, condition, business line, and supported attributes. Quoted fields must be closed correctly; malformed CSV can return CSV_READ_FAILED or CSV_QUOTE_UNCLOSED.$$),
    ('41000000-0000-0000-0000-000000000027', 'Bulk product import preparation and modes', 'inventory', 1,
     'Import modes and permissions',
     $$ADD_ONLY requires inventory.item.create, UPDATE_ONLY requires inventory.item.edit, and UPSERT requires both create and edit. ADD_ONLY inserts new products or can receive stock into a matched serialized product under supported rules. UPDATE_ONLY needs a matched existing product. An unsupported mode returns IMPORT_MODE_INVALID.$$),
    ('41000000-0000-0000-0000-000000000027', 'Bulk product import preparation and modes', 'inventory', 2,
     'Staged workflow',
     $$Upload to Validate first. The system stores a batch and staged rows, then exposes rows, history, summary, original file download, and errors.csv. Validation does not apply products. Confirmation is a separate step and only accepts a batch in VALIDATED or VALIDATED_WITH_ERRORS state for the same branch; otherwise it returns IMPORT_BATCH_NOT_READY.$$),

    ('41000000-0000-0000-0000-000000000028', 'Bulk product import validation and serialized rows', 'inventory', 0,
     'General row validation',
     $$Rows can be VALID, WARNING, INVALID, or DUPLICATE. Checks include required values, numeric and integer formats, category and lookup existence, NEW or USED product state, duplicate SKU and barcode within the file, existing product matching, unit compatibility, and invalid prices. Correct invalid and duplicate rows before confirmation.$$),
    ('41000000-0000-0000-0000-000000000028', 'Bulk product import validation and serialized rows', 'inventory', 1,
     'Serialized import rules',
     $$A unit code IMEI or SERIAL establishes serialized tracking; serial_required can establish SERIAL when appropriate. Every serialized row needs an identifier, and IMEI must be 15 digits. Identifier can fall back from barcode with a warning. The file rejects duplicate serialized identifiers and identifiers already in inventory.$$),
    ('41000000-0000-0000-0000-000000000028', 'Bulk product import validation and serialized rows', 'inventory', 2,
     'Serialized supplier cost and grouping',
     $$Serialized rows require supplier_name so stock can be received from the supplier. unit_cost must be numeric and non-negative. opening_stock_quantity is ignored for a serialized row because each row represents one exact unit. Compatible rows are grouped for create or receive processing, and conflicting group values produce warnings.$$),

    ('41000000-0000-0000-0000-000000000029', 'Bulk product import confirmation results and recovery', 'inventory', 0,
     'Confirming a validated batch',
     $$Confirm only after reviewing the summary and row actions. The batch must belong to the selected branch and be ready. Serialized INSERT and RECEIVE rows are grouped into product receipt requests so identifier count, supplier, cost, inventory movement, and finance behavior use the normal receipt service and deterministic idempotency keys.$$),
    ('41000000-0000-0000-0000-000000000029', 'Bulk product import confirmation results and recovery', 'inventory', 1,
     'Payment during import',
     $$Import confirmation supports supplier receipt payment option FULL or LATER. FULL needs the required payment method and creates the applicable paid-now behavior; LATER records no immediate payment. Invalid payment option returns IMPORT_PAYMENT_OPTION_INVALID and a missing method for immediate payment returns IMPORT_PAYMENT_METHOD_REQUIRED.$$),
    ('41000000-0000-0000-0000-000000000029', 'Bulk product import confirmation results and recovery', 'inventory', 2,
     'Final states and error reports',
     $$The final status is IMPORTED when all eligible rows succeed or IMPORTED_WITH_ERRORS when some rows fail. Row and group failures are recorded instead of being hidden. Use batch summary, filtered rows, history, and errors.csv to resolve failures. Do not upload the same file repeatedly before checking the existing batch result.$$),

    ('41000000-0000-0000-0000-000000000030', 'Dynamic pricing metrics and recommendations', 'inventory', 0,
     'Pricing metrics',
     $$Dynamic Pricing Engine analyzes branch inventory and sales signals such as cost, current retail and lowest price, margin, stock, sales velocity, days of cover, low stock, overstock, slow-moving, and dead-stock conditions. Confirm company, branch, date or analysis context, and inventory.pricing.view before interpreting metrics.$$),
    ('41000000-0000-0000-0000-000000000030', 'Dynamic pricing metrics and recommendations', 'inventory', 1,
     'Recommendation preview',
     $$inventory.pricing.recommendation.run allows recommendations. A recommendation proposes a price based on matched policy, target and minimum margins, inventory signals, maximum movement limits, and rounding. It does not change the product price. Review current cost, old price, recommended price, reason, margin, and warnings.$$),
    ('41000000-0000-0000-0000-000000000030', 'Dynamic pricing metrics and recommendations', 'inventory', 2,
     'Manual price adjustment',
     $$Use adjustment preview before creating a price batch. Capabilities separate inventory.pricing.adjustment.preview and inventory.pricing.adjustment.create. Saving an adjustment creates governed work; it is not equivalent to applying it. Cost fields remain hidden without inventory.pricing.cost.read.$$),

    ('41000000-0000-0000-0000-000000000031', 'Dynamic pricing batches policies and inflation', 'inventory', 0,
     'Batch lifecycle',
     $$A price adjustment batch can be created, submitted, approved or rejected, applied, or cancelled according to status and capability. Submit requires inventory.pricing.adjustment.submit, approval requires inventory.pricing.adjustment.approve, and application requires inventory.pricing.adjustment.apply. Maker-checker policy can prevent the maker from approving their own batch.$$),
    ('41000000-0000-0000-0000-000000000031', 'Dynamic pricing batches policies and inflation', 'inventory', 1,
     'Pricing policy controls',
     $$inventory.pricing.policy.manage controls policy changes. A policy can be company-, branch-, category-, product-, or pricing-policy scoped and defines target and minimum margin, rounding mode, max percentage and amount increases or decreases, low-stock and overstock days cover, slow and dead stock days, below-cost permission, approval requirement, maker-checker, auto-apply permission, and maximum auto-apply delta.$$),
    ('41000000-0000-0000-0000-000000000031', 'Dynamic pricing batches policies and inflation', 'inventory', 2,
     'Inflation bulk update',
     $$Inflation adjustment can scope matching products, choose rate, mode and direction, choose buying, retail, and lowest price fields, and set an optional rounding factor. Preview and confirm scope before Apply Bulk Update because application directly changes matching database prices. It requires price-application authority and creates auditable results.$$),

    ('41000000-0000-0000-0000-000000000032', 'Inventory permissions concurrency and safe recovery', 'inventory', 0,
     'Core inventory capabilities',
     $$Core capabilities include inventory.item.read, inventory.item.create, inventory.item.edit, and inventory.adjustment.create or inventory.adjustment.edit where configured. Pricing has separate view, cost-read, recommendation, preview, create, submit, approve, apply, auto-apply, policy-manage, and audit-read capabilities. The screen hides or disables actions the effective user scope does not allow.$$),
    ('41000000-0000-0000-0000-000000000032', 'Inventory permissions concurrency and safe recovery', 'inventory', 1,
     'Legacy writer protection',
     $$Generic legacy inventory transactions, standalone serialized stock-in, and damage hard-delete can be disabled by InventoryLegacyWriterGate. INVENTORY_LEGACY_WRITER_DISABLED means the operation must use the supported receipt, adjustment, damage, reversal, return, or serialized workflow. Do not enable a legacy writer merely to bypass validation.$$),
    ('41000000-0000-0000-0000-000000000032', 'Inventory permissions concurrency and safe recovery', 'inventory', 2,
     'Discrepancy recovery',
     $$For unexpected stock, check branch, product and unit identifiers, on-hand and reserved quantity, unit status, receipts, transfers, sales, bounced-back records, adjustments, damage and reversal, supplier returns, import history, and finance posting references. Reload after a concurrency error and use a new idempotency key only for a genuinely new request.$$),

    ('41000000-0000-0000-0000-000000000033', 'POS and Inventory Arabic English terminology', 'help', 0,
     'POS terms in Arabic and English',
     $$Point of sale and Inventory terms: نقطة البيع = Point of Sale or POS; سلة = cart; دفع = payment; نقدي = cash; آجل = credit; خصم = discount; عرض = offer; نقاط الولاء = loyalty points; وردية = shift; فتح الوردية = open shift; إغلاق الوردية = close shift; تسوية النقدية = cash reconciliation; إيصال = receipt; طابعة = printer; بيع بدون اتصال = offline sale.$$),
    ('41000000-0000-0000-0000-000000000033', 'POS and Inventory Arabic English terminology', 'help', 1,
     'Inventory terms in Arabic and English',
     $$المخزون = inventory; صنف or منتج = item or product; كمية متاحة = available quantity; كمية محجوزة = reserved quantity; مخزون منخفض = low stock; نفد المخزون = out of stock; استلام بضاعة = product receipt; مورد = supplier; مرتجع مورد = supplier return; تسوية مخزون = inventory adjustment; تالف = damaged stock; عكس التلف = damage reversal.$$),
    ('41000000-0000-0000-0000-000000000033', 'POS and Inventory Arabic English terminology', 'help', 2,
     'Tracking import and pricing terms',
     $$باركود = barcode; رقم تسلسلي or سيريال = serial number; رقم IMEI = IMEI; وحدة متسلسلة = serialized unit; تحويل مخزون = inventory transfer; سجل حركة المخزون = stock movement history; استيراد جماعي = bulk import; تحقق = validate; تأكيد الاستيراد = confirm import; تسعير ديناميكي = dynamic pricing; توصية سعر = price recommendation; اعتماد = approval; تطبيق الأسعار = apply prices.$$);

INSERT INTO public.ai_document
    (id, company_id, title, document_type, module, language, content,
     metadata_json, active, created_at, updated_at)
SELECT
    document_id,
    NULL,
    title,
    'HELP_ARTICLE',
    module,
    'en',
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    '{"seed":"rag-pos-inventory-detail-v1","source":"implemented-pos-inventory-workflows"}',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_pos_inventory_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    document_type = EXCLUDED.document_type,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json,
    active = true,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_document_chunk
    (id, document_id, company_id, title, module, language, chunk_index,
     content, metadata_json, created_at)
SELECT
    md5('legacy-pos-inventory-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    title,
    module,
    'en',
    chunk_index,
    heading || E'\n' || content,
    '{"seed":"rag-pos-inventory-detail-v1","retrieval":"keyword"}',
    CURRENT_TIMESTAMP
FROM vls_ai_pos_inventory_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    title = EXCLUDED.title,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json;

INSERT INTO public.ai_knowledge_document
    (id, company_id, branch_id, module, language, document_type, title,
     source_type, source_uri, content_hash, raw_content, normalized_content,
     status, metadata_json, created_at, updated_at)
SELECT
    document_id,
    NULL,
    NULL,
    module,
    'en',
    'HELP_ARTICLE',
    title,
    'APPLICATION',
    'valueinsoft://help/pos-inventory/' || replace(lower(title), ' ', '-'),
    md5(string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index)),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    'ACTIVE',
    '{"seed":"rag-pos-inventory-detail-v1","source":"implemented-pos-inventory-workflows"}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_pos_inventory_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    document_type = EXCLUDED.document_type,
    title = EXCLUDED.title,
    source_type = EXCLUDED.source_type,
    source_uri = EXCLUDED.source_uri,
    content_hash = EXCLUDED.content_hash,
    raw_content = EXCLUDED.raw_content,
    normalized_content = EXCLUDED.normalized_content,
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_knowledge_chunk
    (id, document_id, company_id, branch_id, module, language, chunk_index,
     heading, content, token_count, embedding, embedding_model, status,
     metadata_json, created_at)
SELECT
    md5('knowledge-pos-inventory-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    NULL,
    module,
    'en',
    chunk_index,
    heading,
    content,
    cardinality(regexp_split_to_array(btrim(content), E'\\s+')),
    NULL,
    'keyword-fallback',
    'ACTIVE',
    '{"seed":"rag-pos-inventory-detail-v1","embeddingStatus":"pending-real-provider"}'::jsonb,
    CURRENT_TIMESTAMP
FROM vls_ai_pos_inventory_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    branch_id = EXCLUDED.branch_id,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    heading = EXCLUDED.heading,
    content = EXCLUDED.content,
    token_count = EXCLUDED.token_count,
    embedding = NULL,
    embedding_model = 'keyword-fallback',
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json;

DROP TABLE vls_ai_pos_inventory_detail_chunk;
