-- ==========================================================
-- V166 - Detailed Dashboards and Access RAG knowledge
-- ==========================================================
-- Source-of-truth help content derived from implemented frontend
-- routes, dashboard providers, authorization services, access graph,
-- company insights, capabilities, scopes, and lifecycle states.
-- The same corpus is written to the legacy and semantic RAG stores.
-- Keyword retrieval is immediately available; embeddings remain pending
-- until a real embedding provider is configured.
-- ==========================================================

CREATE TEMP TABLE vls_ai_dashboards_access_detail_chunk (
    document_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    module VARCHAR(100) NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (document_id, chunk_index)
);

INSERT INTO vls_ai_dashboards_access_detail_chunk
    (document_id, title, module, chunk_index, heading, content)
VALUES
    ('42000000-0000-0000-0000-000000000001', 'Dashboard types navigation and purpose', 'dashboard', 0,
     'Available dashboards',
     $$ValueInSoft has several dashboard experiences. The branch dashboard summarizes the selected branch; the company dashboard aggregates branches; Company Smart Insights explains company-wide performance, inventory, and activity signals. Finance, Inventory, and Attendance also have specialized dashboards for their own operational data.$$),
    ('42000000-0000-0000-0000-000000000001', 'Dashboard types navigation and purpose', 'dashboard', 1,
     'Choose the correct scope',
     $$Use the branch dashboard for today's branch KPIs, alerts, inventory health, profit periods, and drill-downs. Use the company dashboard to compare and aggregate branches. Use a specialized module dashboard when the question needs journal-based finance, product-level inventory, or employee attendance detail.$$),
    ('42000000-0000-0000-0000-000000000001', 'Dashboard types navigation and purpose', 'dashboard', 2,
     'Dashboards are summaries',
     $$Dashboard cards are entry points, not substitutes for source records. A sales total should be verified in sales or finance reports, low stock in Inventory, receivables in Obligations, and attendance exceptions in the attendance log. Drill down before correcting business data.$$),

    ('42000000-0000-0000-0000-000000000002', 'Opening the branch dashboard', 'dashboard', 0,
     'Context prerequisites',
     $$The branch dashboard needs an authenticated session, a company, and an active selected branch. The request is scoped by company, branch, local business date, period TODAY, and locale. If a wrong branch is selected, the figures can be valid but belong to a different branch.$$),
    ('42000000-0000-0000-0000-000000000002', 'Opening the branch dashboard', 'dashboard', 1,
     'Dashboard permission',
     $$The backend endpoint POST /api/dashboard/branch-summary requires dashboard.home.view and verifies that the user belongs to the company and can access the requested branch. Finance drill-downs additionally need finance.report.read. Seeing a navigation entry does not bypass the endpoint capability check.$$),
    ('42000000-0000-0000-0000-000000000002', 'Opening the branch dashboard', 'dashboard', 2,
     'Loading and refresh behavior',
     $$Dashboard data is cached briefly and refreshed when the page regains focus or the network reconnects. The interface can keep the last successful data while a refresh runs. Use Refresh or reopen the page when recent transactions are not yet visible, but do not post duplicates to make a card change.$$),

    ('42000000-0000-0000-0000-000000000003', 'Branch dashboard KPI definitions', 'dashboard', 0,
     'Sales orders and average order',
     $$Today Sales is the sum of today's branch sales. Orders is the count of today's orders. Average Order Value is today sales divided by order count and is zero when there are no orders. These values come from server-side daily KPI queries.$$),
    ('42000000-0000-0000-0000-000000000003', 'Branch dashboard KPI definitions', 'dashboard', 1,
     'Gross profit and new clients',
     $$Gross Profit is the daily income or gross-profit result returned by the sales KPI source; it is not the same as cash collected or final accounting net income. New Clients counts clients created for the branch on the selected day.$$),
    ('42000000-0000-0000-0000-000000000003', 'Branch dashboard KPI definitions', 'dashboard', 2,
     'Cash on hand limitation',
     $$The branch-summary KPI provider currently sets Cash on Hand to 0 and its comparison to stable 0. Do not use that card as cash reconciliation evidence. Use the active shift reconciliation, cash movements, posted finance records, and counted cash for an authoritative cash position.$$),

    ('42000000-0000-0000-0000-000000000004', 'Dashboard comparisons dates and freshness', 'dashboard', 0,
     'Previous-day comparisons',
     $$Sales, gross profit, orders, average order, and new-client percentages compare the selected business day with the immediately previous calendar day. When the previous value is zero, a positive current value is represented as 100 percent and two zero values as 0 percent.$$),
    ('42000000-0000-0000-0000-000000000004', 'Dashboard comparisons dates and freshness', 'dashboard', 1,
     'Do not confuse date windows',
     $$The KPI strip is daily, top categories use the last 30 days, recently sold and moved inventory use 7 days, and dead stock uses a 30-day no-sale window. Week, month, and year finance summaries have their own period boundaries. Always name the card and period when comparing figures.$$),
    ('42000000-0000-0000-0000-000000000004', 'Dashboard comparisons dates and freshness', 'dashboard', 2,
     'Empty data is not invented data',
     $$When a chart or section has no records, the dashboard shows zeros, an empty state, or a warning. It must not fabricate sales or operational values. Confirm the selected date, branch, filters, posting state, and whether the source section loaded before treating zero as a real business result.$$),

    ('42000000-0000-0000-0000-000000000005', 'Branch dashboard alerts and severity', 'dashboard', 0,
     'Inventory alerts',
     $$Low Stock counts products at or below inventory.lowStockThreshold using branch-effective settings. inventory.excludeSerializedFromLowStock and inventory.includeOutOfStockInLowStock change the count. The low-stock alert becomes critical when its count reaches inventory.lowStockCriticalCount. Out of Stock separately reports products whose branch balance is zero or less.$$),
    ('42000000-0000-0000-0000-000000000005', 'Branch dashboard alerts and severity', 'dashboard', 1,
     'Operational and finance alerts',
     $$The alert hub can include pending or failed finance posting work, expenses awaiting action, an unusually long open shift, current-shift returns, client trade-in or purchase activity, and weekly receivables. Only alerts with a meaningful positive count are normally displayed.$$),
    ('42000000-0000-0000-0000-000000000005', 'Branch dashboard alerts and severity', 'dashboard', 2,
     'Use the alert action',
     $$Alert severity indicates attention, not automatic proof of an error. Open the alert's authorized target, keep the branch and filter parameters, and inspect source records. A hidden action usually means the target capability is missing even when the alert itself is visible.$$),

    ('42000000-0000-0000-0000-000000000006', 'Dashboard inventory health metrics', 'inventory', 0,
     'Inventory value and availability',
     $$Inventory Value uses acquisition cost for available serialized units and product buying price multiplied by quantity for quantity-tracked stock. Stock Availability is the percentage of stocked product balances above zero in the selected branch. Cost-sensitive results should be handled according to inventory pricing permissions.$$),
    ('42000000-0000-0000-0000-000000000006', 'Dashboard inventory health metrics', 'inventory', 1,
     'Dead stock and turnover',
     $$Dead Stock Percentage is the share of products with positive stock that have no sale or no sale within the last 30 days. Turnover Rate annualizes 30-day cost of goods sold by multiplying it by 12 and dividing by current inventory value; it is zero when inventory value is not positive.$$),
    ('42000000-0000-0000-0000-000000000006', 'Dashboard inventory health metrics', 'inventory', 2,
     'Recent inventory counts',
     $$Total Items sums branch quantity balances. New Items counts products created or, as a fallback, updated in the last 7 days. Recently Sold counts distinct products sold in 7 days, while Recently Moved counts distinct products with non-sale inventory movements in 7 days.$$),

    ('42000000-0000-0000-0000-000000000007', 'Dashboard finance snapshot and receivables', 'finance', 0,
     'Week month and year profit',
     $$The finance snapshot displays revenue, gross profit, expenses, net profit, and margin for week, month, and year windows. Net profit is gross profit minus expenses for the supplied summary. Margin is recalculated from the aggregated monetary values rather than averaged across branches.$$),
    ('42000000-0000-0000-0000-000000000007', 'Dashboard finance snapshot and receivables', 'finance', 1,
     'Weekly receivables',
     $$The weekly receivables notice appears only when the user has finance.report.read and outstanding receivables are positive. It shows party counts and totals grouped by currency as of today. Open Obligations Report to inspect the customers, due items, settlements, and remaining balances.$$),
    ('42000000-0000-0000-0000-000000000007', 'Dashboard finance snapshot and receivables', 'finance', 2,
     'Accounting source of truth',
     $$Dashboard profit and receivable summaries are operational overviews. Posted journals, fiscal-period reports, ledgers, and open-item records remain the accounting source of truth. Pending posting requests can explain why a recent sale or expense has not reached an accounting report.$$),

    ('42000000-0000-0000-0000-000000000008', 'Dashboard charts and payment methods', 'dashboard', 0,
     'Daily performance chart',
     $$The branch daily-performance chart presents the loaded week, arranged Saturday through Friday where data is available. It can show sales and gross profit. The detailed sales chart can switch between current-month and current-year views and refreshes after focus, reconnect, or visibility changes.$$),
    ('42000000-0000-0000-0000-000000000008', 'Dashboard charts and payment methods', 'dashboard', 1,
     'Client and payment charts',
     $$Client Trend shows a six-month client series. Payment Methods groups the loaded sales payment distribution. A missing payment slice can mean there were no matching transactions or that the chart section failed; check section status and source sales before interpreting it.$$),
    ('42000000-0000-0000-0000-000000000008', 'Dashboard charts and payment methods', 'dashboard', 2,
     'Reading chart filters',
     $$Chart period and branch selection are local presentation filters over server data. A company chart can sum only selected branches. If no branch is selected, the application shows an explicit no-selection state rather than silently including every branch.$$),

    ('42000000-0000-0000-0000-000000000009', 'Dashboard top performers', 'dashboard', 0,
     'Top categories',
     $$The implemented server provider ranks the top five product categories by sales revenue over the last 30 days for the selected branch. Within each category it loads the top three product subcategories by revenue.$$),
    ('42000000-0000-0000-0000-000000000009', 'Dashboard top performers', 'dashboard', 1,
     'Current provider limitations',
     $$The branch-summary provider currently returns empty Products, Customers, and Staff performer lists; Categories are the implemented populated performer dataset. An empty list in those three areas is not evidence that no product, customer, or employee performed.$$),
    ('42000000-0000-0000-0000-000000000009', 'Dashboard top performers', 'dashboard', 2,
     'Company category aggregation',
     $$The company dashboard merges category and subcategory sales from successfully loaded branches and sorts the combined values. Because failed branches are excluded, use the loaded and failed branch counters before calling the ranking company-wide.$$),

    ('42000000-0000-0000-0000-000000000010', 'Dashboard partial loading warnings and recovery', 'dashboard', 0,
     'Independent sections',
     $$Branch dashboard providers load KPI, charts, top performers, alerts, profit summary, and inventory health independently. sectionStatus and warnings identify partial failures. One failed section should not discard valid data from the others.$$),
    ('42000000-0000-0000-0000-000000000010', 'Dashboard partial loading warnings and recovery', 'dashboard', 1,
     'Fallback data',
     $$The frontend can build limited KPI or alert fallback data from other available sales, client, inventory, and finance sources when summary sections are missing. Fallback is clearly narrower than a complete branch summary and must not be presented as a full successful dashboard load.$$),
    ('42000000-0000-0000-0000-000000000010', 'Dashboard partial loading warnings and recovery', 'dashboard', 2,
     'Recovery checklist',
     $$For incomplete data, note the failed section, refresh once, verify backend connectivity, company and branch, capability, date, and whether the relevant tenant tables exist. Preserve the warning and request timestamp for support. Do not repair business records merely because one visualization failed.$$),

    ('42000000-0000-0000-0000-000000000011', 'Branch dashboard Smart Insights', 'dashboard', 0,
     'Generation and cache',
     $$Branch Smart Insights are requested after dashboard business data loads. Generated insight results can be cached for seven days; Run or manual refresh requests a new calculation. The underlying dashboard records remain the evidence used to verify an insight.$$),
    ('42000000-0000-0000-0000-000000000011', 'Branch dashboard Smart Insights', 'dashboard', 1,
     'Real model and grounded help',
     $$The main AI chat answer is generated by the configured real model and grounded with retrieved RAG chunks; knowledge documents are context, not predefined final answers. If relevant authorized knowledge cannot be retrieved, the chat reports that it lacks matching knowledge rather than presenting an ungrounded canned response.$$),
    ('42000000-0000-0000-0000-000000000011', 'Branch dashboard Smart Insights', 'dashboard', 2,
     'Insight safety',
     $$An AI insight is an explanation or recommendation, not an automatic posting, stock adjustment, or permission change. Validate important claims against the visible KPI, Inventory, Sales, and Finance records. An action button is shown only when the user can access its destination.$$),

    ('42000000-0000-0000-0000-000000000012', 'Dashboard drill-down permissions', 'access', 0,
     'Finance destinations',
     $$Finance Reports and Sales reporting drill-downs require finance.report.read. Expense destinations accept applicable finance.entry.read, finance.entry.create, or finance.entry.edit access according to the registered view. Weekly receivables opens the Obligations Report only for an authorized user.$$),
    ('42000000-0000-0000-0000-000000000012', 'Dashboard drill-down permissions', 'access', 1,
     'Inventory and POS destinations',
     $$Inventory alerts and health actions require inventory.item.read for the Inventory view. Point of Sale actions require applicable pos.sale.create or pos.sale.read access. Query parameters such as chip, productId, shiftId, and date range narrow the target but do not grant access.$$),
    ('42000000-0000-0000-0000-000000000012', 'Dashboard drill-down permissions', 'access', 2,
     'Preserved context',
     $$Drill-down paths carry the authenticated user, company, branch name, target view, and supported filters. The backend independently resolves company and branch ownership. Editing a URL cannot expand the caller's tenant, branch, module, or capability scope.$$),

    ('42000000-0000-0000-0000-000000000013', 'Company dashboard access and branch loading', 'dashboard', 0,
     'Opening company dashboard',
     $$The company dashboard route is available to Owner or users with an applicable company.settings.read, company.settings.edit, users.account.read, or users.account.edit capability. It is company-scoped and requires an authenticated user with an existing company.$$),
    ('42000000-0000-0000-0000-000000000013', 'Company dashboard access and branch loading', 'dashboard', 1,
     'Branch fan-out',
     $$The page requests dashboard summaries for company branches concurrently. Each branch can succeed or fail independently. loadedBranches, failedBranches, and branchCount state how complete the company view is; no branches produces a specific empty message.$$),
    ('42000000-0000-0000-0000-000000000013', 'Company dashboard access and branch loading', 'dashboard', 2,
     'Refresh',
     $$Company Refresh reloads dashboard summaries and associated sales and receivable information. Use it after new branch transactions or recovery from a partial failure. If a branch repeatedly fails, open that branch context and diagnose its dashboard endpoint and permissions.$$),

    ('42000000-0000-0000-0000-000000000014', 'Company dashboard aggregation rules', 'dashboard', 0,
     'Aggregated KPIs',
     $$Company Today Sales, Gross Profit, Orders, New Clients, and Cash on Hand sum successfully loaded branch values. Company Average Order Value is total sales divided by total orders, not an average of branch averages.$$),
    ('42000000-0000-0000-0000-000000000014', 'Company dashboard aggregation rules', 'dashboard', 1,
     'Inventory and finance aggregation',
     $$Inventory value, total items, and recent item counts are summed. Percentage and rate fields are averaged over loaded branches. Week, month, and year revenue, profit, and expense values are summed, while net margin is recalculated from the combined totals.$$),
    ('42000000-0000-0000-0000-000000000014', 'Company dashboard aggregation rules', 'dashboard', 2,
     'Partial-company qualification',
     $$Every company total depends on the set of loaded branches. When failedBranches is greater than zero, describe figures as totals for loaded branches, not the entire company. Retry failed branches before formal reporting.$$),

    ('42000000-0000-0000-0000-000000000015', 'Company dashboard charts branch table and receivables', 'dashboard', 0,
     'Branch comparison table',
     $$The company branch table is sorted by sales and shows branch load state, sales, gross profit, orders, average order value, new clients, and active alert count. Use it to identify a branch, then drill into source data rather than judging only from rank.$$),
    ('42000000-0000-0000-0000-000000000015', 'Company dashboard charts branch table and receivables', 'dashboard', 1,
     'Selectable sales chart',
     $$The wide sales chart supports month or year periods and branch selection, including select all and deselect. The chart sums the selected loaded branches client-side. Selection changes presentation only and do not change stored transactions.$$),
    ('42000000-0000-0000-0000-000000000015', 'Company dashboard charts branch table and receivables', 'dashboard', 2,
     'Company receivables',
     $$Weekly receivables are loaded per branch and combined by currency with a loaded-branch count. Different currencies stay separate and must not be numerically added without a defined conversion. Drill into Obligations to see party and open-item details.$$),

    ('42000000-0000-0000-0000-000000000016', 'Company Smart Insights dashboard', 'dashboard', 0,
     'Summary period and KPIs',
     $$Company Smart Insights defaults its KPI summary to the last 30 calendar days, from today minus 29 days through today. It shows total sales, gross profit, gross margin, orders, branch count, and active alert counts by severity. Summary dates affect the KPI trend; insight-card filters are separate.$$),
    ('42000000-0000-0000-0000-000000000016', 'Company Smart Insights dashboard', 'dashboard', 1,
     'Filters',
     $$Insight filters include severity CRITICAL, WARNING, or INFO; category PERFORMANCE, INVENTORY, or ACTIVITY; lifecycle status; type; branch; role; and date range where exposed. The API pages results and caps an effective page size at 100.$$),
    ('42000000-0000-0000-0000-000000000016', 'Company Smart Insights dashboard', 'dashboard', 2,
     'Insight content',
     $$A card can show localized title and description, incomplete-data warning, financial impact, affected branches, affected products, occurrence count, and contributing factors with percentage changes. Deep links can carry branch, product, inventory chip, and date parameters while still enforcing access.$$),

    ('42000000-0000-0000-0000-000000000017', 'Company insight rules lifecycle and actions', 'dashboard', 0,
     'Implemented insight types',
     $$Implemented types are COMPANY_WEEKLY_PERFORMANCE, LOW_PERFORMING_BRANCH, COMPANY_WIDE_LOW_STOCK, DEAD_STOCK_COMPANY_WIDE, and BRANCH_NO_ACTIVITY. They belong to Performance, Inventory, or Activity categories and are generated from deterministic company KPI and inventory snapshots.$$),
    ('42000000-0000-0000-0000-000000000017', 'Company insight rules lifecycle and actions', 'dashboard', 1,
     'Statuses',
     $$Insights begin in NEW and can be marked SEEN, DISMISSED, or RESOLVED. Status updates require company.insights.view and are tenant-checked. Dismissed or resolved insight behavior also uses the configured cooldown before an equivalent active signal should reappear.$$),
    ('42000000-0000-0000-0000-000000000017', 'Company insight rules lifecycle and actions', 'dashboard', 2,
     'Recalculate and backfill',
     $$Manual Recalculate aggregates roughly five weeks of trusted KPI snapshots and runs the engine for a target date; company.insights.admin is required. Historical Backfill also requires company.insights.admin. Reading insights requires company.insights.view, while updating settings requires company.insights.configure.$$),

    ('42000000-0000-0000-0000-000000000018', 'Company insight settings and thresholds', 'settings', 0,
     'Default thresholds',
     $$Defaults include 25 percent low-performing branch deviation, 7 critical stock-coverage days, 2 affected low-stock branches, 60 dead-stock no-sale days, 1000 minimum dead-stock value, 5 percent margin drop, and 15 percent material sales drop.$$),
    ('42000000-0000-0000-0000-000000000018', 'Company insight settings and thresholds', 'settings', 1,
     'Timing and volume controls',
     $$Defaults also include a 180-minute no-sales delay, 28 minimum comparison-history days, 30 new-branch grace days, 5 active insights per category, and a 72-hour cooldown. Currency defaults to EGP and timezone to Africa/Cairo when not otherwise configured.$$),
    ('42000000-0000-0000-0000-000000000018', 'Company insight settings and thresholds', 'settings', 2,
     'AI enrichment setting',
     $$AI enrichment is enabled by default but only runs when the global narrative service is enabled. Deterministic rules identify the signal; model narration enriches its explanation. Changing thresholds changes future evaluations and should be documented and tested against company policy.$$),

    ('42000000-0000-0000-0000-000000000019', 'Finance dashboard', 'finance', 0,
     'Scope and reports',
     $$The Finance Dashboard selects a fiscal period, current branch or all-branch scope, and currency. It loads Profit and Loss, Balance Sheet, Trial Balance, posting requests, recent journals, and up to six fiscal periods of profit-and-loss trend. Its report access is governed by finance.report.read and related finance capabilities.$$),
    ('42000000-0000-0000-0000-000000000019', 'Finance dashboard', 'finance', 1,
     'Finance KPIs and posting health',
     $$KPIs include revenue, expenses, net income, net margin, total assets, and period-over-period changes when a prior period exists. Posting health samples up to 100 requests and counts pending, failed, and processed records; use the posting-request screen for the complete queue.$$),
    ('42000000-0000-0000-0000-000000000019', 'Finance dashboard', 'finance', 2,
     'Finance AI insight label',
     $$Finance insight output identifies whether it came from the configured model, a cached model result, or explicitly labeled local rule fallback after an AI error. Posted journals and backend report APIs remain the source of truth. Refreshing insight narration does not alter journals.$$),

    ('42000000-0000-0000-0000-000000000020', 'Inventory dashboard workspace', 'inventory', 0,
     'Inventory dashboard scope',
     $$The Inventory workspace Dashboard uses the active company and branch and requires inventory.item.read. It summarizes stock and product health, while Browse, Quick Find, and Analysis provide item-level and movement-level evidence.$$),
    ('42000000-0000-0000-0000-000000000020', 'Inventory dashboard workspace', 'inventory', 1,
     'Low stock settings',
     $$Inventory dashboard interpretation must use effective branch settings such as low-stock threshold, serialized exclusion, out-of-stock inclusion, page size, and serialized-row visibility. A company default can be overridden by permitted branch configuration unless a higher policy locks it.$$),
    ('42000000-0000-0000-0000-000000000020', 'Inventory dashboard workspace', 'inventory', 2,
     'Drill to evidence',
     $$Use low-stock and out-of-stock chips to open filtered Browse results, exact barcode or serial search for a physical unit, and Analysis for movement history. Cost data and export actions can require capabilities beyond ordinary item read.$$),

    ('42000000-0000-0000-0000-000000000021', 'Attendance dashboard', 'attendance', 0,
     'Access and scope',
     $$The attendance dashboard route accepts attendance.report.view or attendance.report.company at the route layer. Branch report access shows one branch; users with company-report access can switch to company scope and select branches. A company and selected branch are required to enter the workspace.$$),
    ('42000000-0000-0000-0000-000000000021', 'Attendance dashboard', 'attendance', 1,
     'Daily metrics and filters',
     $$The selected date report summarizes active employees, present employees, active clock-ins, late arrivals, and worked minutes. The log shows clock-in, clock-out, work, breaks, lateness, overtime, and status. Search by employee or code and filter Present, Late, Absent, or Incomplete.$$),
    ('42000000-0000-0000-0000-000000000021', 'Attendance dashboard', 'attendance', 2,
     'Corrections',
     $$An authorized correction records action type CLOCK_IN, CLOCK_OUT, BREAK_START, or BREAK_END, corrected time, and a required reason up to 500 characters. Corrections are audited actions. Reload the report after saving and preserve the reason instead of deleting attendance evidence.$$),

    ('42000000-0000-0000-0000-000000000022', 'Dashboard troubleshooting checklist', 'help', 0,
     'Dashboard is hidden or denied',
     $$Check authentication, company existence, active branch, module availability, dashboard.home.view, and the target drill-down capability. For a company dashboard check company settings or user-account read or edit access. Read the denial reason: plan_locked, workspace_disabled, module_unavailable, access_denied, or prerequisite_unmet.$$),
    ('42000000-0000-0000-0000-000000000022', 'Dashboard troubleshooting checklist', 'help', 1,
     'Numbers look wrong',
     $$Confirm branch, date, period, currency, selected branches, loadedBranches versus failedBranches, and section warnings. Compare source sales, journals, open items, inventory movements, and attendance records. Remember that daily, 7-day, 30-day, fiscal-period, and company insight windows differ.$$),
    ('42000000-0000-0000-0000-000000000022', 'Dashboard troubleshooting checklist', 'help', 2,
     'Safe escalation',
     $$Refresh once and record the page, company, branch, date, filter, failed section, API error code, and approximate time. Do not share passwords, tokens, full customer financial data, or unnecessary identifiers. Do not create corrective transactions until the source mismatch is understood.$$),

    ('42000000-0000-0000-0000-000000000023', 'Authentication login and rate limiting', 'access', 0,
     'Signing in',
     $$POST /authenticate validates username and password and returns a JWT, base username, role, and passwordResetRequired state. Authentication is only the first boundary; company membership, branch membership, module availability, capability, and scope are checked separately for protected operations.$$),
    ('42000000-0000-0000-0000-000000000023', 'Authentication login and rate limiting', 'access', 1,
     'Login protection',
     $$Login failures are rate-limited for both normalized username and client IP. Defaults permit 5 failures in a rolling 300-second window and lock for 900 seconds; the API returns HTTP 429 with LOGIN_RATE_LIMITED. A successful login resets the tracked counters.$$),
    ('42000000-0000-0000-0000-000000000023', 'Authentication login and rate limiting', 'access', 2,
     'Operational limitation',
     $$The current rate-limit store is in-memory per backend instance. A multi-instance deployment needs a shared store such as Redis for consistent counters. Never weaken authorization or expose whether another tenant's username exists to troubleshoot login.$$),

    ('42000000-0000-0000-0000-000000000024', 'Session branch switching and default destination', 'access', 0,
     'Session data',
     $$The browser session stores the token, email, role, password-reset flag, company details, current branch, selected caches, shift state, and an effective configuration snapshot. Signing out clears the full session. Do not manually copy tokens between users or companies.$$),
    ('42000000-0000-0000-0000-000000000024', 'Session branch switching and default destination', 'access', 1,
     'Changing branch',
     $$Changing branch saves the new currentBranch and clears branch-sensitive suppliers, categories, shiftId, and AB state. Reload branch data before selling, receiving inventory, reporting, or interpreting dashboards. A stale tab cannot authorize access to the previous branch.$$),
    ('42000000-0000-0000-0000-000000000024', 'Session branch switching and default destination', 'access', 2,
     'Default redirect order',
     $$A required password reset goes to the account page first. Platform admins without a company can enter the Web Admin console. Company administrators can land on Company Dashboard; operational users enter the first accessible main-app view. One branch can be auto-selected, while setup-capable users without company or branch are directed to create them.$$),

    ('42000000-0000-0000-0000-000000000025', 'Tenant and branch authorization boundary', 'access', 0,
     'Tenant resolution',
     $$Every protected company operation resolves the authenticated base username to a user and company. The requested tenant must exist and the user must belong through ownership or branch membership. Failures include USER_NOT_FOUND, TENANT_NOT_FOUND, TENANT_ACCESS_DENIED, and TENANT_CONTEXT_NOT_FOUND.$$),
    ('42000000-0000-0000-0000-000000000025', 'Tenant and branch authorization boundary', 'access', 1,
     'Branch resolution',
     $$The active branch can come from the request, the user's branch, or the first valid company branch when supported. The backend verifies that it belongs to the resolved company and that the user can use it. Foreign branch access returns BRANCH_ACCESS_DENIED.$$),
    ('42000000-0000-0000-0000-000000000025', 'Tenant and branch authorization boundary', 'access', 2,
     'URL and payload safety',
     $$Company and branch IDs sent by the browser are not trusted authorization. Changing a route, query string, or JSON body cannot cross tenant or branch boundaries because the server performs membership checks before capability evaluation.$$),

    ('42000000-0000-0000-0000-000000000026', 'Effective configuration snapshot', 'settings', 0,
     'Configuration endpoints',
     $$The client loads /api/config/me/effective, /capabilities, /navigation, and effective branch settings. The effective snapshot combines tenant, package, template, module, navigation, capability, scope, and settings decisions for the signed-in context.$$),
    ('42000000-0000-0000-0000-000000000026', 'Effective configuration snapshot', 'settings', 1,
     'Ready versus fallback',
     $$Before effective configuration is ready, route and shell guards can use legacy allowedRoles to avoid blocking startup. Once ready, capabilities, module state, scopes, and prerequisites are authoritative. A role name alone must not be treated as final access evidence after configuration loads.$$),
    ('42000000-0000-0000-0000-000000000026', 'Effective configuration snapshot', 'settings', 2,
     'Refresh after administration',
     $$After a package, module, role, grant, or user override changes, refresh the effective configuration or sign in again if needed. Existing screens still rely on backend authorization, so stale navigation cannot make a denied API call succeed.$$),

    ('42000000-0000-0000-0000-000000000027', 'Navigation view access and denial reasons', 'access', 0,
     'How views are filtered',
     $$The sidebar includes only registered views whose module is navigable and whose access requirements are satisfied. Groups with no accessible children disappear. The default landing view is selected from the ordered accessible view list.$$),
    ('42000000-0000-0000-0000-000000000027', 'Navigation view access and denial reasons', 'access', 1,
     'Prerequisites',
     $$Routes can require authenticated, company_exists, branch_selected, branch_active, onboarding_complete, or onboarding_incomplete states. A capability cannot compensate for a missing runtime prerequisite. The reason is prerequisite_unmet.$$),
    ('42000000-0000-0000-0000-000000000027', 'Navigation view access and denial reasons', 'access', 2,
     'Denial meanings',
     $$unknown_view means the view is not registered; access_denied means capability or role requirements failed; plan_locked means the package disables the module; workspace_disabled means tenant configuration disables it; module_unavailable means it is not in effective navigation. These reasons guide the correct administrator action.$$),

    ('42000000-0000-0000-0000-000000000028', 'Any all and backend capability checks', 'access', 0,
     'Any-of requirements',
     $$requiredCapabilities is an any-of list: one applicable capability is enough for that frontend route or view. For example, a route listing dashboard.home.view and finance.report.read can be visible when either matches. This is navigation behavior, not a promise that every API used inside the page accepts either capability.$$),
    ('42000000-0000-0000-0000-000000000028', 'Any all and backend capability checks', 'access', 1,
     'All-of requirements',
     $$requiredAllCapabilities is an all-of list: every listed capability must apply. A view can use both any-of and all-of checks. The access resolver also evaluates module availability and runtime prerequisites, so capability matching is necessary but not always sufficient.$$),
    ('42000000-0000-0000-0000-000000000028', 'Any all and backend capability checks', 'access', 2,
     'Backend is authoritative',
     $$Backend controllers check the exact capability needed for each operation and return CAPABILITY_DENIED when absent. The branch and company dashboard summary APIs require dashboard.home.view even if a frontend route was discoverable through finance.report.read. Always grant the operation's real capability, not a cosmetically related one.$$),

    ('42000000-0000-0000-0000-000000000029', 'Module package template and tenant precedence', 'settings', 0,
     'Module resolution order',
     $$Effective module state resolves in this order: platform default, package policy, company template default, then tenant override. The effective result records its source so administrators can explain why a module is enabled or disabled.$$),
    ('42000000-0000-0000-0000-000000000029', 'Module package template and tenant precedence', 'settings', 1,
     'Package lock',
     $$A module disabled by the subscribed package is package_locked and cannot be re-enabled by template, tenant override, role grant, or user allow. Access requires changing to a package that includes the module. The UI reports a higher-plan or plan-locked state.$$),
    ('42000000-0000-0000-0000-000000000029', 'Module package template and tenant precedence', 'settings', 2,
     'Workspace disable',
     $$A module disabled by a tenant-level workspace choice reports workspace_disabled. An authorized company administrator can change that module override when the package permits it. Capability grants remain unusable while their module is unavailable.$$),

    ('42000000-0000-0000-0000-000000000030', 'Roles assignments and grants', 'access', 0,
     'Role definition and assignment',
     $$A role definition is a reusable set of grants. A tenant role assignment connects a user to that role at company or branch scope. Removing an assignment removes only the access contributed by that assignment; other roles and direct user overrides are evaluated independently.$$),
    ('42000000-0000-0000-0000-000000000030', 'Roles assignments and grants', 'access', 1,
     'Allow grants',
     $$An active role grant with grantMode allow contributes its capability when assignment scope and branch context match. Role deny mode is reserved and does not grant. Deprecated or inactive capabilities are not usable operational access.$$),
    ('42000000-0000-0000-0000-000000000030', 'Roles assignments and grants', 'access', 2,
     'Administrative permission',
     $$Reading company-user access needs users.account.read or another allowed portal-read capability. Changing role assignments, role grants, and user overrides requires users.account.edit. The target user, role, branch, and capability are validated inside the tenant.$$),

    ('42000000-0000-0000-0000-000000000031', 'Capability scopes', 'access', 0,
     'Scope types',
     $$Capabilities use self, branch, company, or global_admin scope. Self applies only to the same base username. Branch applies to one active branch. Company applies across the tenant where the operation supports company scope. global_admin is reserved for platform administration.$$),
    ('42000000-0000-0000-0000-000000000031', 'Capability scopes', 'access', 1,
     'Assignment projection',
     $$A company-scoped assignment keeps the grant's declared scope. A branch assignment narrows company or branch grants to that exact branch, keeps self grants as self, and drops global_admin grants. A branch assignment never creates platform-wide authority.$$),
    ('42000000-0000-0000-0000-000000000031', 'Capability scopes', 'access', 2,
     'Branch mismatch',
     $$A branch-scoped grant applies only when its scopeBranchId equals the active branch. Missing or different branch context makes it inapplicable. Use a company-scoped grant only when the job genuinely needs all company branches.$$),

    ('42000000-0000-0000-0000-000000000032', 'User allow and deny overrides', 'access', 0,
     'Direct allow',
     $$A user allow override adds a direct capability at the exact capability, scope type, and optional branch key. It is useful for a documented exception but should not replace a well-designed role for many users.$$),
    ('42000000-0000-0000-0000-000000000032', 'User allow and deny overrides', 'access', 1,
     'Explicit deny',
     $$A user deny override removes the matching effective key, including matching role contribution. It does not automatically deny the same capability at every scope or branch. Verify capabilityKey, scopeType, and scopeBranchId when a user still has another valid path.$$),
    ('42000000-0000-0000-0000-000000000032', 'User allow and deny overrides', 'access', 2,
     'Validation and reason',
     $$Override scope must match the capability scope, and branch scope requires a tenant-owned branch. Errors include USER_OVERRIDE_SCOPE_MISMATCH and USER_OVERRIDE_BRANCH_REQUIRED. Record a concise reason so the access graph and audit trail explain the exception.$$),

    ('42000000-0000-0000-0000-000000000033', 'User access graph', 'access', 0,
     'Graph structure',
     $$The access graph explains User to Module to Resource to Capability relationships. Its summary includes accessible and total capabilities, role-derived access, direct grants, explicit denies, and locked items. Search and state filters help locate a capability.$$),
    ('42000000-0000-0000-0000-000000000033', 'User access graph', 'access', 1,
     'Capability states',
     $$States include DIRECT_GRANTED, ROLE_GRANTED, EXPLICITLY_DENIED, MODULE_LOCKED, SCOPE_MISMATCH, NOT_GRANTED, and DEPRECATED. usableAccess is true only when a grant applies and its module is available.$$),
    ('42000000-0000-0000-0000-000000000033', 'User access graph', 'access', 2,
     'Details drawer',
     $$Capability details show effective scope and branch, module availability and source, granting roles, blocked or inapplicable roles, and user override ID, grant mode, and reason. Use those paths to change the actual cause instead of repeatedly adding grants.$$),

    ('42000000-0000-0000-0000-000000000034', 'Access graph mutation actions', 'access', 0,
     'Grant block remove and restore',
     $$Grant creates a direct allow when no usable role or direct path exists and the module is available. Block creates a matching deny against role-derived access. Remove deletes a direct override. Restore removes an explicit deny so matching role access can apply again.$$),
    ('42000000-0000-0000-0000-000000000034', 'Access graph mutation actions', 'access', 1,
     'Read-only cases',
     $$Actions are read-only when the administrator cannot mutate access, the target is an Owner bypass, the capability is deprecated, a global_admin capability is not tenant-targetable, a required branch is unavailable, or the module is package-locked or workspace-disabled.$$),
    ('42000000-0000-0000-0000-000000000034', 'Access graph mutation actions', 'access', 2,
     'Self-lockout protection',
     $$A non-Owner administrator cannot remove their last users.account.edit path by editing their own matching override. The backend rechecks effective access after mutation and returns SELF_LOCKOUT_PROTECTED so the transaction rolls back.$$),

    ('42000000-0000-0000-0000-000000000035', 'Owner behavior and security boundary', 'access', 0,
     'Owner frontend behavior',
     $$Once effective configuration is ready, the app shell treats Owner as broadly permitted for registered views, subject to module and runtime context behavior. This improves administration but does not make arbitrary foreign tenant or branch identifiers valid.$$),
    ('42000000-0000-0000-0000-000000000035', 'Owner behavior and security boundary', 'access', 1,
     'Owner backend behavior',
     $$Backend owner bypass is evaluated only after authenticated tenant and branch membership are resolved. An Owner cannot cross into another tenant or unrelated branch. Tenant and branch isolation always precede broad role behavior.$$),
    ('42000000-0000-0000-0000-000000000035', 'Owner behavior and security boundary', 'access', 2,
     'Owner access editing',
     $$Owner bypass is represented as non-mutable in the user access graph. Do not try to block the Owner by adding ordinary tenant user denies. Transfer or change ownership only through an explicit supported governance workflow.$$),

    ('42000000-0000-0000-0000-000000000036', 'Company access administration endpoints', 'settings', 0,
     'Portal and access map',
     $$The company administration API exposes a tenant portal and per-user access map. Portal read is allowed by an applicable company.settings.read, company.settings.edit, users.account.read, or users.account.edit capability. Target users must belong to the tenant.$$),
    ('42000000-0000-0000-0000-000000000036', 'Company access administration endpoints', 'settings', 1,
     'Module and workflow changes',
     $$Company module and workflow configuration changes require company.settings.edit. Package and capability constraints are revalidated by the backend. A disabled package module cannot be forced on by sending an override directly.$$),
    ('42000000-0000-0000-0000-000000000036', 'Company access administration endpoints', 'settings', 2,
     'Role and user changes',
     $$Role assignments, role grants, and user overrides require users.account.edit. Common validation errors include ROLE_GRANT_SCOPE_MISMATCH, USER_OVERRIDE_SCOPE_MISMATCH, USER_OVERRIDE_BRANCH_REQUIRED, CAPABILITY_NOT_FOUND, and CAPABILITY_INACTIVE.$$),

    ('42000000-0000-0000-0000-000000000037', 'Least privilege access troubleshooting', 'help', 0,
     'Diagnose before granting',
     $$Identify the exact denied operation and backend error. Then check prerequisite, module source, package, capability key, scope, active branch, role assignment, role grant, direct override, deny override, and target ownership. Granting a broad role before finding the failed layer can expose unrelated data.$$),
    ('42000000-0000-0000-0000-000000000037', 'Least privilege access troubleshooting', 'help', 1,
     'Safe change sequence',
     $$Prefer the smallest active capability at the narrowest valid scope, normally through a job role. Use a direct override for a documented exception and add a reason. Test with the target user in the intended branch, refresh effective configuration, and confirm both navigation and backend operation.$$),
    ('42000000-0000-0000-0000-000000000037', 'Least privilege access troubleshooting', 'help', 2,
     'Common errors',
     $$CAPABILITY_DENIED means the effective capability does not apply. SELF_ACCESS_DENIED means a self-scoped request targeted another user. TENANT_ACCESS_DENIED and BRANCH_ACCESS_DENIED are ownership boundary failures. PORTAL_ACCESS_DENIED means none of the permitted company portal capabilities applies.$$),

    ('42000000-0000-0000-0000-000000000038', 'Dashboards and Access Arabic English terminology', 'help', 0,
     'Dashboard terms',
     $$لوحة المعلومات = dashboard; لوحة الفرع = branch dashboard; لوحة الشركة = company dashboard; المبيعات اليوم = today sales; الربح الإجمالي = gross profit; متوسط قيمة الطلب = average order value; العملاء الجدد = new clients; تنبيهات = alerts; المخزون المنخفض = low stock; نفاد المخزون = out of stock; الذمم المدينة = receivables.$$),
    ('42000000-0000-0000-0000-000000000038', 'Dashboards and Access Arabic English terminology', 'help', 1,
     'Insight and scope terms',
     $$الرؤى الذكية = Smart Insights; حرج = critical; تحذير = warning; معلومات = info; الفرع المحدد = selected branch; نطاق الشركة = company scope; نطاق الفرع = branch scope; هذا المستخدم فقط = self scope; إعادة الحساب = recalculate; استبعاد = dismiss; تم الحل = resolved.$$),
    ('42000000-0000-0000-0000-000000000038', 'Dashboards and Access Arabic English terminology', 'help', 2,
     'Access terms',
     $$الوصول = access; صلاحية = capability or permission; دور = role; منح مباشر = direct grant; منع صريح = explicit deny; الوحدة مقفلة بالخطة = module package locked; الوحدة معطلة = workspace disabled; لا يوجد وصول = access denied; الشركة = company or tenant; تغيير الفرع = switch branch; أقل صلاحية لازمة = least privilege.$$);

INSERT INTO public.ai_document
    (id, company_id, title, document_type, module, language, content,
     metadata_json, active, created_at, updated_at)
SELECT
    document_id,
    NULL,
    title,
    'HELP_ARTICLE',
    module,
    'en',
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    '{"seed":"rag-dashboard-access-detail-v1","source":"implemented-dashboard-access-workflows"}',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_dashboards_access_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    document_type = EXCLUDED.document_type,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json,
    active = true,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_document_chunk
    (id, document_id, company_id, title, module, language, chunk_index,
     content, metadata_json, created_at)
SELECT
    md5('legacy-dashboard-access-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    title,
    module,
    'en',
    chunk_index,
    heading || E'\n' || content,
    '{"seed":"rag-dashboard-access-detail-v1","retrieval":"keyword"}',
    CURRENT_TIMESTAMP
FROM vls_ai_dashboards_access_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    title = EXCLUDED.title,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json;

INSERT INTO public.ai_knowledge_document
    (id, company_id, branch_id, module, language, document_type, title,
     source_type, source_uri, content_hash, raw_content, normalized_content,
     status, metadata_json, created_at, updated_at)
SELECT
    document_id,
    NULL,
    NULL,
    module,
    'en',
    'HELP_ARTICLE',
    title,
    'APPLICATION',
    'valueinsoft://help/dashboards-access/' || replace(lower(title), ' ', '-'),
    md5(string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index)),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    'ACTIVE',
    '{"seed":"rag-dashboard-access-detail-v1","source":"implemented-dashboard-access-workflows"}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_dashboards_access_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    document_type = EXCLUDED.document_type,
    title = EXCLUDED.title,
    source_type = EXCLUDED.source_type,
    source_uri = EXCLUDED.source_uri,
    content_hash = EXCLUDED.content_hash,
    raw_content = EXCLUDED.raw_content,
    normalized_content = EXCLUDED.normalized_content,
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_knowledge_chunk
    (id, document_id, company_id, branch_id, module, language, chunk_index,
     heading, content, token_count, embedding, embedding_model, status,
     metadata_json, created_at)
SELECT
    md5('knowledge-dashboard-access-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    NULL,
    module,
    'en',
    chunk_index,
    heading,
    content,
    cardinality(regexp_split_to_array(btrim(content), E'\\s+')),
    NULL,
    'keyword-fallback',
    'ACTIVE',
    '{"seed":"rag-dashboard-access-detail-v1","embeddingStatus":"pending-real-provider"}'::jsonb,
    CURRENT_TIMESTAMP
FROM vls_ai_dashboards_access_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    branch_id = EXCLUDED.branch_id,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    heading = EXCLUDED.heading,
    content = EXCLUDED.content,
    token_count = EXCLUDED.token_count,
    embedding = NULL,
    embedding_model = 'keyword-fallback',
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json;

DROP TABLE vls_ai_dashboards_access_detail_chunk;
