-- ==========================================================
-- V167 - Detailed Clients and Suppliers RAG knowledge
-- ==========================================================
-- Source-of-truth help content derived from the implemented web
-- screens, controllers, services, capability checks, open-item
-- accounting, credit controls, trade-ins, and supplier lifecycle.
-- The same corpus is written to the legacy and semantic RAG stores.
-- Keyword retrieval is immediately available; embeddings remain pending
-- until a real embedding provider is configured.
-- ==========================================================

CREATE TEMP TABLE vls_ai_clients_suppliers_detail_chunk (
    document_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    module VARCHAR(100) NOT NULL,
    chunk_index INTEGER NOT NULL,
    heading TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (document_id, chunk_index)
);

INSERT INTO vls_ai_clients_suppliers_detail_chunk
    (document_id, title, module, chunk_index, heading, content)
VALUES
    ('43000000-0000-0000-0000-000000000001', 'Clients module navigation and purpose', 'customers', 0,
     'What the Clients module manages',
     $$The Clients or Customers module manages customer identities, contact details, order history, receipts, rewards, receivable open items, statements, aging, credit controls, and customer trade-ins. Use the selected client profile to keep these different records tied to the correct person.$$),
    ('43000000-0000-0000-0000-000000000001', 'Clients module navigation and purpose', 'customers', 1,
     'Open and select a client',
     $$Open Customers or Clients from the authorized application navigation. The list is scoped to the current company and normally the selected branch. In a POS client picker, selecting a row assigns that client to the sale; opening Info displays the full profile without changing the sale.$$),
    ('43000000-0000-0000-0000-000000000001', 'Clients module navigation and purpose', 'customers', 2,
     'Help questions versus live data',
     $$Ask HELP questions for workflow explanations such as how to add a client or read aging. Ask CUSTOMERS or BUSINESS questions for live tenant data such as finding a customer by phone or checking current balances. Live values must come from authorized tools or SQL, while RAG explains how the system works.$$),

    ('43000000-0000-0000-0000-000000000002', 'Create a client', 'customers', 0,
     'Required client information',
     $$Use Add Client and enter the client name, gender, phone number, and optional description. The implemented form accepts Male or Female, requires a name between 10 and 45 characters, requires a phone between 11 and 16 characters, and limits the optional description to 255 characters.$$),
    ('43000000-0000-0000-0000-000000000002', 'Create a client', 'customers', 1,
     'Duplicate phone protection',
     $$The phone number identifies the client during lookup and must not already belong to another client in the applicable company data. If the application reports that the phone is taken, search by that number and use the existing profile instead of creating a duplicate.$$),
    ('43000000-0000-0000-0000-000000000002', 'Create a client', 'customers', 2,
     'Online and offline creation',
     $$When offline mode is enabled and the device is offline or has no usable token, Add Client can route to the offline POS store and later synchronize. Do not repeatedly submit after a delayed response. Check the local client list and synchronization state first to avoid duplicate customer records.$$),

    ('43000000-0000-0000-0000-000000000003', 'Search and choose clients', 'customers', 0,
     'Search modes',
     $$The client list can show the latest 5, 10, 20, or 100 clients. Search supports client name, phone number, or client ID. A digits-only query is treated as a numeric lookup and can match an exact client ID as well as phone results; other text uses name search.$$),
    ('43000000-0000-0000-0000-000000000003', 'Search and choose clients', 'customers', 1,
     'Search scope and refresh',
     $$Results belong to the authenticated company and current branch context. Refresh clears the applied search and reloads recent clients. If a known client is missing, verify company, branch, archived state, spelling, phone formatting, online status, and the current result limit.$$),
    ('43000000-0000-0000-0000-000000000003', 'Search and choose clients', 'customers', 2,
     'POS client selection',
     $$Inside the POS picker, click Select or the permitted row action to attach the client to the current transaction. Confirm the displayed name and phone before charging credit, applying rewards, or completing a trade-in. Searching for a client does not itself modify the cart or customer account.$$),

    ('43000000-0000-0000-0000-000000000004', 'Client profile orders and order details', 'customers', 0,
     'Profile summary',
     $$Client Info shows the customer identity and summary values, then separates detail into tabs. The Orders tab lists the selected client's branch orders; opening an order loads its line details. The profile must be opened from the correct client row to avoid reviewing another customer's history.$$),
    ('43000000-0000-0000-0000-000000000004', 'Client profile orders and order details', 'customers', 1,
     'Order history scope',
     $$Customer order history is company and branch scoped. A client can exist at company level while the visible order list reflects only the requested branch. A zero order count does not prove the client has never purchased at another branch or outside the active filters.$$),
    ('43000000-0000-0000-0000-000000000004', 'Client profile orders and order details', 'customers', 2,
     'Verify financial meaning',
     $$Orders show sales activity, but receivable exposure and settled cash are separate records. Use Account and Credit for open debt, Client Receipts for payments, and Finance reports for posted accounting. Do not infer that an order is paid solely because it appears in order history.$$),

    ('43000000-0000-0000-0000-000000000005', 'Client receipts rewards and vouchers', 'customers', 0,
     'Client receipts',
     $$The client profile can load receipts recorded for the selected client. Receipt rows represent money received, not sales invoices. Compare receipt date, amount, branch, reference, and allocation status when reconciling a customer's balance.$$),
    ('43000000-0000-0000-0000-000000000005', 'Client receipts rewards and vouchers', 'customers', 1,
     'Rewards history',
     $$The Reward History tab displays reward or loyalty activity available for the client. Reward entries and vouchers are promotional records and must not be treated as cash receipts or receivable settlements unless a supported transaction explicitly posts that effect.$$),
    ('43000000-0000-0000-0000-000000000005', 'Client receipts rewards and vouchers', 'customers', 2,
     'Troubleshoot empty tabs',
     $$Tabs load their data independently. If orders load but receipts or rewards do not, keep the valid orders and retry the failed tab. Verify capability, company, branch, client ID, network state, and whether the client genuinely has records of that type.$$),

    ('43000000-0000-0000-0000-000000000006', 'Archive and reactivate clients', 'customers', 0,
     'Archive instead of unsafe deletion',
     $$The client lifecycle action changes the archived status rather than erasing historical business evidence. Archiving is appropriate when the customer should no longer be selected for new activity but past orders, receipts, statements, and audit relationships must remain traceable.$$),
    ('43000000-0000-0000-0000-000000000006', 'Archive and reactivate clients', 'customers', 1,
     'Reactivate a client',
     $$Reactivate by changing the archived status back to active through the supported client action. Confirm that you selected the correct client and have clients.account.archive. If the client is not visible, search archived records or use the applicable lifecycle filter rather than creating a replacement.$$),
    ('43000000-0000-0000-0000-000000000006', 'Archive and reactivate clients', 'customers', 2,
     'Access and tenant safety',
     $$Client status changes require clients.account.archive and the backend verifies tenant access. Editing a URL or client ID cannot move or reactivate a customer in another company. A denied status change should be resolved through access configuration, not by duplicating the client.$$),

    ('43000000-0000-0000-0000-000000000007', 'Client receivable open items', 'customers', 0,
     'What an open item is',
     $$A client open item is an unpaid or partly paid accounts-receivable document for a credit sale or another supported debit. It carries original amount, remaining amount, currency, document date, due date, source type, and source reference. The open amount, not the original invoice total, is the amount still unsettled.$$),
    ('43000000-0000-0000-0000-000000000007', 'Client receivable open items', 'customers', 1,
     'Filters and paging',
     $$The Account and Credit panel can filter client items by status and load a paged result, normally 50 rows at a time. The query is scoped by company, selected branch, and client. Use open status for current debt and include settled items only when researching history.$$),
    ('43000000-0000-0000-0000-000000000007', 'Client receivable open items', 'customers', 2,
     'Permissions and source records',
     $$Viewing client open items requires clients.openitems.view. Open items are accounting settlement records; the related sale remains the commercial source document. If totals disagree, compare currency, branch, posting status, reversals, allocations, and the same as-of date before correcting data.$$),

    ('43000000-0000-0000-0000-000000000008', 'Client statement and receivable aging', 'customers', 0,
     'Client statement',
     $$The client account statement reports movements over a date range. When dates are omitted, the backend uses today as the end and the previous 90 days as the start. fromDate must not be after toDate. Opening balance, debits, credits, and closing balance must be read in the displayed currency and branch scope.$$),
    ('43000000-0000-0000-0000-000000000008', 'Client statement and receivable aging', 'customers', 1,
     'Receivable aging buckets',
     $$Client aging groups remaining receivables as current, 1-30, 31-60, 61-90, and over 90 days based on due dates as of the requested date. Aging measures lateness, not customer purchase volume. An old sale can be absent when fully settled, reversed, or outside the selected scope.$$),
    ('43000000-0000-0000-0000-000000000008', 'Client statement and receivable aging', 'customers', 2,
     'Statement and aging access',
     $$Statements require clients.account.statement.view and aging requires clients.openitems.view. Both also enforce authenticated company and branch access. Exported or printed figures should include client, branch, currency, date range or as-of date, and generation time so the report can be reproduced.$$),

    ('43000000-0000-0000-0000-000000000009', 'Client credit limit terms and status', 'customers', 0,
     'Credit values',
     $$The Credit panel shows credit limit, current open exposure, available credit, payment terms in days, currency, status, and optional notes. Available credit is derived from the limit and exposure. Zero limit with positive exposure is displayed as fully used or over limit, not as unlimited credit.$$),
    ('43000000-0000-0000-0000-000000000009', 'Client credit limit terms and status', 'customers', 1,
     'NORMAL HOLD and BLOCKED',
     $$NORMAL allows the ordinary branch credit rules. HOLD denies new credit sales, while BLOCKED denies all credit sales when branch credit checking is enabled. These statuses concern credit sales; they do not automatically erase debt, cancel orders, or block permitted cash sales.$$),
    ('43000000-0000-0000-0000-000000000009', 'Client credit limit terms and status', 'customers', 2,
     'Editing credit settings',
     $$Viewing needs clients.credit.view and editing needs clients.credit.manage. Credit limit and terms must be zero or positive. New credit-sale due dates use the terms in effect at sale time, so changing terms does not silently rewrite existing open-item due dates.$$),

    ('43000000-0000-0000-0000-000000000010', 'Allocate client receipts to open items', 'customers', 0,
     'Allocation purpose',
     $$A client receipt can be allocated against one or more settleable receivable open items. Enter allocations that identify the target items and amounts. The total allocation cannot exceed the receipt amount or any item's remaining balance, and currency must match the supported accounting context.$$),
    ('43000000-0000-0000-0000-000000000010', 'Allocate client receipts to open items', 'customers', 1,
     'On-account remainder',
     $$If allocations are omitted or total less than the receipt, the unallocated amount remains on account according to the implemented workflow. If no settleable items exist, the full receipt stays on account. This is not an error, but it should be reviewed during reconciliation.$$),
    ('43000000-0000-0000-0000-000000000010', 'Allocate client receipts to open items', 'customers', 2,
     'Idempotency and reversal',
     $$Allocation and reversal commands use protected backend operations and may use idempotency keys to prevent double application. Do not retry by creating a second receipt after a timeout. Reload the receipt and open items first, then use the supported reversal operation when an allocation was genuinely wrong.$$),

    ('43000000-0000-0000-0000-000000000011', 'Client trade-in overview', 'customers', 0,
     'Client as seller',
     $$A client trade-in records a product the customer sold to the business, so the client acts as a supplier for that transaction. This is different from the client's normal purchase orders and accounts receivable. The profile Trade-ins tab shows items received, payments made to the selling client, remaining payable, and a seller statement.$$),
    ('43000000-0000-0000-0000-000000000011', 'Client trade-in overview', 'customers', 1,
     'Trade-in item identity',
     $$Trade-in records can include product, SKU, condition, buying price, receipt reference, branch, date, serial number, and IMEI where applicable. Verify serial or IMEI uniqueness and product condition before receiving inventory; the client profile alone does not validate physical stock.$$),
    ('43000000-0000-0000-0000-000000000011', 'Client trade-in overview', 'customers', 2,
     'Trade-in permissions',
     $$Viewing trade-ins requires clients.tradein.view. The seller statement uses clients.statement.view, and recording a payment uses the applicable clients trade-in payment capability. Receiving stock can also require product-creation and inventory permissions because the operation changes inventory.$$),

    ('43000000-0000-0000-0000-000000000012', 'Receive and pay client trade-ins', 'customers', 0,
     'Receive trade-in inventory',
     $$Inventory received from a client uses the typed product receipt workflow with acquisitionSource CLIENT_TRADE_IN. Select the selling client, branch, product details, condition, quantity or serialized identity, and buying price. Confirm the receipt before posting because it creates stock and a payable relationship to the client.$$),
    ('43000000-0000-0000-0000-000000000012', 'Receive and pay client trade-ins', 'customers', 1,
     'Pay the selling client',
     $$A trade-in payment reduces the amount owed to the client-as-seller. Use the payment action from the Trade-ins area, enter the supported amount and reference, and verify the returned receipt. Do not record the payment as an ordinary client receipt, because client receipts settle money the customer owes the business.$$),
    ('43000000-0000-0000-0000-000000000012', 'Receive and pay client trade-ins', 'customers', 2,
     'Trade-in statement reconciliation',
     $$The trade-in summary separates total owed, paid amount, and remaining payable. Reconcile it with received products, trade-in payment receipts, finance posting status, branch, and currency. A normal customer receivable can coexist with a trade-in payable; do not net the two without an explicit supported accounting action.$$),

    ('43000000-0000-0000-0000-000000000013', 'Customer behavior analytics', 'customers', 0,
     'Behavior scope',
     $$Customer Behavior Analytics derives deterministic metrics from linked customer purchases in a selected branch and date range. It can provide overview metrics, customer rows, segments, preferences, recent orders, product affinity, retention cohorts, spend trends, and at-risk insights where supported.$$),
    ('43000000-0000-0000-0000-000000000013', 'Customer behavior analytics', 'customers', 1,
     'Interpretation limits',
     $$Behavior metrics only include sales linked to identifiable clients and the requested scope. Walk-in sales without a client cannot be attributed. A segment or at-risk label is analytical evidence for review, not an automatic credit block, marketing consent, or instruction to alter a customer's account.$$),
    ('43000000-0000-0000-0000-000000000013', 'Customer behavior analytics', 'customers', 2,
     'AI and deterministic data',
     $$The underlying metrics and segments are calculated from business data. An AI explanation can summarize them but must not invent customer activity. Validate recommendations against the displayed period, filters, sample size, order history, and the customer's current credit and consent context.$$),

    ('43000000-0000-0000-0000-000000000014', 'Client access and data scope', 'customers', 0,
     'Core capabilities',
     $$Client lookup and profile data require clients.account.read. Creation requires clients.account.create, and lifecycle status changes require clients.account.archive. Account features have narrower capabilities including clients.openitems.view, clients.account.statement.view, clients.credit.view, and clients.credit.manage.$$),
    ('43000000-0000-0000-0000-000000000014', 'Client access and data scope', 'customers', 1,
     'Scope enforcement',
     $$The backend applies authenticated company and branch scope in addition to capabilities. A user with client read access in one branch cannot use a foreign branch or tenant identifier to read another scope. Company-level client identity does not make every branch's transactions visible.$$),
    ('43000000-0000-0000-0000-000000000014', 'Client access and data scope', 'customers', 2,
     'Least privilege',
     $$Grant the smallest capability needed for the task. A cashier may need lookup and selection without credit-management or statement access. Finance or authorized managers may need open items, statements, allocations, or credit controls. Hidden tabs and disabled buttons normally reflect effective access.$$),

    ('43000000-0000-0000-0000-000000000015', 'Client troubleshooting and reconciliation', 'customers', 0,
     'Client not found',
     $$When a client is not found, confirm the active company and branch, search by exact phone and numeric client ID, increase the latest-client limit, clear the current search, and check archived or offline synchronization state. Do not create a new client until duplicate phone lookup is complete.$$),
    ('43000000-0000-0000-0000-000000000015', 'Client troubleshooting and reconciliation', 'customers', 1,
     'Balance disagreement',
     $$For a disputed client balance, compare open items, statement dates, receipts, allocations, reversals, credit-sale documents, currency, branch, and finance posting status. Order totals, receipt totals, exposure, and statement closing balance answer different questions and should not be compared without matching scope.$$),
    ('43000000-0000-0000-0000-000000000015', 'Client troubleshooting and reconciliation', 'customers', 2,
     'Safe recovery',
     $$Refresh the failed tab once and preserve the error code, client ID, branch, filters, and time. Never post a duplicate sale, receipt, allocation, or trade-in payment merely to make the screen update. Verify whether the first request committed before retrying.$$),

    ('43000000-0000-0000-0000-000000000016', 'Clients Arabic English terminology', 'customers', 0,
     'Core client terms',
     $$العملاء or الزبائن = clients or customers; إضافة عميل = add client; البحث بالاسم أو الهاتف أو رقم العميل = search by name, phone, or client ID; ملف العميل = client profile; سجل الطلبات = order history; الإيصالات = receipts; نقاط الولاء = rewards; مؤرشف = archived; إعادة تنشيط = reactivate.$$),
    ('43000000-0000-0000-0000-000000000016', 'Clients Arabic English terminology', 'customers', 1,
     'Credit and receivable terms',
     $$الحساب والائتمان = account and credit; الذمم المدينة = accounts receivable; بند مفتوح = open item; كشف حساب العميل = client statement; أعمار الديون = receivable aging; حد الائتمان = credit limit; المديونية الحالية = open exposure; الائتمان المتاح = available credit; مدة السداد = payment terms.$$),
    ('43000000-0000-0000-0000-000000000016', 'Clients Arabic English terminology', 'customers', 2,
     'Trade-in terms',
     $$شراء من عميل or استبدال منتج = client trade-in; العميل البائع = selling client; إجمالي المستحق للعميل = total owed to client; المدفوع = paid; المتبقي = remaining; إيصال الاستلام = receiving receipt; الرقم التسلسلي = serial number; الرقم الدولي للجهاز = IMEI; حالة المنتج = condition.$$),

    ('43000000-0000-0000-0000-000000000017', 'Suppliers module navigation and list', 'suppliers', 0,
     'What the Suppliers module manages',
     $$The Suppliers module manages vendor profiles, branch supplier lists, purchase and received-product history, payments, statements, accounts-payable aging, open items, amounts a supplier owes the business, returns, lifecycle status, and audit events.$$),
    ('43000000-0000-0000-0000-000000000017', 'Suppliers module navigation and list', 'suppliers', 1,
     'Search and filter suppliers',
     $$The supplier list is loaded for the authenticated company and selected branch. Search can match name, primary or secondary phone, location, major or category, and other displayed identity fields. Status filters distinguish active, blocked, and archived suppliers where available.$$),
    ('43000000-0000-0000-0000-000000000017', 'Suppliers module navigation and list', 'suppliers', 2,
     'Help questions versus live supplier data',
     $$Use HELP for instructions such as how to archive a supplier or read AP aging. Use SUPPLIERS or BUSINESS for live questions such as top suppliers by payable or pending supplier invoices. RAG provides workflow knowledge; current balances and rankings must come from authorized live tools or SQL.$$),

    ('43000000-0000-0000-0000-000000000018', 'Create and edit suppliers', 'suppliers', 0,
     'Supplier fields',
     $$Creating a supplier requires a name, primary phone, location, major or business category, company, and branch; secondary phone is optional. Review spelling and contact details because these values drive search, receipts, statements, and exported records.$$),
    ('43000000-0000-0000-0000-000000000018', 'Create and edit suppliers', 'suppliers', 1,
     'Duplicate protection',
     $$Within a branch, the backend normalizes the supplier name and primary phone and rejects a duplicate name or duplicate primary phone. Search active and archived suppliers before adding a new one. A formatting variation should not be used to bypass duplicate protection.$$),
    ('43000000-0000-0000-0000-000000000018', 'Create and edit suppliers', 'suppliers', 2,
     'Create and edit access',
     $$Creating requires suppliers.account.create and editing requires suppliers.account.edit. The supplier ID in an update body must match the path when supplied. The backend also checks that the supplier belongs to the requested company and branch.$$),

    ('43000000-0000-0000-0000-000000000019', 'Copy suppliers between branches', 'suppliers', 0,
     'Copy workflow',
     $$Copy From Branch imports supplier profiles from another branch of the same company into the selected target branch. Choose different source and target branches, review the source, and run the copy once. The operation copies profiles, not historical purchases, payments, statements, or balances.$$),
    ('43000000-0000-0000-0000-000000000019', 'Copy suppliers between branches', 'suppliers', 1,
     'Duplicates are skipped',
     $$During branch copy, suppliers whose normalized name or primary phone already exists in the target branch are skipped. The result reports copied count, skipped count, skipped names, and source total. A skipped supplier is not a failed transaction when it was identified as a duplicate.$$),
    ('43000000-0000-0000-0000-000000000019', 'Copy suppliers between branches', 'suppliers', 2,
     'Copy permissions',
     $$Copying requires suppliers.account.create in the target branch and suppliers.account.read in the source branch. Both branches must belong to the authenticated tenant. If branch access is denied, request the minimum required branch-scoped access instead of recreating records manually.$$),

    ('43000000-0000-0000-0000-000000000020', 'Archive reactivate and delete suppliers', 'suppliers', 0,
     'Archive supplier',
     $$Archiving a supplier requires a non-empty reason and suppliers.account.edit. The archived profile and its history remain available for authorized review, but the supplier should not be used for new ordinary activity. An already archived supplier cannot be archived again.$$),
    ('43000000-0000-0000-0000-000000000020', 'Archive reactivate and delete suppliers', 'suppliers', 1,
     'Reactivate supplier',
     $$Reactivate restores an archived supplier to active status and also requires suppliers.account.edit. Only archived suppliers can be reactivated. Review the prior archive reason and current contact information before resuming transactions.$$),
    ('43000000-0000-0000-0000-000000000020', 'Archive reactivate and delete suppliers', 'suppliers', 2,
     'Hard delete protection',
     $$Deletion requires suppliers.account.delete and is allowed only when reference checks say the supplier can be deleted. Referenced transactions or an open balance produce SUPPLIER_HAS_REFERENCES. Archive the supplier instead of deleting accounting or inventory evidence to force deletion.$$),

    ('43000000-0000-0000-0000-000000000021', 'Supplier profile totals and tabs', 'suppliers', 0,
     'Supplier summary cards',
     $$Supplier Details shows identity, contact fields, status, total purchases or supplier sales to the branch, amount paid, remaining amount, settlement state, and settlement rate. Remaining amount greater than zero indicates an outstanding balance under that summary; zero indicates fully settled for the loaded scope.$$),
    ('43000000-0000-0000-0000-000000000021', 'Supplier profile totals and tabs', 'suppliers', 1,
     'Available supplier tabs',
     $$The implemented profile separates purchase details, supplier receipts, statement, AP aging, open items, supplier receivables or Should pay us, returns to supplier, and audit trail. Each tab answers a different question and can load independently.$$),
    ('43000000-0000-0000-0000-000000000021', 'Supplier profile totals and tabs', 'suppliers', 2,
     'Do not mix totals',
     $$Purchase total, payments, AP open balance, and supplier receivable balance are not interchangeable. Filter all records to the same company, branch, supplier, currency, and date or as-of date. Use posted statement and open-item data for settlement verification.$$),

    ('43000000-0000-0000-0000-000000000022', 'Supplier purchases and received products', 'suppliers', 0,
     'Purchase history',
     $$The Purchase Details or salesDetails tab lists inventory transactions associated with goods obtained from the supplier. It represents purchases or receipts into the branch, not customer sales. Review document reference, product, quantity, cost, date, user, and posting state.$$),
    ('43000000-0000-0000-0000-000000000022', 'Supplier purchases and received products', 'suppliers', 1,
     'Supplier product rows',
     $$The supplier bought-products history records product, quantity, cost, paid state, time, description, and order-detail relationship where applicable. A record-only entry must not be assumed to adjust inventory unless the typed inventory receipt or return workflow actually performed the stock movement.$$),
    ('43000000-0000-0000-0000-000000000022', 'Supplier purchases and received products', 'suppliers', 2,
     'Posting verification',
     $$Inventory receipt and finance posting can have separate statuses. If goods are visible but the payable or journal is missing, inspect the posting request, journal ID, pending or failed state, and retry permission. Do not receive the goods a second time to repair accounting.$$),

    ('43000000-0000-0000-0000-000000000023', 'Supplier payment receipts', 'suppliers', 0,
     'Record a supplier payment',
     $$Use the supplier payment action when the business pays money to a supplier. Enter the amount and supported reference details, confirm the supplier and branch, then save once. This differs from recording a supplier invoice or receiving inventory.$$),
    ('43000000-0000-0000-0000-000000000023', 'Supplier payment receipts', 'suppliers', 1,
     'Payment capability and evidence',
     $$Creating a supplier payment requires suppliers.payment.create. The receipt list can be viewed with suppliers.account.read in the implemented profile. Keep the generated receipt ID, date, amount, user, and posting status as evidence for reconciliation.$$),
    ('43000000-0000-0000-0000-000000000023', 'Supplier payment receipts', 'suppliers', 2,
     'Avoid duplicate payments',
     $$After a timeout or posting warning, reload supplier receipts, statement, and open items before trying again. A saved receipt can exist while finance posting is pending. Repeating the payment can overstate cash outflow and settlement.$$),

    ('43000000-0000-0000-0000-000000000024', 'Supplier statement', 'suppliers', 0,
     'Statement date range',
     $$The Supplier Statement reports supplier account movements for a selected period. Without dates, the supplier service defaults from the first day of the current month through today. toDate must be on or after fromDate.$$),
    ('43000000-0000-0000-0000-000000000024', 'Supplier statement', 'suppliers', 1,
     'Reading statement lines',
     $$Review transaction date, source type, source reference, description, debit, credit, and running or closing balance as displayed. Match purchase invoices, payments, returns, reversals, and adjustments. Always state the currency and branch when communicating the balance.$$),
    ('43000000-0000-0000-0000-000000000024', 'Supplier statement', 'suppliers', 2,
     'Statement permission and export',
     $$The dedicated statement view uses suppliers.statement.view; related profile access can also depend on suppliers.account.read. Export uses the loaded statement and selected dates. An export is a snapshot and does not update when later transactions post.$$),

    ('43000000-0000-0000-0000-000000000025', 'Supplier AP aging', 'suppliers', 0,
     'Aging meaning',
     $$Supplier AP aging groups unpaid supplier documents by due-date age as of a selected date: current, 1-30, 31-60, 61-90, and over 90 days. The total is the sum of remaining open amounts, not total historical purchases.$$),
    ('43000000-0000-0000-0000-000000000025', 'Supplier AP aging', 'suppliers', 1,
     'Aging line details',
     $$Aging lines can show document date, due date, source, reference, description, open amount, days overdue, and bucket. Use the document due date and selected as-of date to explain the bucket. A future-due amount belongs in Current.$$),
    ('43000000-0000-0000-0000-000000000025', 'Supplier AP aging', 'suppliers', 2,
     'Aging access and export',
     $$AP aging is available with suppliers.statement.view in the implemented screen, with supplier read access used for related exports and profile data. Exported aging should retain supplier, branch, as-of date, currency, buckets, and source references.$$),

    ('43000000-0000-0000-0000-000000000026', 'Supplier payable open items', 'suppliers', 0,
     'What supplier open items are',
     $$Supplier open items are accounts-payable documents that remain unpaid or partly paid. Each item has original and remaining amount, currency, document and due dates, source type, and reference. Open items explain what the business still owes the supplier.$$),
    ('43000000-0000-0000-0000-000000000026', 'Supplier payable open items', 'suppliers', 1,
     'Filters and statement',
     $$The supplier Open Items tab supports status, due-before date, limit up to 200, and offset. Its statement defaults to the last 90 days when dates are omitted; its aging defaults to today. Results are always scoped to company, branch, and supplier.$$),
    ('43000000-0000-0000-0000-000000000026', 'Supplier payable open items', 'suppliers', 2,
     'Open-item capability',
     $$Viewing these AP records requires suppliers.openitems.view. A missing tab or 403 means the capability or effective branch scope is absent, not that the supplier has no balance. A valid empty result means no matching open items under the filters.$$),

    ('43000000-0000-0000-0000-000000000027', 'Settle supplier open items', 'suppliers', 0,
     'Allocate payment',
     $$A supplier payment can be applied to eligible AP open items so their remaining balances decrease. Choose the correct supplier, branch, currency, and target documents. The allocated amount must not exceed the payment or any selected item's remaining amount.$$),
    ('43000000-0000-0000-0000-000000000027', 'Settle supplier open items', 'suppliers', 1,
     'On-account supplier payment',
     $$When a payment is not fully allocated, the remainder stays on account according to the supported settlement workflow. It should later be matched to valid documents rather than creating a duplicate payment. Reload open items to confirm the committed result.$$),
    ('43000000-0000-0000-0000-000000000027', 'Settle supplier open items', 'suppliers', 2,
     'Allocation access and audit',
     $$Supplier open-item settlement requires suppliers.openitems.allocate. Keep receipt and allocation identifiers for audit and reversal. Never modify source invoices or delete supplier history merely to make the open balance agree.$$),

    ('43000000-0000-0000-0000-000000000028', 'Supplier receivables Should pay us', 'suppliers', 0,
     'Opposite balance direction',
     $$The Supplier Receivables or Should pay us tab tracks amounts the supplier owes the business. This is the opposite direction from accounts payable, where the business owes the supplier. Common causes can include approved returns, recoveries, or other supported debit documents.$$),
    ('43000000-0000-0000-0000-000000000028', 'Supplier receivables Should pay us', 'suppliers', 1,
     'Collect supplier payment',
     $$The supplier receivable workflow can record money collected from a supplier and returns a posted receipt identifier. Use it only for a genuine supplier-to-business payment against the receivable direction. Do not use the ordinary Pay Supplier action, which records business-to-supplier cash.$$),
    ('43000000-0000-0000-0000-000000000028', 'Supplier receivables Should pay us', 'suppliers', 2,
     'Separate AP and receivable reporting',
     $$A supplier can simultaneously have AP payable items and a supplier receivable. The UI reports them separately. Do not net them manually or assume one cancels the other unless an explicit supported settlement or accounting entry links them.$$),

    ('43000000-0000-0000-0000-000000000029', 'Return inventory to a supplier', 'suppliers', 0,
     'Typed return workflow',
     $$Inventory-affecting supplier returns must use the typed POST /api/inventory/supplier-returns workflow. Select the original product or serialized unit, supplier, quantity, cost, reason, and applicable source reference. The branch setting inventory.allowSupplierReturns must permit returns.$$),
    ('43000000-0000-0000-0000-000000000029', 'Return inventory to a supplier', 'suppliers', 1,
     'Stock and finance effects',
     $$A completed supplier return can reduce branch inventory and create the corresponding finance posting or supplier-side balance effect. For serialized stock, verify the exact serial or IMEI and current availability. Never use a generic supplier product-history insert to imitate a stock return.$$),
    ('43000000-0000-0000-0000-000000000029', 'Return inventory to a supplier', 'suppliers', 2,
     'Posting failure handling',
     $$A return can be saved while finance posting is pending or failed. Inspect posting status, request ID, journal ID, and failure reason, then use the authorized retry action. Do not return the same goods twice to compensate for a failed journal.$$),

    ('43000000-0000-0000-0000-000000000030', 'Supplier audit and exports', 'suppliers', 0,
     'Audit trail',
     $$The supplier Audit Trail can show time, event, actor, source, source ID, summary, and recorded changes. Its default service period is the last 30 days through today; page starts at zero and size defaults to 50 with a maximum of 200.$$),
    ('43000000-0000-0000-0000-000000000030', 'Supplier audit and exports', 'suppliers', 1,
     'Supplier exports',
     $$The supplier list, statement, AP aging, and audit views can export the data currently loaded by the authorized user. Confirm filters before export. The spreadsheet is a point-in-time copy and should include supplier identity, company or branch context, and selected dates.$$),
    ('43000000-0000-0000-0000-000000000030', 'Supplier audit and exports', 'suppliers', 2,
     'Evidence and privacy',
     $$Use audit events to identify who changed supplier state or related records, but verify the referenced source transaction for full financial evidence. Supplier contact, balances, and audit payloads are business-sensitive and must be shared only with authorized recipients.$$),

    ('43000000-0000-0000-0000-000000000031', 'Supplier access and troubleshooting', 'suppliers', 0,
     'Core supplier capabilities',
     $$Supplier listing and profiles use suppliers.account.read or the applicable list permission. Create, edit, delete, export, statement, payment, open-item view, and open-item allocation are distinct capabilities. A visible module does not grant every action inside it.$$),
    ('43000000-0000-0000-0000-000000000031', 'Supplier access and troubleshooting', 'suppliers', 1,
     'Supplier not found or action hidden',
     $$Confirm company, current branch, search text, status filter, archived state, and effective capability. Supplier profiles are branch records; a supplier at another branch is not automatically in the selected branch unless copied. Do not change URL identifiers to bypass branch selection.$$),
    ('43000000-0000-0000-0000-000000000031', 'Supplier access and troubleshooting', 'suppliers', 2,
     'Balance reconciliation checklist',
     $$Compare purchases, supplier payments, AP open items, statement, returns, supplier receivables, currencies, dates, and finance posting states. Preserve reference IDs and errors. Never duplicate a purchase, receipt, payment, or return solely because one tab has stale or failed data.$$),

    ('43000000-0000-0000-0000-000000000032', 'Suppliers Arabic English terminology', 'suppliers', 0,
     'Core supplier terms',
     $$الموردون = suppliers or vendors; إضافة مورد = add supplier; تعديل المورد = edit supplier; نسخ الموردين من فرع = copy suppliers from branch; أرشفة المورد = archive supplier; إعادة تنشيط المورد = reactivate supplier; سبب الأرشفة = archive reason; موقع المورد = supplier location; النشاط = supplier major or category.$$),
    ('43000000-0000-0000-0000-000000000032', 'Suppliers Arabic English terminology', 'suppliers', 1,
     'Payable terms',
     $$الذمم الدائنة = accounts payable or AP; مستحقات المورد = supplier payable; البنود المفتوحة = open items; كشف حساب المورد = supplier statement; أعمار ديون الموردين = supplier AP aging; دفعة للمورد = supplier payment; إيصال المورد = supplier receipt; المبلغ المتبقي = remaining amount; مسدد بالكامل = fully settled.$$),
    ('43000000-0000-0000-0000-000000000032', 'Suppliers Arabic English terminology', 'suppliers', 2,
     'Return and opposite-balance terms',
     $$مرتجع للمورد = supplier return; المنتجات المشتراة = purchased or received products; المورد مدين لنا or يجب أن يدفع لنا = supplier receivable or Should pay us; سجل التدقيق = audit trail; تاريخ الاستحقاق = due date; المبلغ المفتوح = open amount; متأخر السداد = overdue; ترحيل مالي معلق = pending finance posting.$$);

INSERT INTO public.ai_document
    (id, company_id, title, document_type, module, language, content,
     metadata_json, active, created_at, updated_at)
SELECT
    document_id,
    NULL,
    title,
    'HELP_ARTICLE',
    module,
    'en',
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    '{"seed":"rag-clients-suppliers-detail-v1","source":"implemented-clients-suppliers-workflows"}',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_clients_suppliers_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    document_type = EXCLUDED.document_type,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json,
    active = true,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_document_chunk
    (id, document_id, company_id, title, module, language, chunk_index,
     content, metadata_json, created_at)
SELECT
    md5('legacy-clients-suppliers-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    title,
    module,
    'en',
    chunk_index,
    heading || E'\n' || content,
    '{"seed":"rag-clients-suppliers-detail-v1","retrieval":"keyword"}',
    CURRENT_TIMESTAMP
FROM vls_ai_clients_suppliers_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    title = EXCLUDED.title,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    content = EXCLUDED.content,
    metadata_json = EXCLUDED.metadata_json;

INSERT INTO public.ai_knowledge_document
    (id, company_id, branch_id, module, language, document_type, title,
     source_type, source_uri, content_hash, raw_content, normalized_content,
     status, metadata_json, created_at, updated_at)
SELECT
    document_id,
    NULL,
    NULL,
    module,
    'en',
    'HELP_ARTICLE',
    title,
    'APPLICATION',
    'valueinsoft://help/clients-suppliers/' || replace(lower(title), ' ', '-'),
    md5(string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index)),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    string_agg(heading || E'\n' || content, E'\n\n' ORDER BY chunk_index),
    'ACTIVE',
    '{"seed":"rag-clients-suppliers-detail-v1","source":"implemented-clients-suppliers-workflows"}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM vls_ai_clients_suppliers_detail_chunk
GROUP BY document_id, title, module
ON CONFLICT (id) DO UPDATE SET
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    document_type = EXCLUDED.document_type,
    title = EXCLUDED.title,
    source_type = EXCLUDED.source_type,
    source_uri = EXCLUDED.source_uri,
    content_hash = EXCLUDED.content_hash,
    raw_content = EXCLUDED.raw_content,
    normalized_content = EXCLUDED.normalized_content,
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO public.ai_knowledge_chunk
    (id, document_id, company_id, branch_id, module, language, chunk_index,
     heading, content, token_count, embedding, embedding_model, status,
     metadata_json, created_at)
SELECT
    md5('knowledge-clients-suppliers-detail:' || document_id::text || ':' || chunk_index::text)::uuid,
    document_id,
    NULL,
    NULL,
    module,
    'en',
    chunk_index,
    heading,
    content,
    cardinality(regexp_split_to_array(btrim(content), E'\\s+')),
    NULL,
    'keyword-fallback',
    'ACTIVE',
    '{"seed":"rag-clients-suppliers-detail-v1","embeddingStatus":"pending-real-provider"}'::jsonb,
    CURRENT_TIMESTAMP
FROM vls_ai_clients_suppliers_detail_chunk
ON CONFLICT (id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    company_id = EXCLUDED.company_id,
    branch_id = EXCLUDED.branch_id,
    module = EXCLUDED.module,
    language = EXCLUDED.language,
    chunk_index = EXCLUDED.chunk_index,
    heading = EXCLUDED.heading,
    content = EXCLUDED.content,
    token_count = EXCLUDED.token_count,
    embedding = NULL,
    embedding_model = 'keyword-fallback',
    status = 'ACTIVE',
    metadata_json = EXCLUDED.metadata_json;

DROP TABLE vls_ai_clients_suppliers_detail_chunk;
