INSERT INTO public.platform_modules (
    module_id,
    display_name,
    category,
    status,
    default_enabled,
    config_version,
    description
) VALUES
    ('pos_checkout', 'POS checkout', 'operations', 'active', FALSE, 'v1', 'Point of sale checkout and cashier sales screen.'),
    ('pos_returns', 'POS returns and bounced-back sales', 'operations', 'active', FALSE, 'v1', 'Sales return and bounced-back item handling in the POS flow.'),
    ('inventory_catalog', 'Inventory catalog', 'inventory', 'active', FALSE, 'v1', 'Browse inventory items, stock, pricing, and catalog data.'),
    ('inventory_item_management', 'Inventory item management', 'inventory', 'active', FALSE, 'v1', 'Create and edit inventory products and item master data.'),
    ('inventory_transactions', 'Inventory transactions', 'inventory', 'active', FALSE, 'v1', 'View inventory history, movements, and transaction records.'),
    ('inventory_bounced_back', 'Inventory bounced-back and damages', 'inventory', 'active', FALSE, 'v1', 'Track damaged, bounced-back, and returned inventory items.'),
    ('inventory_barcode', 'Inventory barcode labels', 'inventory', 'active', FALSE, 'v1', 'Generate and print barcode labels for inventory items.'),
    ('inventory_scanner', 'Inventory scanner workflow', 'inventory', 'active', FALSE, 'v1', 'Use scanner-assisted inventory and product workflows.'),
    ('inventory_categories', 'Inventory categories', 'inventory', 'active', FALSE, 'v1', 'Manage inventory categories and category configuration.'),
    ('suppliers_management', 'Supplier management', 'inventory', 'active', FALSE, 'v1', 'Supplier directory, procurement support, and supplier receipts.'),
    ('clients_management', 'Client management', 'crm', 'active', TRUE, 'v1', 'Client account creation, lookup, and customer records.'),
    ('client_vouchers', 'Client vouchers', 'finance', 'active', FALSE, 'v1', 'Client voucher and account balance workflows.'),
    ('finance_sales_reports', 'Sales reports', 'finance', 'active', FALSE, 'v1', 'Sales reporting and commercial reporting screens.'),
    ('finance_expenses', 'Expenses', 'finance', 'active', FALSE, 'v1', 'Expense entry and expense management screens.'),
    ('company_billing_settings', 'Company billing and settings', 'admin', 'active', TRUE, 'v1', 'Company settings, billing, and subscription recovery screen.'),
    ('user_management', 'User management', 'admin', 'active', TRUE, 'v1', 'Tenant user creation, editing, and role management.')
ON CONFLICT (module_id) DO UPDATE
SET
    display_name = EXCLUDED.display_name,
    category = EXCLUDED.category,
    status = EXCLUDED.status,
    default_enabled = EXCLUDED.default_enabled,
    config_version = EXCLUDED.config_version,
    description = EXCLUDED.description,
    updated_at = NOW();

INSERT INTO public.package_module_policies (
    package_id,
    module_id,
    enabled,
    mode,
    limits,
    policy_version
) VALUES
    ('starter', 'pos_checkout', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'pos_returns', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'inventory_catalog', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'inventory_item_management', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'inventory_transactions', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'inventory_bounced_back', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'inventory_barcode', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'inventory_scanner', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'inventory_categories', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'suppliers_management', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'clients_management', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'client_vouchers', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'finance_sales_reports', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'finance_expenses', FALSE, NULL, '{}'::jsonb, 'v1'),
    ('starter', 'company_billing_settings', TRUE, 'basic', '{}'::jsonb, 'v1'),
    ('starter', 'user_management', TRUE, 'basic', '{"max_users": 5}'::jsonb, 'v1'),
    ('pro', 'pos_checkout', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'pos_returns', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_catalog', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_item_management', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_transactions', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_bounced_back', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_barcode', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_scanner', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'inventory_categories', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'suppliers_management', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'clients_management', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'client_vouchers', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'finance_sales_reports', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'finance_expenses', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'company_billing_settings', TRUE, 'standard', '{}'::jsonb, 'v1'),
    ('pro', 'user_management', TRUE, 'advanced', '{"max_users": 40}'::jsonb, 'v1'),
    ('enterprise', 'pos_checkout', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'pos_returns', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_catalog', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_item_management', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_transactions', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_bounced_back', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_barcode', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_scanner', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'inventory_categories', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'suppliers_management', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'clients_management', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'client_vouchers', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'finance_sales_reports', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'finance_expenses', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'company_billing_settings', TRUE, 'advanced', '{}'::jsonb, 'v1'),
    ('enterprise', 'user_management', TRUE, 'advanced', '{"max_users": 500}'::jsonb, 'v1')
ON CONFLICT (package_id, module_id) DO UPDATE
SET
    enabled = EXCLUDED.enabled,
    mode = EXCLUDED.mode,
    limits = EXCLUDED.limits,
    policy_version = EXCLUDED.policy_version,
    updated_at = NOW();
