-- ==========================================================
-- V74 — POS Offline Sync Foundation Tables
-- ==========================================================
-- These tables support the offline POS sync module.
-- They live in the PUBLIC schema because device registration
-- and sync batch tracking are cross-tenant management concerns.
-- The company_id / branch_id columns enable tenant scoping at
-- the query level.
-- ==========================================================

-- 1. pos_device — Registered POS devices per tenant/company/branch
CREATE TABLE IF NOT EXISTS pos_device (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    device_code     VARCHAR(100)  NOT NULL,
    device_name     VARCHAR(200),
    client_type     VARCHAR(50)   NOT NULL,
    platform        VARCHAR(50),
    status          VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
    allowed_offline BOOLEAN       NOT NULL DEFAULT FALSE,
    max_offline_hours INTEGER     NOT NULL DEFAULT 24,
    app_version     VARCHAR(50),
    last_heartbeat_at TIMESTAMPTZ,
    registered_by   BIGINT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_pos_device_code
        UNIQUE (company_id, branch_id, device_code),

    CONSTRAINT chk_pos_device_status
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'INACTIVE')),

    CONSTRAINT chk_pos_device_client_type
        CHECK (client_type IN (
            'WEB_PWA',
            'REACT_NATIVE_ANDROID',
            'REACT_NATIVE_IOS',
            'DESKTOP_POS',
            'TABLET_POS'
        ))
);

-- 2. pos_sync_batch — One sync attempt from one POS device
CREATE TABLE IF NOT EXISTS pos_sync_batch (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT        NOT NULL,
    branch_id           BIGINT        NOT NULL,
    device_id           BIGINT        NOT NULL,
    cashier_id          BIGINT        NOT NULL,
    client_batch_id     VARCHAR(150)  NOT NULL,
    client_type         VARCHAR(50)   NOT NULL,
    platform            VARCHAR(50),
    app_version         VARCHAR(50),
    status              VARCHAR(30)   NOT NULL DEFAULT 'RECEIVED',
    total_orders        INTEGER       NOT NULL DEFAULT 0,
    synced_orders       INTEGER       NOT NULL DEFAULT 0,
    failed_orders       INTEGER       NOT NULL DEFAULT 0,
    duplicate_orders    INTEGER       NOT NULL DEFAULT 0,
    needs_review_orders INTEGER       NOT NULL DEFAULT 0,
    offline_started_at  TIMESTAMPTZ,
    sync_started_at     TIMESTAMPTZ,
    sync_completed_at   TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_sync_batch_device
        FOREIGN KEY (device_id) REFERENCES pos_device (id),

    CONSTRAINT uq_sync_batch_client
        UNIQUE (company_id, branch_id, device_id, client_batch_id),

    CONSTRAINT chk_sync_batch_status
        CHECK (status IN (
            'RECEIVED',
            'PROCESSING',
            'PARTIALLY_SYNCED',
            'SYNCED',
            'FAILED'
        ))
);

-- 3. pos_offline_order_import — Raw offline order payloads and processing status
CREATE TABLE IF NOT EXISTS pos_offline_order_import (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_batch_id           BIGINT        NOT NULL,
    company_id              BIGINT        NOT NULL,
    branch_id               BIGINT        NOT NULL,
    device_id               BIGINT        NOT NULL,
    cashier_id              BIGINT        NOT NULL,
    offline_order_no        VARCHAR(150)  NOT NULL,
    idempotency_key         VARCHAR(200)  NOT NULL,
    local_order_created_at  TIMESTAMPTZ,
    payload_json            JSONB         NOT NULL,
    payload_hash            VARCHAR(128)  NOT NULL,
    status                  VARCHAR(30)   NOT NULL DEFAULT 'PENDING',
    official_order_id       BIGINT,
    official_invoice_no     VARCHAR(100),
    error_code              VARCHAR(100),
    error_message           TEXT,
    retry_count             INTEGER       NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    processed_at            TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_order_import_batch
        FOREIGN KEY (sync_batch_id) REFERENCES pos_sync_batch (id),

    CONSTRAINT fk_order_import_device
        FOREIGN KEY (device_id) REFERENCES pos_device (id),

    CONSTRAINT uq_order_import_idempotency
        UNIQUE (company_id, branch_id, device_id, idempotency_key),

    CONSTRAINT chk_order_import_status
        CHECK (status IN (
            'PENDING',
            'PROCESSING',
            'SYNCED',
            'FAILED',
            'DUPLICATE',
            'NEEDS_REVIEW'
        ))
);

-- 4. pos_idempotency_key — Prevents duplicate invoice/order creation
CREATE TABLE IF NOT EXISTS pos_idempotency_key (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT        NOT NULL,
    branch_id           BIGINT        NOT NULL,
    device_id           BIGINT        NOT NULL,
    idempotency_key     VARCHAR(200)  NOT NULL,
    offline_order_no    VARCHAR(150)  NOT NULL,
    request_hash        VARCHAR(128)  NOT NULL,
    status              VARCHAR(30)   NOT NULL DEFAULT 'PROCESSING',
    official_order_id   BIGINT,
    official_invoice_no VARCHAR(100),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_idempotency_device
        FOREIGN KEY (device_id) REFERENCES pos_device (id),

    CONSTRAINT uq_idempotency_key
        UNIQUE (company_id, branch_id, device_id, idempotency_key),

    CONSTRAINT chk_idempotency_status
        CHECK (status IN (
            'PROCESSING',
            'SYNCED',
            'FAILED',
            'DUPLICATE',
            'NEEDS_REVIEW'
        ))
);

-- 5. pos_offline_order_error — Detailed validation and processing errors
CREATE TABLE IF NOT EXISTS pos_offline_order_error (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offline_order_import_id  BIGINT        NOT NULL,
    company_id               BIGINT        NOT NULL,
    branch_id                BIGINT        NOT NULL,
    error_stage              VARCHAR(50)   NOT NULL,
    error_code               VARCHAR(100)  NOT NULL,
    error_message            TEXT          NOT NULL,
    field_path               VARCHAR(300),
    raw_value                TEXT,
    severity                 VARCHAR(30)   NOT NULL DEFAULT 'HARD_FAIL',
    retry_allowed            BOOLEAN       NOT NULL DEFAULT FALSE,
    manager_review_required  BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_order_error_import
        FOREIGN KEY (offline_order_import_id) REFERENCES pos_offline_order_import (id),

    CONSTRAINT chk_order_error_severity
        CHECK (severity IN (
            'HARD_FAIL',
            'NEEDS_REVIEW',
            'WARNING',
            'RETRYABLE_ERROR',
            'SYSTEM_ERROR'
        ))
);

-- 6. pos_bootstrap_version — Tracks offline cache data version
CREATE TABLE IF NOT EXISTS pos_bootstrap_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT        NOT NULL,
    branch_id       BIGINT        NOT NULL,
    data_type       VARCHAR(50)   NOT NULL,
    version_no      BIGINT        NOT NULL DEFAULT 1,
    checksum        VARCHAR(128),
    last_changed_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_bootstrap_version
        UNIQUE (company_id, branch_id, data_type),

    CONSTRAINT chk_bootstrap_data_type
        CHECK (data_type IN (
            'PRODUCTS',
            'PRICES',
            'TAXES',
            'DISCOUNTS',
            'PAYMENT_METHODS',
            'CASHIER_PERMISSIONS',
            'POS_SETTINGS'
        ))
);

-- 7. pos_device_session — POS device/cashier sessions
CREATE TABLE IF NOT EXISTS pos_device_session (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT        NOT NULL,
    branch_id          BIGINT        NOT NULL,
    device_id          BIGINT        NOT NULL,
    cashier_id         BIGINT        NOT NULL,
    session_token_hash VARCHAR(256),
    status             VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
    login_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    logout_at          TIMESTAMPTZ,
    last_seen_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_session_device
        FOREIGN KEY (device_id) REFERENCES pos_device (id),

    CONSTRAINT chk_session_status
        CHECK (status IN ('ACTIVE', 'EXPIRED', 'LOGGED_OUT', 'BLOCKED'))
);

-- 8. pos_sync_audit_log — General audit log for offline sync events
CREATE TABLE IF NOT EXISTS pos_sync_audit_log (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               BIGINT        NOT NULL,
    branch_id                BIGINT        NOT NULL,
    sync_batch_id            BIGINT,
    offline_order_import_id  BIGINT,
    device_id                BIGINT,
    cashier_id               BIGINT,
    event_type               VARCHAR(100)  NOT NULL,
    event_message            TEXT,
    payload_json             JSONB,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_audit_sync_batch
        FOREIGN KEY (sync_batch_id) REFERENCES pos_sync_batch (id),

    CONSTRAINT fk_audit_order_import
        FOREIGN KEY (offline_order_import_id) REFERENCES pos_offline_order_import (id),

    CONSTRAINT fk_audit_device
        FOREIGN KEY (device_id) REFERENCES pos_device (id)
);
