-- ==========================================================
-- V77 - POS Offline Sync Tenant Tables
-- ==========================================================
-- V74/V75 created public.pos_* tables. Those public tables are
-- deprecated compatibility artifacts and must not be used for
-- normal offline sync runtime access.
--
-- This migration creates an idempotent helper that provisions the
-- offline sync tables inside each tenant schema (c_{companyId}).
-- ==========================================================

CREATE OR REPLACE FUNCTION public.create_offline_sync_tables_for_tenant(schema_name text)
RETURNS void AS $$
BEGIN
    IF schema_name IS NULL OR schema_name NOT LIKE 'c\_%' ESCAPE '\' THEN
        RAISE EXCEPTION 'Offline sync tenant schema must start with c_: %', schema_name;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schemata.schema_name = $1
    ) THEN
        RAISE EXCEPTION 'Offline sync tenant schema does not exist: %', schema_name;
    END IF;

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_device (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id          BIGINT        NOT NULL,
            branch_id           BIGINT        NOT NULL,
            device_code         VARCHAR(100)  NOT NULL,
            device_name         VARCHAR(200),
            client_type         VARCHAR(50)   NOT NULL,
            platform            VARCHAR(50),
            status              VARCHAR(30)   NOT NULL DEFAULT ''ACTIVE'',
            allowed_offline     BOOLEAN       NOT NULL DEFAULT FALSE,
            max_offline_hours   INTEGER       NOT NULL DEFAULT 24,
            app_version         VARCHAR(50),
            last_heartbeat_at   TIMESTAMPTZ,
            registered_by       BIGINT,
            created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_pos_device_code UNIQUE (company_id, branch_id, device_code),
            CONSTRAINT chk_pos_device_status CHECK (status IN (''ACTIVE'', ''BLOCKED'', ''INACTIVE'')),
            CONSTRAINT chk_pos_device_client_type CHECK (client_type IN (
                ''WEB_PWA'',
                ''REACT_NATIVE_ANDROID'',
                ''REACT_NATIVE_IOS'',
                ''DESKTOP_POS'',
                ''TABLET_POS''
            ))
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_sync_batch (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id          BIGINT        NOT NULL,
            branch_id           BIGINT        NOT NULL,
            device_id           BIGINT        NOT NULL,
            cashier_id          BIGINT        NOT NULL,
            client_batch_id     VARCHAR(150)  NOT NULL,
            client_type         VARCHAR(50)   NOT NULL,
            platform            VARCHAR(50),
            app_version         VARCHAR(50),
            status              VARCHAR(30)   NOT NULL DEFAULT ''RECEIVED'',
            total_orders        INTEGER       NOT NULL DEFAULT 0,
            synced_orders       INTEGER       NOT NULL DEFAULT 0,
            failed_orders       INTEGER       NOT NULL DEFAULT 0,
            duplicate_orders    INTEGER       NOT NULL DEFAULT 0,
            needs_review_orders INTEGER       NOT NULL DEFAULT 0,
            offline_started_at  TIMESTAMPTZ,
            sync_started_at     TIMESTAMPTZ,
            sync_completed_at   TIMESTAMPTZ,
            created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_sync_batch_device FOREIGN KEY (device_id) REFERENCES %I.pos_device (id),
            CONSTRAINT uq_sync_batch_client UNIQUE (company_id, branch_id, device_id, client_batch_id),
            CONSTRAINT chk_sync_batch_status CHECK (status IN (
                ''RECEIVED'',
                ''PROCESSING'',
                ''PARTIALLY_SYNCED'',
                ''SYNCED'',
                ''FAILED''
            ))
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_offline_order_import (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sync_batch_id           BIGINT        NOT NULL,
            company_id              BIGINT        NOT NULL,
            branch_id               BIGINT        NOT NULL,
            device_id               BIGINT        NOT NULL,
            cashier_id              BIGINT        NOT NULL,
            offline_order_no        VARCHAR(150)  NOT NULL,
            idempotency_key         VARCHAR(200)  NOT NULL,
            local_order_created_at  TIMESTAMPTZ,
            payload_json            JSONB         NOT NULL,
            payload_hash            VARCHAR(128)  NOT NULL,
            status                  VARCHAR(30)   NOT NULL DEFAULT ''PENDING'',
            official_order_id       BIGINT,
            official_invoice_no     VARCHAR(100),
            error_code              VARCHAR(100),
            error_message           TEXT,
            retry_count             INTEGER       NOT NULL DEFAULT 0,
            last_retry_at           TIMESTAMPTZ,
            created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            processing_started_at   TIMESTAMPTZ,
            processed_at            TIMESTAMPTZ,
            updated_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_order_import_batch FOREIGN KEY (sync_batch_id) REFERENCES %I.pos_sync_batch (id),
            CONSTRAINT fk_order_import_device FOREIGN KEY (device_id) REFERENCES %I.pos_device (id),
            CONSTRAINT uq_order_import_idempotency UNIQUE (company_id, branch_id, device_id, idempotency_key),
            CONSTRAINT chk_order_import_status CHECK (status IN (
                ''PENDING'',
                ''PENDING_RETRY'',
                ''PROCESSING'',
                ''READY_FOR_VALIDATION'',
                ''VALIDATING'',
                ''VALIDATED'',
                ''VALIDATION_FAILED'',
                ''SYNCED'',
                ''FAILED'',
                ''DUPLICATE'',
                ''NEEDS_REVIEW''
            ))
        )', schema_name, schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_idempotency_key (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id          BIGINT        NOT NULL,
            branch_id           BIGINT        NOT NULL,
            device_id           BIGINT        NOT NULL,
            idempotency_key     VARCHAR(200)  NOT NULL,
            offline_order_no    VARCHAR(150)  NOT NULL,
            request_hash        VARCHAR(128)  NOT NULL,
            status              VARCHAR(30)   NOT NULL DEFAULT ''RECEIVED'',
            official_order_id   BIGINT,
            official_invoice_no VARCHAR(100),
            created_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_idempotency_device FOREIGN KEY (device_id) REFERENCES %I.pos_device (id),
            CONSTRAINT uq_idempotency_key UNIQUE (company_id, branch_id, device_id, idempotency_key),
            CONSTRAINT chk_idempotency_status CHECK (status IN (
                ''RECEIVED'',
                ''PROCESSING'',
                ''SYNCED'',
                ''FAILED'',
                ''DUPLICATE'',
                ''NEEDS_REVIEW'',
                ''PAYLOAD_MISMATCH''
            ))
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_offline_order_error (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            offline_order_import_id  BIGINT        NOT NULL,
            company_id               BIGINT        NOT NULL,
            branch_id                BIGINT        NOT NULL,
            error_stage              VARCHAR(50)   NOT NULL,
            error_code               VARCHAR(100)  NOT NULL,
            error_message            TEXT          NOT NULL,
            field_path               VARCHAR(300),
            raw_value                TEXT,
            severity                 VARCHAR(30)   NOT NULL DEFAULT ''HARD_FAIL'',
            retry_allowed            BOOLEAN       NOT NULL DEFAULT FALSE,
            manager_review_required  BOOLEAN       NOT NULL DEFAULT FALSE,
            created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_order_error_import FOREIGN KEY (offline_order_import_id) REFERENCES %I.pos_offline_order_import (id),
            CONSTRAINT chk_order_error_severity CHECK (severity IN (
                ''HARD_FAIL'',
                ''NEEDS_REVIEW'',
                ''WARNING'',
                ''RETRYABLE_ERROR'',
                ''SYSTEM_ERROR''
            ))
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_bootstrap_version (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id      BIGINT        NOT NULL,
            branch_id       BIGINT        NOT NULL,
            data_type       VARCHAR(50)   NOT NULL,
            version_no      BIGINT        NOT NULL DEFAULT 1,
            checksum        VARCHAR(128),
            last_changed_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_bootstrap_version UNIQUE (company_id, branch_id, data_type),
            CONSTRAINT chk_bootstrap_data_type CHECK (data_type IN (
                ''PRODUCTS'',
                ''PRICES'',
                ''TAXES'',
                ''DISCOUNTS'',
                ''PAYMENT_METHODS'',
                ''CASHIER_PERMISSIONS'',
                ''POS_SETTINGS''
            ))
        )', schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_device_session (
            id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id         BIGINT        NOT NULL,
            branch_id          BIGINT        NOT NULL,
            device_id          BIGINT        NOT NULL,
            cashier_id         BIGINT        NOT NULL,
            session_token_hash VARCHAR(256),
            status             VARCHAR(30)   NOT NULL DEFAULT ''ACTIVE'',
            login_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            logout_at          TIMESTAMPTZ,
            last_seen_at       TIMESTAMPTZ,
            created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_session_device FOREIGN KEY (device_id) REFERENCES %I.pos_device (id),
            CONSTRAINT chk_session_status CHECK (status IN (''ACTIVE'', ''EXPIRED'', ''LOGGED_OUT'', ''BLOCKED''))
        )', schema_name, schema_name);

    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.pos_sync_audit_log (
            id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_id               BIGINT        NOT NULL,
            branch_id                BIGINT        NOT NULL,
            sync_batch_id            BIGINT,
            offline_order_import_id  BIGINT,
            device_id                BIGINT,
            cashier_id               BIGINT,
            event_type               VARCHAR(100)  NOT NULL,
            event_message            TEXT,
            payload_json             JSONB,
            created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            CONSTRAINT fk_audit_sync_batch FOREIGN KEY (sync_batch_id) REFERENCES %I.pos_sync_batch (id),
            CONSTRAINT fk_audit_order_import FOREIGN KEY (offline_order_import_id) REFERENCES %I.pos_offline_order_import (id),
            CONSTRAINT fk_audit_device FOREIGN KEY (device_id) REFERENCES %I.pos_device (id)
        )', schema_name, schema_name, schema_name, schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_device (company_id, branch_id, status)',
        'idx_pos_device_company_branch_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_device (last_heartbeat_at)',
        'idx_pos_device_heartbeat', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_sync_batch (company_id, branch_id, status, created_at)',
        'idx_sync_batch_company_status_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_sync_batch (device_id, created_at)',
        'idx_sync_batch_device_created', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_offline_order_import (sync_batch_id, status)',
        'idx_order_import_batch_status', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_offline_order_import (company_id, branch_id, status, created_at)',
        'idx_order_import_company_status_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_offline_order_import (company_id, branch_id, offline_order_no)',
        'idx_order_import_offline_order_no', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_idempotency_key (official_order_id) WHERE official_order_id IS NOT NULL',
        'idx_idempotency_official_order', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_idempotency_key (official_invoice_no) WHERE official_invoice_no IS NOT NULL',
        'idx_idempotency_official_invoice', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_offline_order_error (offline_order_import_id)',
        'idx_order_error_import', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_offline_order_error (company_id, branch_id, error_code, created_at)',
        'idx_order_error_company_code_created', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_device_session (company_id, branch_id, device_id, cashier_id, status)',
        'idx_device_session_lookup', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_device_session (last_seen_at)',
        'idx_device_session_last_seen', schema_name);

    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_sync_audit_log (company_id, branch_id, created_at)',
        'idx_sync_audit_company_created', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_sync_audit_log (sync_batch_id) WHERE sync_batch_id IS NOT NULL',
        'idx_sync_audit_batch', schema_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I.pos_sync_audit_log (offline_order_import_id) WHERE offline_order_import_id IS NOT NULL',
        'idx_sync_audit_order_import', schema_name);
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
    r record;
BEGIN
    FOR r IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name LIKE 'c\_%' ESCAPE '\'
    LOOP
        PERFORM public.create_offline_sync_tables_for_tenant(r.schema_name);
    END LOOP;
END $$;
